# See Dependabot documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions
  # Updates workflow dependencies and groups them into a single PR
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    # Group all GitHub Actions updates into a single PR
    groups:
      all-actions:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"
    # Ignore patch updates to reduce noise
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  
  # Pub Packages
  # Each package groups all dependency updates into a single PR per week
  
  # stream_video (Low-level client)
  - package-ecosystem: "pub"
    directory: "/packages/stream_video"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"
  
  # stream_video_flutter (UI components)
  - package-ecosystem: "pub"
    directory: "/packages/stream_video_flutter"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"
  
  # stream_video_noise_cancellation (Noise cancellation)
  - package-ecosystem: "pub"
    directory: "/packages/stream_video_noise_cancellation"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"
  
  # stream_video_push_notification (Push notifications)
  - package-ecosystem: "pub"
    directory: "/packages/stream_video_push_notification"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"
  
  # stream_video_screen_sharing (Screen sharing)
  - package-ecosystem: "pub"
    directory: "/packages/stream_video_screen_sharing"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"
  
  # Dogfooding App (Sample app)
  - package-ecosystem: "pub"
    directory: "/dogfooding"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      all-dependencies:
        patterns: ["*"]
    commit-message:
      prefix: "chore(deps)"

