// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:retrofit/retrofit.dart';
import 'package:stream_core/stream_core.dart';

import '../models.dart';

part 'default_api.g.dart';

@RestApi(callAdapter: _ResultCallAdapter)
abstract interface class DefaultApi {
  factory DefaultApi(
    Dio dio, {
    String? baseUrl,
  }) = _DefaultApi;

  @POST('/api/v2/video/call/{type}/{id}/accept')
  Future<Result<AcceptCallResponse>> acceptCall({
    @Path('type') required String type,
    @Path('id') required String id,
  });

  @POST('/api/v2/usergroups/{id}/members')
  Future<Result<AddUserGroupMembersResponse>> addUserGroupMembers({
    @Path('id') required String id,
    @Body() required AddUserGroupMembersRequest addUserGroupMembersRequest,
  });

  @POST('/api/v2/moderation/appeal')
  Future<Result<AppealResponse>> appeal({
    @Body() required AppealRequest appealRequest,
  });

  @POST('/api/v2/moderation/ban')
  Future<Result<BanResponse>> ban({
    @Body() required BanRequest banRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/block')
  Future<Result<BlockUserResponse>> blockUser({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required BlockUserRequest blockUserRequest,
  });

  @POST('/api/v2/users/block')
  Future<Result<BlockUsersResponse>> blockUsers({
    @Body() required BlockUsersRequest blockUsersRequest,
  });

  @POST('/api/v2/moderation/appeals/bulk_action')
  Future<Result<BulkActionAppealsResponse>> bulkActionAppeals({
    @Body() required BulkActionAppealsRequest bulkActionAppealsRequest,
  });

  @POST('/api/v2/moderation/action_config/bulk_delete')
  Future<Result<BulkDeleteActionConfigResponse>> bulkDeleteActionConfig({
    @Body()
    required BulkDeleteActionConfigRequest bulkDeleteActionConfigRequest,
  });

  @POST('/api/v2/moderation/action_config/bulk')
  Future<Result<BulkUpsertActionConfigResponse>> bulkUpsertActionConfig({
    @Body()
    required BulkUpsertActionConfigRequest bulkUpsertActionConfigRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/feedback')
  Future<Result<CollectUserFeedbackResponse>> collectUserFeedback({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required CollectUserFeedbackRequest collectUserFeedbackRequest,
  });

  @POST('/api/v2/blocklists')
  Future<Result<CreateBlockListResponse>> createBlockList({
    @Body() required CreateBlockListRequest createBlockListRequest,
  });

  @POST('/api/v2/devices')
  Future<Result<DurationResponse>> createDevice({
    @Body() required CreateDeviceRequest createDeviceRequest,
  });

  @POST('/api/v2/guest')
  Future<Result<CreateGuestResponse>> createGuest({
    @Body() required CreateGuestRequest createGuestRequest,
  });

  @POST('/api/v2/polls')
  Future<Result<PollResponse>> createPoll({
    @Body() required CreatePollRequest createPollRequest,
  });

  @POST('/api/v2/polls/{poll_id}/options')
  Future<Result<PollOptionResponse>> createPollOption({
    @Path('poll_id') required String pollId,
    @Body() required CreatePollOptionRequest createPollOptionRequest,
  });

  @POST('/api/v2/usergroups')
  Future<Result<CreateUserGroupResponse>> createUserGroup({
    @Body() required CreateUserGroupRequest createUserGroupRequest,
  });

  @DELETE('/api/v2/moderation/action_config/{id}')
  Future<Result<DeleteActionConfigResponse>> deleteActionConfig({
    @Path('id') required String id,
  });

  @DELETE('/api/v2/blocklists/{name}')
  Future<Result<DurationResponse>> deleteBlockList({
    @Path('name') required String name,
    @Query('team') String? team,
  });

  @POST('/api/v2/video/call/{type}/{id}/delete')
  Future<Result<DeleteCallResponse>> deleteCall({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() DeleteCallRequest? deleteCallRequest,
  });

  @DELETE('/api/v2/moderation/config/{key}')
  Future<Result<DeleteModerationConfigResponse>> deleteConfig({
    @Path('key') required String key,
    @Query('team') String? team,
  });

  @DELETE('/api/v2/devices')
  Future<Result<DurationResponse>> deleteDevice({
    @Query('id') required String id,
  });

  @DELETE('/api/v2/uploads/file')
  Future<Result<DurationResponse>> deleteFile({
    @Query('url') String? url,
  });

  @DELETE('/api/v2/uploads/image')
  Future<Result<DurationResponse>> deleteImage({
    @Query('url') String? url,
  });

  @DELETE('/api/v2/polls/{poll_id}')
  Future<Result<DurationResponse>> deletePoll({
    @Path('poll_id') required String pollId,
    @Query('user_id') String? userId,
  });

  @DELETE('/api/v2/polls/{poll_id}/options/{option_id}')
  Future<Result<DurationResponse>> deletePollOption({
    @Path('poll_id') required String pollId,
    @Path('option_id') required String optionId,
    @Query('user_id') String? userId,
  });

  @DELETE('/api/v2/video/call/{type}/{id}/{session}/recordings/{filename}')
  Future<Result<DeleteRecordingResponse>> deleteRecording({
    @Path('type') required String type,
    @Path('id') required String id,
    @Path('session') required String session,
    @Path('filename') required String filename,
  });

  @DELETE('/api/v2/video/call/{type}/{id}/{session}/transcriptions/{filename}')
  Future<Result<DeleteTranscriptionResponse>> deleteTranscription({
    @Path('type') required String type,
    @Path('id') required String id,
    @Path('session') required String session,
    @Path('filename') required String filename,
  });

  @DELETE('/api/v2/usergroups/{id}')
  Future<Result<DurationResponse>> deleteUserGroup({
    @Path('id') required String id,
    @Query('team_id') String? teamId,
  });

  @POST('/api/v2/video/call/{type}/{id}/mark_ended')
  Future<Result<EndCallResponse>> endCall({
    @Path('type') required String type,
    @Path('id') required String id,
  });

  @POST('/api/v2/moderation/flag')
  Future<Result<FlagResponse>> flag({
    @Body() required FlagRequest flagRequest,
  });

  @GET('/api/v2/moderation/action_config')
  Future<Result<GetActionConfigResponse>> getActionConfig({
    @Query('queue_type') String? queueType,
    @Query('entity_type') String? entityType,
    @Query('exclude_defaults') bool? excludeDefaults,
    @Query('only_defaults') bool? onlyDefaults,
  });

  @GET('/api/v2/app')
  Future<Result<GetApplicationResponse>> getApp();

  @GET('/api/v2/moderation/appeal/{id}')
  Future<Result<GetAppealResponse>> getAppeal({
    @Path('id') required String id,
  });

  @GET('/api/v2/users/block')
  Future<Result<GetBlockedUsersResponse>> getBlockedUsers();

  @GET('/api/v2/video/call/{type}/{id}')
  Future<Result<GetCallResponse>> getCall({
    @Path('type') required String type,
    @Path('id') required String id,
    @Query('members_limit') int? membersLimit,
    @Query('ring') bool? ring,
    @Query('notify') bool? notify,
    @Query('video') bool? video,
  });

  @GET(
    '/api/v2/video/call/{type}/{id}/session/{session}/participant/{user}/{user_session}/details/track',
  )
  Future<Result<GetCallParticipantSessionMetricsResponse>>
  getCallParticipantSessionMetrics({
    @Path('type') required String type,
    @Path('id') required String id,
    @Path('session') required String session,
    @Path('user') required String user,
    @Path('user_session') required String userSession,
    @Query('since') DateTime? since,
    @Query('until') DateTime? until,
  });

  @GET('/api/v2/video/call/{type}/{id}/report')
  Future<Result<GetCallReportResponse>> getCallReport({
    @Path('type') required String type,
    @Path('id') required String id,
    @Query('session_id') String? sessionId,
  });

  @GET(
    '/api/v2/video/call_stats/{call_type}/{call_id}/{session}/participant/{user}/{user_session}/details',
  )
  Future<Result<GetCallSessionParticipantStatsDetailsResponse>>
  getCallSessionParticipantStatsDetails({
    @Path('call_type') required String callType,
    @Path('call_id') required String callId,
    @Path('session') required String session,
    @Path('user') required String user,
    @Path('user_session') required String userSession,
    @Query('since') String? since,
    @Query('until') String? until,
    @Query('max_points') int? maxPoints,
  });

  @GET(
    '/api/v2/video/call_stats/{call_type}/{call_id}/{session}/participants/{user}/{user_session}/timeline',
  )
  Future<Result<QueryCallSessionParticipantStatsTimelineResponse>>
  getCallSessionParticipantStatsTimeline({
    @Path('call_type') required String callType,
    @Path('call_id') required String callId,
    @Path('session') required String session,
    @Path('user') required String user,
    @Path('user_session') required String userSession,
    @Query('start_time') String? startTime,
    @Query('end_time') String? endTime,
    @Query('severity') List<String>? severity,
  });

  @GET('/api/v2/video/call_stats/{call_type}/{call_id}/{session}/map')
  Future<Result<QueryCallStatsMapResponse>> getCallStatsMap({
    @Path('call_type') required String callType,
    @Path('call_id') required String callId,
    @Path('session') required String session,
    @Query('start_time') DateTime? startTime,
    @Query('end_time') DateTime? endTime,
    @Query('exclude_publishers') bool? excludePublishers,
    @Query('exclude_subscribers') bool? excludeSubscribers,
    @Query('exclude_sfus') bool? excludeSfus,
  });

  @GET('/api/v2/moderation/config/{key}')
  Future<Result<GetConfigResponse>> getConfig({
    @Path('key') required String key,
    @Query('team') String? team,
  });

  @GET('/api/v2/video/edges')
  Future<Result<GetEdgesResponse>> getEdges();

  @GET('/api/v2/og')
  Future<Result<GetOGResponse>> getOG({
    @Query('url') required String url,
  });

  @POST('/api/v2/video/call/{type}/{id}')
  Future<Result<GetOrCreateCallResponse>> getOrCreateCall({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() GetOrCreateCallRequest? getOrCreateCallRequest,
  });

  @GET('/api/v2/polls/{poll_id}')
  Future<Result<PollResponse>> getPoll({
    @Path('poll_id') required String pollId,
    @Query('user_id') String? userId,
  });

  @GET('/api/v2/polls/{poll_id}/options/{option_id}')
  Future<Result<PollOptionResponse>> getPollOption({
    @Path('poll_id') required String pollId,
    @Path('option_id') required String optionId,
    @Query('user_id') String? userId,
  });

  @GET('/api/v2/usergroups/{id}')
  Future<Result<GetUserGroupResponse>> getUserGroup({
    @Path('id') required String id,
    @Query('team_id') String? teamId,
  });

  @GET('/api/v2/users/live_locations')
  Future<Result<SharedLocationsResponse>> getUserLiveLocations();

  @POST('/api/v2/video/call/{type}/{id}/go_live')
  Future<Result<GoLiveResponse>> goLive({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() GoLiveRequest? goLiveRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/join')
  Future<Result<JoinCallResponse>> joinCall({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required JoinCallRequest joinCallRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/kick')
  Future<Result<KickUserResponse>> kickUser({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required KickUserRequest kickUserRequest,
  });

  @GET('/api/v2/blocklists')
  Future<Result<ListBlockListResponse>> listBlockLists({
    @Query('team') String? team,
  });

  @GET('/api/v2/devices')
  Future<Result<ListDevicesResponse>> listDevices();

  @GET('/api/v2/video/call/{type}/{id}/recordings')
  Future<Result<ListRecordingsResponse>> listRecordings({
    @Path('type') required String type,
    @Path('id') required String id,
  });

  @GET('/api/v2/video/call/{type}/{id}/transcriptions')
  Future<Result<ListTranscriptionsResponse>> listTranscriptions({
    @Path('type') required String type,
    @Path('id') required String id,
  });

  @GET('/api/v2/usergroups')
  Future<Result<ListUserGroupsResponse>> listUserGroups({
    @Query('limit') int? limit,
    @Query('id_gt') String? idGt,
    @Query('created_at_gt') String? createdAtGt,
    @Query('team_id') String? teamId,
  });

  @GET('/api/v2/longpoll')
  Future<Result<void>> longPoll({
    @Query('json') WSAuthMessage? json,
  });

  @POST('/api/v2/moderation/mute')
  Future<Result<MuteResponse>> mute({
    @Body() required MuteRequest muteRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/mute_users')
  Future<Result<MuteUsersResponse>> muteUsers({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() MuteUsersRequest? muteUsersRequest,
  });

  @POST('/api/v2/video/stats')
  Future<Result<QueryAggregateCallStatsResponse>> queryAggregateCallStats({
    @Body() QueryAggregateCallStatsRequest? queryAggregateCallStatsRequest,
  });

  @POST('/api/v2/moderation/appeals')
  Future<Result<QueryAppealsResponse>> queryAppeals({
    @Body() QueryAppealsRequest? queryAppealsRequest,
  });

  @POST('/api/v2/video/call/members')
  Future<Result<QueryCallMembersResponse>> queryCallMembers({
    @Body() required QueryCallMembersRequest queryCallMembersRequest,
  });

  @GET('/api/v2/video/call/{type}/{id}/session/{session}/participant_sessions')
  Future<Result<QueryCallParticipantSessionsResponse>>
  queryCallParticipantSessions({
    @Path('type') required String type,
    @Path('id') required String id,
    @Path('session') required String session,
    @Query('limit') int? limit,
    @Query('prev') String? prev,
    @Query('next') String? next,
    @Query('filter_conditions') Map<String, Object?>? filterConditions,
  });

  @POST('/api/v2/video/call/{type}/{id}/participants')
  Future<Result<QueryCallParticipantsResponse>> queryCallParticipants({
    @Path('id') required String id,
    @Path('type') required String type,
    @Query('limit') int? limit,
    @Body() QueryCallParticipantsRequest? queryCallParticipantsRequest,
  });

  @GET('/api/v2/video/call_stats/{call_type}/{call_id}/{session}/participants')
  Future<Result<QueryCallSessionParticipantStatsResponse>>
  queryCallSessionParticipantStats({
    @Path('call_type') required String callType,
    @Path('call_id') required String callId,
    @Path('session') required String session,
    @Query('limit') int? limit,
    @Query('prev') String? prev,
    @Query('next') String? next,
    @Query('sort') List<SortParamRequest>? sort,
    @Query('filter_conditions') Map<String, Object?>? filterConditions,
  });

  @POST('/api/v2/video/call_stats')
  Future<Result<QueryCallSessionStatsResponse>> queryCallSessionStats({
    @Body() QueryCallSessionStatsRequest? queryCallSessionStatsRequest,
  });

  @POST('/api/v2/video/call/stats')
  Future<Result<QueryCallStatsResponse>> queryCallStats({
    @Body() QueryCallStatsRequest? queryCallStatsRequest,
  });

  @POST('/api/v2/video/calls')
  Future<Result<QueryCallsResponse>> queryCalls({
    @Body() QueryCallsRequest? queryCallsRequest,
  });

  @POST('/api/v2/moderation/configs')
  Future<Result<QueryModerationConfigsResponse>> queryModerationConfigs({
    @Body() QueryModerationConfigsRequest? queryModerationConfigsRequest,
  });

  @POST('/api/v2/polls/{poll_id}/votes')
  Future<Result<PollVotesResponse>> queryPollVotes({
    @Path('poll_id') required String pollId,
    @Query('user_id') String? userId,
    @Body() QueryPollVotesRequest? queryPollVotesRequest,
  });

  @POST('/api/v2/polls/query')
  Future<Result<QueryPollsResponse>> queryPolls({
    @Query('user_id') String? userId,
    @Body() QueryPollsRequest? queryPollsRequest,
  });

  @POST('/api/v2/moderation/review_queue')
  Future<Result<QueryReviewQueueResponse>> queryReviewQueue({
    @Body() QueryReviewQueueRequest? queryReviewQueueRequest,
  });

  @GET('/api/v2/users')
  Future<Result<QueryUsersResponse>> queryUsers({
    @Query('payload') QueryUsersPayload? payload,
  });

  @POST('/api/v2/video/call/{type}/{id}/reject')
  Future<Result<RejectCallResponse>> rejectCall({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() RejectCallRequest? rejectCallRequest,
  });

  @POST('/api/v2/usergroups/{id}/members/delete')
  Future<Result<RemoveUserGroupMembersResponse>> removeUserGroupMembers({
    @Path('id') required String id,
    @Body()
    required RemoveUserGroupMembersRequest removeUserGroupMembersRequest,
  });

  @POST('/api/v2/video/call_client_event')
  Future<Result<ReportClientEventResponse>> reportClientCallEvent({
    @Body() required ReportClientEventRequest reportClientEventRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/request_permission')
  Future<Result<RequestPermissionResponse>> requestPermission({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required RequestPermissionRequest requestPermissionRequest,
  });

  @POST('/api/v2/video/sip/auth')
  Future<Result<ResolveSipAuthResponse>> resolveSipAuth({
    @Body() required ResolveSipAuthRequest resolveSipAuthRequest,
  });

  @POST('/api/v2/video/sip/resolve')
  Future<Result<ResolveSipInboundResponse>> resolveSipInbound({
    @Body() required ResolveSipInboundRequest resolveSipInboundRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/ring')
  Future<Result<RingCallResponse>> ringCall({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() RingCallRequest? ringCallRequest,
  });

  @GET('/api/v2/roles/search')
  Future<Result<SearchRolesResponse>> searchRoles({
    @Query('query') required String query,
    @Query('limit') int? limit,
    @Query('name_gt') String? nameGt,
    @Query('role_type') String? roleType,
    @Query('include_global_roles') bool? includeGlobalRoles,
  });

  @GET('/api/v2/usergroups/search')
  Future<Result<SearchUserGroupsResponse>> searchUserGroups({
    @Query('query') required String query,
    @Query('limit') int? limit,
    @Query('name_gt') String? nameGt,
    @Query('id_gt') String? idGt,
    @Query('team_id') String? teamId,
  });

  @POST('/api/v2/video/call/{type}/{id}/event')
  Future<Result<SendCallEventResponse>> sendCallEvent({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() SendCallEventRequest? sendCallEventRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/reaction')
  Future<Result<SendVideoReactionResponse>> sendVideoReaction({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required SendVideoReactionRequest sendVideoReactionRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/start_closed_captions')
  Future<Result<StartClosedCaptionsResponse>> startClosedCaptions({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() StartClosedCaptionsRequest? startClosedCaptionsRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/start_frame_recording')
  Future<Result<StartFrameRecordingResponse>> startFrameRecording({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() StartFrameRecordingRequest? startFrameRecordingRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/start_broadcasting')
  Future<Result<StartHLSBroadcastingResponse>> startHLSBroadcasting({
    @Path('type') required String type,
    @Path('id') required String id,
  });

  @POST('/api/v2/video/call/{type}/{id}/rtmp_broadcasts')
  Future<Result<StartRTMPBroadcastsResponse>> startRTMPBroadcasts({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required StartRTMPBroadcastsRequest startRTMPBroadcastsRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/recordings/{recording_type}/start')
  Future<Result<StartRecordingResponse>> startRecording({
    @Path('type') required String type,
    @Path('id') required String id,
    @Path('recording_type') required String recordingType,
    @Body() StartRecordingRequest? startRecordingRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/start_transcription')
  Future<Result<StartTranscriptionResponse>> startTranscription({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() StartTranscriptionRequest? startTranscriptionRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/rtmp_broadcasts/stop')
  Future<Result<StopAllRTMPBroadcastsResponse>> stopAllRTMPBroadcasts({
    @Path('type') required String type,
    @Path('id') required String id,
  });

  @POST('/api/v2/video/call/{type}/{id}/stop_closed_captions')
  Future<Result<StopClosedCaptionsResponse>> stopClosedCaptions({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() StopClosedCaptionsRequest? stopClosedCaptionsRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/stop_frame_recording')
  Future<Result<StopFrameRecordingResponse>> stopFrameRecording({
    @Path('type') required String type,
    @Path('id') required String id,
  });

  @POST('/api/v2/video/call/{type}/{id}/stop_broadcasting')
  Future<Result<StopHLSBroadcastingResponse>> stopHLSBroadcasting({
    @Path('type') required String type,
    @Path('id') required String id,
  });

  @POST('/api/v2/video/call/{type}/{id}/stop_live')
  Future<Result<StopLiveResponse>> stopLive({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() StopLiveRequest? stopLiveRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/rtmp_broadcasts/{name}/stop')
  Future<Result<StopRTMPBroadcastsResponse>> stopRTMPBroadcast({
    @Path('type') required String type,
    @Path('id') required String id,
    @Path('name') required String name,
  });

  @POST('/api/v2/video/call/{type}/{id}/recordings/{recording_type}/stop')
  Future<Result<StopRecordingResponse>> stopRecording({
    @Path('type') required String type,
    @Path('id') required String id,
    @Path('recording_type') required String recordingType,
  });

  @POST('/api/v2/video/call/{type}/{id}/stop_transcription')
  Future<Result<StopTranscriptionResponse>> stopTranscription({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() StopTranscriptionRequest? stopTranscriptionRequest,
  });

  @POST('/api/v2/moderation/submit_action')
  Future<Result<SubmitActionResponse>> submitAction({
    @Body() required SubmitActionRequest submitActionRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/unblock')
  Future<Result<UnblockUserResponse>> unblockUser({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required UnblockUserRequest unblockUserRequest,
  });

  @POST('/api/v2/users/unblock')
  Future<Result<UnblockUsersResponse>> unblockUsers({
    @Body() required UnblockUsersRequest unblockUsersRequest,
  });

  @PUT('/api/v2/blocklists/{name}')
  Future<Result<UpdateBlockListResponse>> updateBlockList({
    @Path('name') required String name,
    @Body() UpdateBlockListRequest? updateBlockListRequest,
  });

  @PATCH('/api/v2/video/call/{type}/{id}')
  Future<Result<UpdateCallResponse>> updateCall({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() UpdateCallRequest? updateCallRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/members')
  Future<Result<UpdateCallMembersResponse>> updateCallMembers({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() UpdateCallMembersRequest? updateCallMembersRequest,
  });

  @PUT('/api/v2/users/live_locations')
  Future<Result<SharedLocationResponse>> updateLiveLocation({
    @Body() required UpdateLiveLocationRequest updateLiveLocationRequest,
  });

  @PUT('/api/v2/polls')
  Future<Result<PollResponse>> updatePoll({
    @Body() required UpdatePollRequest updatePollRequest,
  });

  @PUT('/api/v2/polls/{poll_id}/options')
  Future<Result<PollOptionResponse>> updatePollOption({
    @Path('poll_id') required String pollId,
    @Body() required UpdatePollOptionRequest updatePollOptionRequest,
  });

  @PATCH('/api/v2/polls/{poll_id}')
  Future<Result<PollResponse>> updatePollPartial({
    @Path('poll_id') required String pollId,
    @Body() UpdatePollPartialRequest? updatePollPartialRequest,
  });

  @POST('/api/v2/push_preferences')
  Future<Result<UpsertPushPreferencesResponse>>
  updatePushNotificationPreferences({
    @Body() required UpsertPushPreferencesRequest upsertPushPreferencesRequest,
  });

  @PUT('/api/v2/usergroups/{id}')
  Future<Result<UpdateUserGroupResponse>> updateUserGroup({
    @Path('id') required String id,
    @Body() UpdateUserGroupRequest? updateUserGroupRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/user_permissions')
  Future<Result<UpdateUserPermissionsResponse>> updateUserPermissions({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required UpdateUserPermissionsRequest updateUserPermissionsRequest,
  });

  @POST('/api/v2/users')
  Future<Result<UpdateUsersResponse>> updateUsers({
    @Body() required UpdateUsersRequest updateUsersRequest,
  });

  @PATCH('/api/v2/users')
  Future<Result<UpdateUsersResponse>> updateUsersPartial({
    @Body() required UpdateUsersPartialRequest updateUsersPartialRequest,
  });

  @POST('/api/v2/uploads/file')
  Future<Result<FileUploadResponse>> uploadFile({
    @Body() FileUploadRequest? fileUploadRequest,
  });

  @POST('/api/v2/uploads/image')
  Future<Result<ImageUploadResponse>> uploadImage({
    @Body() ImageUploadRequest? imageUploadRequest,
  });

  @POST('/api/v2/moderation/action_config')
  Future<Result<UpsertActionConfigResponse>> upsertActionConfig({
    @Body() required UpsertActionConfigRequest upsertActionConfigRequest,
  });

  @POST('/api/v2/moderation/config')
  Future<Result<UpsertConfigResponse>> upsertConfig({
    @Body() required UpsertConfigRequest upsertConfigRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/pin')
  Future<Result<PinResponse>> videoPin({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required PinRequest pinRequest,
  });

  @POST('/api/v2/video/call/{type}/{id}/unpin')
  Future<Result<UnpinResponse>> videoUnpin({
    @Path('type') required String type,
    @Path('id') required String id,
    @Body() required UnpinRequest unpinRequest,
  });
}

class _ResultCallAdapter<T> extends CallAdapter<Future<T>, Future<Result<T>>> {
  @override
  Future<Result<T>> adapt(Future<T> Function() call) => runSafely(call);
}
