// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'accept_call_response.g.dart';
part 'accept_call_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class AcceptCallResponse with _$AcceptCallResponse {
  const AcceptCallResponse({
    required this.duration,
  });

  @override
  final String duration;

  Map<String, dynamic> toJson() => _$AcceptCallResponseToJson(this);

  static AcceptCallResponse fromJson(Map<String, dynamic> json) =>
      _$AcceptCallResponseFromJson(json);
}
