// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class AppEventResponse {
  const AppEventResponse({
    this.asyncUrlEnrichEnabled,
    required this.autoTranslationEnabled,
    this.fileUploadConfig,
    this.imageUploadConfig,
    required this.name,
  });

  final bool? asyncUrlEnrichEnabled;

  final bool autoTranslationEnabled;

  final FileUploadConfig? fileUploadConfig;

  final FileUploadConfig? imageUploadConfig;

  final String name;

  Map<String, dynamic> toJson() {
    return {
      'async_url_enrich_enabled': asyncUrlEnrichEnabled,
      'auto_translation_enabled': autoTranslationEnabled,
      'file_upload_config': fileUploadConfig,
      'image_upload_config': imageUploadConfig,
      'name': name,
    };
  }

  static AppEventResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return AppEventResponse(
        asyncUrlEnrichEnabled:
            mapValueOfType<bool>(json, r'async_url_enrich_enabled', null),
        autoTranslationEnabled:
            mapValueOfType<bool>(json, r'auto_translation_enabled')!,
        fileUploadConfig:
            FileUploadConfig.fromJson(json[r'file_upload_config'] ?? null),
        imageUploadConfig:
            FileUploadConfig.fromJson(json[r'image_upload_config'] ?? null),
        name: mapValueOfType<String>(json, r'name')!,
      );
    }
    return null;
  }

  static List<AppEventResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <AppEventResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = AppEventResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'AppEventResponse('
        'asyncUrlEnrichEnabled: $asyncUrlEnrichEnabled, '
        'autoTranslationEnabled: $autoTranslationEnabled, '
        'fileUploadConfig: $fileUploadConfig, '
        'imageUploadConfig: $imageUploadConfig, '
        'name: $name, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is AppEventResponse &&
        other.asyncUrlEnrichEnabled == asyncUrlEnrichEnabled &&
        other.autoTranslationEnabled == autoTranslationEnabled &&
        other.fileUploadConfig == fileUploadConfig &&
        other.imageUploadConfig == imageUploadConfig &&
        other.name == name;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      asyncUrlEnrichEnabled,
      autoTranslationEnabled,
      fileUploadConfig,
      imageUploadConfig,
      name,
    ]);
  }
}
