// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

enum AudioSettingsRequestDefaultDeviceEnum {
  earpiece('earpiece'),
  speaker('speaker'),
  unknown('_unknown');

  const AudioSettingsRequestDefaultDeviceEnum(this.value);
  final String value;

  static AudioSettingsRequestDefaultDeviceEnum? fromValue(String? json) {
    switch (json) {
      case null:
        return null;
      case 'earpiece':
        return AudioSettingsRequestDefaultDeviceEnum.earpiece;
      case 'speaker':
        return AudioSettingsRequestDefaultDeviceEnum.speaker;
      default:
        return AudioSettingsRequestDefaultDeviceEnum.unknown;
    }
  }
}

@immutable
class AudioSettingsRequest {
  const AudioSettingsRequest({
    this.accessRequestEnabled,
    required this.defaultDevice,
    this.micDefaultOn,
    this.noiseCancellation,
    this.opusDtxEnabled,
    this.redundantCodingEnabled,
    this.speakerDefaultOn,
  });

  final bool? accessRequestEnabled;

  final AudioSettingsRequestDefaultDeviceEnum defaultDevice;

  final bool? micDefaultOn;

  final NoiseCancellationSettings? noiseCancellation;

  final bool? opusDtxEnabled;

  final bool? redundantCodingEnabled;

  final bool? speakerDefaultOn;

  Map<String, dynamic> toJson() {
    return {
      'access_request_enabled': accessRequestEnabled,
      'default_device': defaultDevice,
      'mic_default_on': micDefaultOn,
      'noise_cancellation': noiseCancellation,
      'opus_dtx_enabled': opusDtxEnabled,
      'redundant_coding_enabled': redundantCodingEnabled,
      'speaker_default_on': speakerDefaultOn,
    };
  }

  static AudioSettingsRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return AudioSettingsRequest(
        accessRequestEnabled:
            mapValueOfType<bool>(json, r'access_request_enabled', null),
        defaultDevice: AudioSettingsRequestDefaultDeviceEnum.fromValue(
            json['default_device'])!,
        micDefaultOn: mapValueOfType<bool>(json, r'mic_default_on', null),
        noiseCancellation: NoiseCancellationSettings.fromJson(
            json[r'noise_cancellation'] ?? null),
        opusDtxEnabled: mapValueOfType<bool>(json, r'opus_dtx_enabled', null),
        redundantCodingEnabled:
            mapValueOfType<bool>(json, r'redundant_coding_enabled', null),
        speakerDefaultOn:
            mapValueOfType<bool>(json, r'speaker_default_on', null),
      );
    }
    return null;
  }

  static List<AudioSettingsRequest> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <AudioSettingsRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = AudioSettingsRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'AudioSettingsRequest('
        'accessRequestEnabled: $accessRequestEnabled, '
        'defaultDevice: $defaultDevice, '
        'micDefaultOn: $micDefaultOn, '
        'noiseCancellation: $noiseCancellation, '
        'opusDtxEnabled: $opusDtxEnabled, '
        'redundantCodingEnabled: $redundantCodingEnabled, '
        'speakerDefaultOn: $speakerDefaultOn, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is AudioSettingsRequest &&
        other.accessRequestEnabled == accessRequestEnabled &&
        other.defaultDevice == defaultDevice &&
        other.micDefaultOn == micDefaultOn &&
        other.noiseCancellation == noiseCancellation &&
        other.opusDtxEnabled == opusDtxEnabled &&
        other.redundantCodingEnabled == redundantCodingEnabled &&
        other.speakerDefaultOn == speakerDefaultOn;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      accessRequestEnabled,
      defaultDevice,
      micDefaultOn,
      noiseCancellation,
      opusDtxEnabled,
      redundantCodingEnabled,
      speakerDefaultOn,
    ]);
  }
}
