// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'automod_semantic_filters_rule.g.dart';
part 'automod_semantic_filters_rule.freezed.dart';

@JsonEnum(alwaysCreate: true)
enum AutomodSemanticFiltersRuleAction {
  @JsonValue('bounce')
  bounce,
  @JsonValue('bounce_flag')
  bounceFlag,
  @JsonValue('bounce_remove')
  bounceRemove,
  @JsonValue('flag')
  flag,
  @JsonValue('remove')
  remove,
  @JsonValue('shadow')
  shadow,
  @JsonValue('_unknown')
  unknown,
}

@freezed
@immutable
@JsonSerializable()
class AutomodSemanticFiltersRule with _$AutomodSemanticFiltersRule {
  const AutomodSemanticFiltersRule({
    required this.action,
    required this.name,
    required this.threshold,
  });

  @override
  @JsonKey(unknownEnumValue: AutomodSemanticFiltersRuleAction.unknown)
  final AutomodSemanticFiltersRuleAction action;

  @override
  final String name;

  @override
  final double threshold;

  Map<String, dynamic> toJson() => _$AutomodSemanticFiltersRuleToJson(this);

  static AutomodSemanticFiltersRule fromJson(Map<String, dynamic> json) =>
      _$AutomodSemanticFiltersRuleFromJson(json);
}
