// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'aws_rekognition_rule.g.dart';
part 'aws_rekognition_rule.freezed.dart';

@JsonEnum(alwaysCreate: true)
enum AWSRekognitionRuleAction {
  @JsonValue('bounce')
  bounce,
  @JsonValue('bounce_flag')
  bounceFlag,
  @JsonValue('bounce_remove')
  bounceRemove,
  @JsonValue('flag')
  flag,
  @JsonValue('remove')
  remove,
  @JsonValue('shadow')
  shadow,
  @JsonValue('_unknown')
  unknown,
}

@freezed
@immutable
@JsonSerializable()
class AWSRekognitionRule with _$AWSRekognitionRule {
  const AWSRekognitionRule({
    required this.action,
    required this.label,
    required this.minConfidence,
    this.subclassifications,
  });

  @override
  @JsonKey(unknownEnumValue: AWSRekognitionRuleAction.unknown)
  final AWSRekognitionRuleAction action;

  @override
  final String label;

  @override
  final double minConfidence;

  @override
  final Map<String, Object?>? subclassifications;

  Map<String, dynamic> toJson() => _$AWSRekognitionRuleToJson(this);

  static AWSRekognitionRule fromJson(Map<String, dynamic> json) =>
      _$AWSRekognitionRuleFromJson(json);
}
