// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class BackstageSettingsRequest {
  const BackstageSettingsRequest({
    this.enabled,
    this.joinAheadTimeSeconds,
  });

  final bool? enabled;

  final int? joinAheadTimeSeconds;

  Map<String, dynamic> toJson() {
    return {
      'enabled': enabled,
      'join_ahead_time_seconds': joinAheadTimeSeconds,
    };
  }

  static BackstageSettingsRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return BackstageSettingsRequest(
        enabled: mapValueOfType<bool>(json, r'enabled', null),
        joinAheadTimeSeconds:
            mapValueOfType<int>(json, r'join_ahead_time_seconds', null),
      );
    }
    return null;
  }

  static List<BackstageSettingsRequest> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <BackstageSettingsRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = BackstageSettingsRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'BackstageSettingsRequest('
        'enabled: $enabled, '
        'joinAheadTimeSeconds: $joinAheadTimeSeconds, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is BackstageSettingsRequest &&
        other.enabled == enabled &&
        other.joinAheadTimeSeconds == joinAheadTimeSeconds;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      enabled,
      joinAheadTimeSeconds,
    ]);
  }
}
