// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'bodyguard_severity_rule.g.dart';
part 'bodyguard_severity_rule.freezed.dart';

@JsonEnum(alwaysCreate: true)
enum BodyguardSeverityRuleAction {
  @JsonValue('bounce')
  bounce,
  @JsonValue('bounce_flag')
  bounceFlag,
  @JsonValue('bounce_remove')
  bounceRemove,
  @JsonValue('flag')
  flag,
  @JsonValue('keep')
  keep,
  @JsonValue('mask')
  mask,
  @JsonValue('remove')
  remove,
  @JsonValue('shadow')
  shadow,
  @JsonValue('_unknown')
  unknown,
}

@JsonEnum(alwaysCreate: true)
enum BodyguardSeverityRuleSeverity {
  @JsonValue('critical')
  critical,
  @JsonValue('high')
  high,
  @JsonValue('low')
  low,
  @JsonValue('medium')
  medium,
  @JsonValue('_unknown')
  unknown,
}

@freezed
@immutable
@JsonSerializable()
class BodyguardSeverityRule with _$BodyguardSeverityRule {
  const BodyguardSeverityRule({
    required this.action,
    required this.severity,
  });

  @override
  @JsonKey(unknownEnumValue: BodyguardSeverityRuleAction.unknown)
  final BodyguardSeverityRuleAction action;

  @override
  @JsonKey(unknownEnumValue: BodyguardSeverityRuleSeverity.unknown)
  final BodyguardSeverityRuleSeverity severity;

  Map<String, dynamic> toJson() => _$BodyguardSeverityRuleToJson(this);

  static BodyguardSeverityRule fromJson(Map<String, dynamic> json) =>
      _$BodyguardSeverityRuleFromJson(json);
}
