// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'bodyguard_rule.g.dart';
part 'bodyguard_rule.freezed.dart';

@JsonEnum(alwaysCreate: true)
enum BodyguardRuleAction {
  @JsonValue('bounce')
  bounce,
  @JsonValue('bounce_flag')
  bounceFlag,
  @JsonValue('bounce_remove')
  bounceRemove,
  @JsonValue('flag')
  flag,
  @JsonValue('keep')
  keep,
  @JsonValue('mask')
  mask,
  @JsonValue('mask_flag')
  maskFlag,
  @JsonValue('remove')
  remove,
  @JsonValue('shadow')
  shadow,
  @JsonValue('_unknown')
  unknown,
}

@freezed
@immutable
@JsonSerializable()
class BodyguardRule with _$BodyguardRule {
  const BodyguardRule({
    required this.action,
    required this.label,
    required this.severityRules,
  });

  @override
  @JsonKey(unknownEnumValue: BodyguardRuleAction.unknown)
  final BodyguardRuleAction action;

  @override
  final String label;

  @override
  @JsonKey(defaultValue: [])
  final List<BodyguardSeverityRule> severityRules;

  Map<String, dynamic> toJson() => _$BodyguardRuleToJson(this);

  static BodyguardRule fromJson(Map<String, dynamic> json) =>
      _$BodyguardRuleFromJson(json);
}
