// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'broadcast_settings_response.g.dart';
part 'broadcast_settings_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class BroadcastSettingsResponse with _$BroadcastSettingsResponse {
  const BroadcastSettingsResponse({
    required this.enabled,
    required this.hls,
    required this.rtmp,
  });

  @override
  final bool enabled;

  @override
  final HLSSettingsResponse hls;

  @override
  final RTMPSettingsResponse rtmp;

  Map<String, dynamic> toJson() => _$BroadcastSettingsResponseToJson(this);

  static BroadcastSettingsResponse fromJson(Map<String, dynamic> json) =>
      _$BroadcastSettingsResponseFromJson(json);
}
