// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'broadcast_digest.g.dart';
part 'broadcast_digest.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class BroadcastDigest with _$BroadcastDigest {
  const BroadcastDigest({
    required this.audience,
    required this.broadcast,
    required this.coverage,
    required this.joins,
    required this.poorTail,
    required this.quality,
    required this.schemaVersion,
    required this.segments,
    required this.source,
    required this.viewers,
  });

  @override
  @JsonKey(name: 'audience')
  final Audience audience;

  @override
  @JsonKey(name: 'broadcast')
  final BroadcastInfo broadcast;

  @override
  @JsonKey(name: 'coverage')
  final Coverage coverage;

  @override
  @JsonKey(name: 'joins')
  final Joins joins;

  @override
  @JsonKey(name: 'poor_tail')
  final PoorTail poorTail;

  @override
  @JsonKey(name: 'quality')
  final Quality quality;

  @override
  @JsonKey(name: 'schema_version')
  final String schemaVersion;

  @override
  @JsonKey(name: 'segments')
  final Segments segments;

  @override
  @JsonKey(name: 'source')
  final SourceHealth source;

  @override
  @JsonKey(name: 'viewers')
  final ViewerBehavior viewers;

  Map<String, dynamic> toJson() => _$BroadcastDigestToJson(this);

  static BroadcastDigest fromJson(Map<String, dynamic> json) =>
      _$BroadcastDigestFromJson(json);
}
