// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallParticipantCountReport {
  const CallParticipantCountReport({
    required this.histogram,
  });

  final List<ReportByHistogramBucket> histogram;

  Map<String, dynamic> toJson() {
    return {
      'histogram': histogram,
    };
  }

  static CallParticipantCountReport? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallParticipantCountReport(
        histogram: ReportByHistogramBucket.listFromJson(json[r'histogram'])!,
      );
    }
    return null;
  }

  static List<CallParticipantCountReport> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallParticipantCountReport>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallParticipantCountReport.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallParticipantCountReport('
        'histogram: $histogram, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallParticipantCountReport && other.histogram == histogram;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      histogram,
    ]);
  }
}
