// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_transcription_started_event.g.dart';
part 'call_transcription_started_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallTranscriptionStartedEvent extends core.WsEvent
    with _$CallTranscriptionStartedEvent {
  const CallTranscriptionStartedEvent({
    required this.callCid,
    required this.createdAt,
    required this.egressId,
    required this.type,
  });

  @override
  final String callCid;

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  final String egressId;

  @override
  final String type;

  Map<String, dynamic> toJson() => _$CallTranscriptionStartedEventToJson(this);

  static CallTranscriptionStartedEvent fromJson(Map<String, dynamic> json) =>
      _$CallTranscriptionStartedEventFromJson(json);
}
