// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_missed_event.g.dart';
part 'call_missed_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallMissedEvent extends core.WsEvent with _$CallMissedEvent {
  const CallMissedEvent({
    required this.call,
    required this.callCid,
    required this.createdAt,
    required this.members,
    required this.notifyUser,
    required this.sessionId,
    required this.type,
    required this.user,
  });

  @override
  @JsonKey(name: 'call')
  final CallResponse call;

  @override
  @JsonKey(name: 'call_cid')
  final String callCid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'members')
  final List<MemberResponse> members;

  @override
  @JsonKey(name: 'notify_user')
  final bool notifyUser;

  @override
  @JsonKey(name: 'session_id')
  final String sessionId;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @JsonKey(name: 'user')
  final UserResponse user;

  Map<String, dynamic> toJson() => _$CallMissedEventToJson(this);

  static CallMissedEvent fromJson(Map<String, dynamic> json) =>
      _$CallMissedEventFromJson(json);
}
