// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallStatsReportReadyEvent {
  const CallStatsReportReadyEvent({
    required this.callCid,
    required this.createdAt,
    required this.sessionId,
    required this.type,
  });

  final String callCid;

  final DateTime createdAt;

  final String sessionId;

  final String type;

  Map<String, dynamic> toJson() {
    return {
      'call_cid': callCid,
      'created_at': createdAt,
      'session_id': sessionId,
      'type': type,
    };
  }

  static CallStatsReportReadyEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallStatsReportReadyEvent(
        callCid: mapValueOfType<String>(json, r'call_cid')!,
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        sessionId: mapValueOfType<String>(json, r'session_id')!,
        type: mapValueOfType<String>(json, r'type', "call.stats_report_ready")!,
      );
    }
    return null;
  }

  static List<CallStatsReportReadyEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallStatsReportReadyEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallStatsReportReadyEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallStatsReportReadyEvent('
        'callCid: $callCid, '
        'createdAt: $createdAt, '
        'sessionId: $sessionId, '
        'type: $type, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallStatsReportReadyEvent &&
        other.callCid == callCid &&
        other.createdAt == createdAt &&
        other.sessionId == sessionId &&
        other.type == type;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      callCid,
      createdAt,
      sessionId,
      type,
    ]);
  }
}
