// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallMemberUpdatedPermissionEvent {
  const CallMemberUpdatedPermissionEvent({
    required this.call,
    required this.callCid,
    required this.capabilitiesByRole,
    required this.createdAt,
    required this.members,
    required this.type,
  });

  final CallResponse call;

  final String callCid;

  final Map<String, List<String>> capabilitiesByRole;

  final DateTime createdAt;

  final List<MemberResponse> members;

  final String type;

  Map<String, dynamic> toJson() {
    return {
      'call': call,
      'call_cid': callCid,
      'capabilities_by_role': capabilitiesByRole,
      'created_at': createdAt,
      'members': members,
      'type': type,
    };
  }

  static CallMemberUpdatedPermissionEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallMemberUpdatedPermissionEvent(
        call: CallResponse.fromJson(json[r'call'])!,
        callCid: mapValueOfType<String>(json, r'call_cid')!,
        capabilitiesByRole:
            mapCastOfType<String, List<String>>(json, r'capabilities_by_role')!,
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        members: MemberResponse.listFromJson(json[r'members'])!,
        type: mapValueOfType<String>(
            json, r'type', "call.member_updated_permission")!,
      );
    }
    return null;
  }

  static List<CallMemberUpdatedPermissionEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallMemberUpdatedPermissionEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallMemberUpdatedPermissionEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallMemberUpdatedPermissionEvent('
        'call: $call, '
        'callCid: $callCid, '
        'capabilitiesByRole: $capabilitiesByRole, '
        'createdAt: $createdAt, '
        'members: $members, '
        'type: $type, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallMemberUpdatedPermissionEvent &&
        other.call == call &&
        other.callCid == callCid &&
        other.capabilitiesByRole == capabilitiesByRole &&
        other.createdAt == createdAt &&
        other.members == members &&
        other.type == type;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      call,
      callCid,
      capabilitiesByRole,
      createdAt,
      members,
      type,
    ]);
  }
}
