// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_closed_caption.g.dart';
part 'call_closed_caption.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallClosedCaption with _$CallClosedCaption {
  const CallClosedCaption({
    required this.endTime,
    required this.id,
    required this.language,
    this.service,
    required this.speakerId,
    required this.startTime,
    required this.text,
    required this.translated,
    required this.user,
  });

  @override
  @EpochDateTimeConverter()
  final DateTime endTime;

  @override
  final String id;

  @override
  final String language;

  @override
  final String? service;

  @override
  final String speakerId;

  @override
  @EpochDateTimeConverter()
  final DateTime startTime;

  @override
  final String text;

  @override
  final bool translated;

  @override
  final UserResponse user;

  Map<String, dynamic> toJson() => _$CallClosedCaptionToJson(this);

  static CallClosedCaption fromJson(Map<String, dynamic> json) =>
      _$CallClosedCaptionFromJson(json);
}
