// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_level_event_payload.g.dart';
part 'call_level_event_payload.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallLevelEventPayload with _$CallLevelEventPayload {
  const CallLevelEventPayload({
    required this.eventType,
    this.payload,
    required this.timestamp,
    required this.userId,
  });

  @override
  final String eventType;

  @override
  final Map<String, Object?>? payload;

  @override
  final int timestamp;

  @override
  final String userId;

  Map<String, dynamic> toJson() => _$CallLevelEventPayloadToJson(this);

  static CallLevelEventPayload fromJson(Map<String, dynamic> json) =>
      _$CallLevelEventPayloadFromJson(json);
}
