// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_stats_map_subscriber.g.dart';
part 'call_stats_map_subscriber.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallStatsMapSubscriber with _$CallStatsMapSubscriber {
  const CallStatsMapSubscriber({
    required this.isLive,
    this.location,
    this.name,
    required this.userId,
    required this.userSessionId,
  });

  @override
  @JsonKey(name: 'is_live')
  final bool isLive;

  @override
  @JsonKey(name: 'location')
  final CallStatsLocation? location;

  @override
  @JsonKey(name: 'name')
  final String? name;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  @override
  @JsonKey(name: 'user_session_id')
  final String userSessionId;

  Map<String, dynamic> toJson() => _$CallStatsMapSubscriberToJson(this);

  static CallStatsMapSubscriber fromJson(Map<String, dynamic> json) =>
      _$CallStatsMapSubscriberFromJson(json);
}
