// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_recording.g.dart';
part 'call_recording.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallRecording with _$CallRecording {
  const CallRecording({
    required this.endTime,
    required this.filename,
    required this.recordingType,
    required this.sessionId,
    required this.startTime,
    required this.url,
  });

  @override
  @EpochDateTimeConverter()
  final DateTime endTime;

  @override
  final String filename;

  @override
  final String recordingType;

  @override
  final String sessionId;

  @override
  @EpochDateTimeConverter()
  final DateTime startTime;

  @override
  final String url;

  Map<String, dynamic> toJson() => _$CallRecordingToJson(this);

  static CallRecording fromJson(Map<String, dynamic> json) =>
      _$CallRecordingFromJson(json);
}
