// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_stats_report_summary_response.g.dart';
part 'call_stats_report_summary_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallStatsReportSummaryResponse with _$CallStatsReportSummaryResponse {
  const CallStatsReportSummaryResponse({
    required this.callCid,
    required this.callDurationSeconds,
    required this.callSessionId,
    required this.callStatus,
    this.createdAt,
    required this.firstStatsTime,
    this.minUserRating,
    this.qualityScore,
  });

  @override
  final String callCid;

  @override
  final int callDurationSeconds;

  @override
  final String callSessionId;

  @override
  final String callStatus;

  @override
  @EpochDateTimeConverter()
  final DateTime? createdAt;

  @override
  @EpochDateTimeConverter()
  final DateTime firstStatsTime;

  @override
  final int? minUserRating;

  @override
  final int? qualityScore;

  Map<String, dynamic> toJson() => _$CallStatsReportSummaryResponseToJson(this);

  static CallStatsReportSummaryResponse fromJson(Map<String, dynamic> json) =>
      _$CallStatsReportSummaryResponseFromJson(json);
}
