// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallSessionParticipantLeftEvent {
  const CallSessionParticipantLeftEvent({
    required this.callCid,
    required this.createdAt,
    required this.durationSeconds,
    required this.participant,
    required this.sessionId,
    required this.type,
  });

  final String callCid;

  final DateTime createdAt;

  final int durationSeconds;

  final CallParticipantResponse participant;

  final String sessionId;

  final String type;

  Map<String, dynamic> toJson() {
    return {
      'call_cid': callCid,
      'created_at': createdAt,
      'duration_seconds': durationSeconds,
      'participant': participant,
      'session_id': sessionId,
      'type': type,
    };
  }

  static CallSessionParticipantLeftEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallSessionParticipantLeftEvent(
        callCid: mapValueOfType<String>(json, r'call_cid')!,
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        durationSeconds: mapValueOfType<int>(json, r'duration_seconds')!,
        participant: CallParticipantResponse.fromJson(json[r'participant'])!,
        sessionId: mapValueOfType<String>(json, r'session_id')!,
        type: mapValueOfType<String>(
            json, r'type', "call.session_participant_left")!,
      );
    }
    return null;
  }

  static List<CallSessionParticipantLeftEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallSessionParticipantLeftEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallSessionParticipantLeftEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallSessionParticipantLeftEvent('
        'callCid: $callCid, '
        'createdAt: $createdAt, '
        'durationSeconds: $durationSeconds, '
        'participant: $participant, '
        'sessionId: $sessionId, '
        'type: $type, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallSessionParticipantLeftEvent &&
        other.callCid == callCid &&
        other.createdAt == createdAt &&
        other.durationSeconds == durationSeconds &&
        other.participant == participant &&
        other.sessionId == sessionId &&
        other.type == type;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      callCid,
      createdAt,
      durationSeconds,
      participant,
      sessionId,
      type,
    ]);
  }
}
