// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallRejectedEvent {
  const CallRejectedEvent({
    required this.call,
    required this.callCid,
    required this.createdAt,
    this.reason,
    required this.type,
    required this.user,
  });

  final CallResponse call;

  final String callCid;

  final DateTime createdAt;

  final String? reason;

  final String type;

  final UserResponse user;

  Map<String, dynamic> toJson() {
    return {
      'call': call,
      'call_cid': callCid,
      'created_at': createdAt,
      'reason': reason,
      'type': type,
      'user': user,
    };
  }

  static CallRejectedEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallRejectedEvent(
        call: CallResponse.fromJson(json[r'call'])!,
        callCid: mapValueOfType<String>(json, r'call_cid')!,
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        reason: mapValueOfType<String>(json, r'reason', null),
        type: mapValueOfType<String>(json, r'type', "call.rejected")!,
        user: UserResponse.fromJson(json[r'user'])!,
      );
    }
    return null;
  }

  static List<CallRejectedEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallRejectedEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallRejectedEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallRejectedEvent('
        'call: $call, '
        'callCid: $callCid, '
        'createdAt: $createdAt, '
        'reason: $reason, '
        'type: $type, '
        'user: $user, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallRejectedEvent &&
        other.call == call &&
        other.callCid == callCid &&
        other.createdAt == createdAt &&
        other.reason == reason &&
        other.type == type &&
        other.user == user;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      call,
      callCid,
      createdAt,
      reason,
      type,
      user,
    ]);
  }
}
