// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_participant_timeline.g.dart';
part 'call_participant_timeline.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallParticipantTimeline with _$CallParticipantTimeline {
  const CallParticipantTimeline({
    required this.data,
    required this.severity,
    required this.timestamp,
    required this.type,
  });

  @override
  final Map<String, Object?> data;

  @override
  final String severity;

  @override
  @EpochDateTimeConverter()
  final DateTime timestamp;

  @override
  final String type;

  Map<String, dynamic> toJson() => _$CallParticipantTimelineToJson(this);

  static CallParticipantTimeline fromJson(Map<String, dynamic> json) =>
      _$CallParticipantTimelineFromJson(json);
}
