// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_stats_participant_session.g.dart';
part 'call_stats_participant_session.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallStatsParticipantSession with _$CallStatsParticipantSession {
  const CallStatsParticipantSession({
    this.browser,
    this.browserVersion,
    this.cqScore,
    this.currentIp,
    this.currentSfu,
    this.distanceToSfuKilometers,
    this.endedAt,
    this.freezesDurationMs,
    this.ingress,
    required this.isLive,
    this.jitterMs,
    this.latencyMs,
    this.location,
    this.os,
    required this.publishedTracks,
    this.publisherType,
    this.sdk,
    this.sdkVersion,
    this.startedAt,
    this.unifiedSessionId,
    required this.userSessionId,
    this.webrtcVersion,
  });

  @override
  final String? browser;

  @override
  final String? browserVersion;

  @override
  final int? cqScore;

  @override
  final String? currentIp;

  @override
  final String? currentSfu;

  @override
  final double? distanceToSfuKilometers;

  @override
  @EpochDateTimeConverter()
  final DateTime? endedAt;

  @override
  final int? freezesDurationMs;

  @override
  final String? ingress;

  @override
  final bool isLive;

  @override
  final int? jitterMs;

  @override
  final int? latencyMs;

  @override
  final CallStatsLocation? location;

  @override
  final String? os;

  @override
  final PublishedTrackFlags publishedTracks;

  @override
  final String? publisherType;

  @override
  final String? sdk;

  @override
  final String? sdkVersion;

  @override
  @EpochDateTimeConverter()
  final DateTime? startedAt;

  @override
  final String? unifiedSessionId;

  @override
  final String userSessionId;

  @override
  final String? webrtcVersion;

  Map<String, dynamic> toJson() => _$CallStatsParticipantSessionToJson(this);

  static CallStatsParticipantSession fromJson(Map<String, dynamic> json) =>
      _$CallStatsParticipantSessionFromJson(json);
}
