// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallNotificationEvent {
  const CallNotificationEvent({
    required this.call,
    required this.callCid,
    required this.createdAt,
    required this.members,
    required this.sessionId,
    required this.type,
    required this.user,
  });

  final CallResponse call;

  final String callCid;

  final DateTime createdAt;

  final List<MemberResponse> members;

  final String sessionId;

  final String type;

  final UserResponse user;

  Map<String, dynamic> toJson() {
    return {
      'call': call,
      'call_cid': callCid,
      'created_at': createdAt,
      'members': members,
      'session_id': sessionId,
      'type': type,
      'user': user,
    };
  }

  static CallNotificationEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallNotificationEvent(
        call: CallResponse.fromJson(json[r'call'])!,
        callCid: mapValueOfType<String>(json, r'call_cid')!,
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        members: MemberResponse.listFromJson(json[r'members'])!,
        sessionId: mapValueOfType<String>(json, r'session_id')!,
        type: mapValueOfType<String>(json, r'type', "call.notification")!,
        user: UserResponse.fromJson(json[r'user'])!,
      );
    }
    return null;
  }

  static List<CallNotificationEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallNotificationEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallNotificationEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallNotificationEvent('
        'call: $call, '
        'callCid: $callCid, '
        'createdAt: $createdAt, '
        'members: $members, '
        'sessionId: $sessionId, '
        'type: $type, '
        'user: $user, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallNotificationEvent &&
        other.call == call &&
        other.callCid == callCid &&
        other.createdAt == createdAt &&
        other.members == members &&
        other.sessionId == sessionId &&
        other.type == type &&
        other.user == user;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      call,
      callCid,
      createdAt,
      members,
      sessionId,
      type,
      user,
    ]);
  }
}
