// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_settings_response.g.dart';
part 'call_settings_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallSettingsResponse with _$CallSettingsResponse {
  const CallSettingsResponse({
    required this.audio,
    required this.backstage,
    required this.broadcasting,
    required this.frameRecording,
    required this.geofencing,
    required this.individualRecording,
    this.ingress,
    required this.limits,
    required this.rawRecording,
    required this.recording,
    required this.ring,
    required this.screensharing,
    required this.session,
    required this.thumbnails,
    required this.transcription,
    required this.video,
  });

  @override
  final AudioSettingsResponse audio;

  @override
  final BackstageSettingsResponse backstage;

  @override
  final BroadcastSettingsResponse broadcasting;

  @override
  final FrameRecordingSettingsResponse frameRecording;

  @override
  final GeofenceSettingsResponse geofencing;

  @override
  final IndividualRecordingSettingsResponse individualRecording;

  @override
  final IngressSettingsResponse? ingress;

  @override
  final LimitsSettingsResponse limits;

  @override
  final RawRecordingSettingsResponse rawRecording;

  @override
  final RecordSettingsResponse recording;

  @override
  final RingSettingsResponse ring;

  @override
  final ScreensharingSettingsResponse screensharing;

  @override
  final SessionSettingsResponse session;

  @override
  final ThumbnailsSettingsResponse thumbnails;

  @override
  final TranscriptionSettingsResponse transcription;

  @override
  final VideoSettingsResponse video;

  Map<String, dynamic> toJson() => _$CallSettingsResponseToJson(this);

  static CallSettingsResponse fromJson(Map<String, dynamic> json) =>
      _$CallSettingsResponseFromJson(json);
}
