// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_stats_participant_counts.g.dart';
part 'call_stats_participant_counts.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallStatsParticipantCounts with _$CallStatsParticipantCounts {
  const CallStatsParticipantCounts({
    this.averageJitterMs,
    this.averageLatencyMs,
    this.avgUserRating,
    this.callEventCount,
    this.cqScore,
    required this.liveSessions,
    this.maxFreezesDurationMs,
    this.minUserRating,
    required this.participants,
    required this.peakConcurrentSessions,
    required this.peakConcurrentUsers,
    required this.publishers,
    required this.sessions,
    required this.sfusUsed,
    this.totalParticipantDuration,
  });

  @override
  @JsonKey(name: 'average_jitter_ms')
  final int? averageJitterMs;

  @override
  @JsonKey(name: 'average_latency_ms')
  final int? averageLatencyMs;

  @override
  @JsonKey(name: 'avg_user_rating')
  final double? avgUserRating;

  @override
  @JsonKey(name: 'call_event_count')
  final int? callEventCount;

  @override
  @JsonKey(name: 'cq_score')
  final int? cqScore;

  @override
  @JsonKey(name: 'live_sessions')
  final int liveSessions;

  @override
  @JsonKey(name: 'max_freezes_duration_ms')
  final int? maxFreezesDurationMs;

  @override
  @JsonKey(name: 'min_user_rating')
  final int? minUserRating;

  @override
  @JsonKey(name: 'participants')
  final int participants;

  @override
  @JsonKey(name: 'peak_concurrent_sessions')
  final int peakConcurrentSessions;

  @override
  @JsonKey(name: 'peak_concurrent_users')
  final int peakConcurrentUsers;

  @override
  @JsonKey(name: 'publishers')
  final int publishers;

  @override
  @JsonKey(name: 'sessions')
  final int sessions;

  @override
  @JsonKey(name: 'sfus_used')
  final int sfusUsed;

  @override
  @JsonKey(name: 'total_participant_duration')
  final int? totalParticipantDuration;

  Map<String, dynamic> toJson() => _$CallStatsParticipantCountsToJson(this);

  static CallStatsParticipantCounts fromJson(Map<String, dynamic> json) =>
      _$CallStatsParticipantCountsFromJson(json);
}
