// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallRtmpBroadcastStartedEvent {
  const CallRtmpBroadcastStartedEvent({
    required this.callCid,
    required this.createdAt,
    required this.name,
    required this.type,
  });

  final String callCid;

  final DateTime createdAt;

  final String name;

  final String type;

  Map<String, dynamic> toJson() {
    return {
      'call_cid': callCid,
      'created_at': createdAt,
      'name': name,
      'type': type,
    };
  }

  static CallRtmpBroadcastStartedEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallRtmpBroadcastStartedEvent(
        callCid: mapValueOfType<String>(json, r'call_cid')!,
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        name: mapValueOfType<String>(json, r'name')!,
        type: mapValueOfType<String>(
            json, r'type', "call.rtmp_broadcast_started")!,
      );
    }
    return null;
  }

  static List<CallRtmpBroadcastStartedEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallRtmpBroadcastStartedEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallRtmpBroadcastStartedEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallRtmpBroadcastStartedEvent('
        'callCid: $callCid, '
        'createdAt: $createdAt, '
        'name: $name, '
        'type: $type, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallRtmpBroadcastStartedEvent &&
        other.callCid == callCid &&
        other.createdAt == createdAt &&
        other.name == name &&
        other.type == type;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      callCid,
      createdAt,
      name,
      type,
    ]);
  }
}
