// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_session_response.g.dart';
part 'call_session_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallSessionResponse with _$CallSessionResponse {
  const CallSessionResponse({
    required this.acceptedBy,
    required this.anonymousParticipantCount,
    this.endedAt,
    required this.id,
    this.liveEndedAt,
    this.liveStartedAt,
    required this.missedBy,
    required this.participants,
    required this.participantsCountByRole,
    required this.rejectedBy,
    this.startedAt,
    this.timerEndsAt,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'accepted_by')
  final Map<String, DateTime> acceptedBy;

  @override
  @JsonKey(name: 'anonymous_participant_count')
  final int anonymousParticipantCount;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'ended_at')
  final DateTime? endedAt;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'live_ended_at')
  final DateTime? liveEndedAt;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'live_started_at')
  final DateTime? liveStartedAt;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'missed_by')
  final Map<String, DateTime> missedBy;

  @override
  @JsonKey(name: 'participants')
  final List<CallParticipantResponse> participants;

  @override
  @JsonKey(name: 'participants_count_by_role')
  final Map<String, int> participantsCountByRole;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'rejected_by')
  final Map<String, DateTime> rejectedBy;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'started_at')
  final DateTime? startedAt;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'timer_ends_at')
  final DateTime? timerEndsAt;

  Map<String, dynamic> toJson() => _$CallSessionResponseToJson(this);

  static CallSessionResponse fromJson(Map<String, dynamic> json) =>
      _$CallSessionResponseFromJson(json);
}
