// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_stats_report_ready_event.g.dart';
part 'call_stats_report_ready_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallStatsReportReadyEvent extends core.WsEvent
    with _$CallStatsReportReadyEvent {
  const CallStatsReportReadyEvent({
    required this.callCid,
    required this.counts,
    required this.createdAt,
    this.isTrimmed,
    this.participantsOverview,
    required this.sessionId,
    required this.type,
  });

  @override
  @JsonKey(name: 'call_cid')
  final String callCid;

  @override
  @JsonKey(name: 'counts')
  final CallStatsParticipantCounts counts;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'is_trimmed')
  final bool? isTrimmed;

  @override
  @JsonKey(name: 'participants_overview')
  final List<CallStatsParticipant>? participantsOverview;

  @override
  @JsonKey(name: 'session_id')
  final String sessionId;

  @override
  @JsonKey(name: 'type')
  final String type;

  Map<String, dynamic> toJson() => _$CallStatsReportReadyEventToJson(this);

  static CallStatsReportReadyEvent fromJson(Map<String, dynamic> json) =>
      _$CallStatsReportReadyEventFromJson(json);
}
