// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_member_removed_event.g.dart';
part 'call_member_removed_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallMemberRemovedEvent extends core.WsEvent
    with _$CallMemberRemovedEvent {
  const CallMemberRemovedEvent({
    required this.call,
    required this.callCid,
    required this.createdAt,
    required this.members,
    required this.type,
  });

  @override
  final CallResponse call;

  @override
  final String callCid;

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  @JsonKey(defaultValue: [])
  final List<String> members;

  @override
  final String type;

  Map<String, dynamic> toJson() => _$CallMemberRemovedEventToJson(this);

  static CallMemberRemovedEvent fromJson(Map<String, dynamic> json) =>
      _$CallMemberRemovedEventFromJson(json);
}
