// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallsPerDayReportResponse {
  const CallsPerDayReportResponse({
    required this.daily,
  });

  final List<DailyAggregateCallsPerDayReportResponse> daily;

  Map<String, dynamic> toJson() {
    return {
      'daily': daily,
    };
  }

  static CallsPerDayReportResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallsPerDayReportResponse(
        daily: DailyAggregateCallsPerDayReportResponse.listFromJson(
            json[r'daily'])!,
      );
    }
    return null;
  }

  static List<CallsPerDayReportResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallsPerDayReportResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallsPerDayReportResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallsPerDayReportResponse('
        'daily: $daily, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallsPerDayReportResponse && other.daily == daily;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      daily,
    ]);
  }
}
