// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallReactionEvent {
  const CallReactionEvent({
    required this.callCid,
    required this.createdAt,
    required this.reaction,
    required this.type,
  });

  final String callCid;

  final DateTime createdAt;

  final ReactionResponse reaction;

  final String type;

  Map<String, dynamic> toJson() {
    return {
      'call_cid': callCid,
      'created_at': createdAt,
      'reaction': reaction,
      'type': type,
    };
  }

  static CallReactionEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallReactionEvent(
        callCid: mapValueOfType<String>(json, r'call_cid')!,
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        reaction: ReactionResponse.fromJson(json[r'reaction'])!,
        type: mapValueOfType<String>(json, r'type', "call.reaction_new")!,
      );
    }
    return null;
  }

  static List<CallReactionEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallReactionEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallReactionEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallReactionEvent('
        'callCid: $callCid, '
        'createdAt: $createdAt, '
        'reaction: $reaction, '
        'type: $type, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallReactionEvent &&
        other.callCid == callCid &&
        other.createdAt == createdAt &&
        other.reaction == reaction &&
        other.type == type;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      callCid,
      createdAt,
      reaction,
      type,
    ]);
  }
}
