// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallHLSBroadcastingStartedEvent {
  const CallHLSBroadcastingStartedEvent({
    required this.call,
    required this.callCid,
    required this.createdAt,
    required this.hlsPlaylistUrl,
    required this.type,
  });

  final CallResponse call;

  final String callCid;

  final DateTime createdAt;

  final String hlsPlaylistUrl;

  final String type;

  Map<String, dynamic> toJson() {
    return {
      'call': call,
      'call_cid': callCid,
      'created_at': createdAt,
      'hls_playlist_url': hlsPlaylistUrl,
      'type': type,
    };
  }

  static CallHLSBroadcastingStartedEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallHLSBroadcastingStartedEvent(
        call: CallResponse.fromJson(json[r'call'])!,
        callCid: mapValueOfType<String>(json, r'call_cid')!,
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        hlsPlaylistUrl: mapValueOfType<String>(json, r'hls_playlist_url')!,
        type: mapValueOfType<String>(
            json, r'type', "call.hls_broadcasting_started")!,
      );
    }
    return null;
  }

  static List<CallHLSBroadcastingStartedEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallHLSBroadcastingStartedEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallHLSBroadcastingStartedEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallHLSBroadcastingStartedEvent('
        'call: $call, '
        'callCid: $callCid, '
        'createdAt: $createdAt, '
        'hlsPlaylistUrl: $hlsPlaylistUrl, '
        'type: $type, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallHLSBroadcastingStartedEvent &&
        other.call == call &&
        other.callCid == callCid &&
        other.createdAt == createdAt &&
        other.hlsPlaylistUrl == hlsPlaylistUrl &&
        other.type == type;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      call,
      callCid,
      createdAt,
      hlsPlaylistUrl,
      type,
    ]);
  }
}
