// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_stats_map_publishers.g.dart';
part 'call_stats_map_publishers.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallStatsMapPublishers with _$CallStatsMapPublishers {
  const CallStatsMapPublishers({
    required this.publishers,
  });

  @override
  final List<CallStatsMapPublisher> publishers;

  Map<String, dynamic> toJson() => _$CallStatsMapPublishersToJson(this);

  static CallStatsMapPublishers fromJson(Map<String, dynamic> json) =>
      _$CallStatsMapPublishersFromJson(json);
}
