// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_response.g.dart';
part 'call_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallResponse with _$CallResponse {
  const CallResponse({
    required this.backstage,
    required this.blockedUserIds,
    required this.captioning,
    this.channelCid,
    required this.cid,
    required this.createdAt,
    required this.createdBy,
    required this.currentSessionId,
    required this.custom,
    required this.egress,
    this.endedAt,
    required this.id,
    required this.ingress,
    this.joinAheadTimeSeconds,
    required this.recording,
    this.routingNumber,
    this.session,
    required this.settings,
    this.startsAt,
    this.team,
    this.thumbnails,
    required this.transcribing,
    required this.translating,
    required this.type,
    required this.updatedAt,
  });

  @override
  @JsonKey(name: 'backstage')
  final bool backstage;

  @override
  @JsonKey(name: 'blocked_user_ids')
  final List<String> blockedUserIds;

  @override
  @JsonKey(name: 'captioning')
  final bool captioning;

  @override
  @JsonKey(name: 'channel_cid')
  final String? channelCid;

  @override
  @JsonKey(name: 'cid')
  final String cid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'created_by')
  final UserResponse createdBy;

  @override
  @JsonKey(name: 'current_session_id')
  final String currentSessionId;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @JsonKey(name: 'egress')
  final EgressResponse egress;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'ended_at')
  final DateTime? endedAt;

  @override
  @JsonKey(name: 'id')
  final String id;

  @override
  @JsonKey(name: 'ingress')
  final CallIngressResponse ingress;

  @override
  @JsonKey(name: 'join_ahead_time_seconds')
  final int? joinAheadTimeSeconds;

  @override
  @JsonKey(name: 'recording')
  final bool recording;

  @override
  @JsonKey(name: 'routing_number')
  final String? routingNumber;

  @override
  @JsonKey(name: 'session')
  final CallSessionResponse? session;

  @override
  @JsonKey(name: 'settings')
  final CallSettingsResponse settings;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'starts_at')
  final DateTime? startsAt;

  @override
  @JsonKey(name: 'team')
  final String? team;

  @override
  @JsonKey(name: 'thumbnails')
  final ThumbnailResponse? thumbnails;

  @override
  @JsonKey(name: 'transcribing')
  final bool transcribing;

  @override
  @JsonKey(name: 'translating')
  final bool translating;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  Map<String, dynamic> toJson() => _$CallResponseToJson(this);

  static CallResponse fromJson(Map<String, dynamic> json) =>
      _$CallResponseFromJson(json);
}
