// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_user_muted_event.g.dart';
part 'call_user_muted_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallUserMutedEvent extends core.WsEvent with _$CallUserMutedEvent {
  const CallUserMutedEvent({
    required this.callCid,
    required this.createdAt,
    required this.fromUserId,
    required this.mutedUserIds,
    required this.reason,
    required this.type,
  });

  @override
  @JsonKey(name: 'call_cid')
  final String callCid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'from_user_id')
  final String fromUserId;

  @override
  @JsonKey(name: 'muted_user_ids')
  final List<String> mutedUserIds;

  @override
  @JsonKey(name: 'reason')
  final String reason;

  @override
  @JsonKey(name: 'type')
  final String type;

  Map<String, dynamic> toJson() => _$CallUserMutedEventToJson(this);

  static CallUserMutedEvent fromJson(Map<String, dynamic> json) =>
      _$CallUserMutedEventFromJson(json);
}
