// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallsPerDayReport {
  const CallsPerDayReport({
    required this.count,
  });

  final int count;

  Map<String, dynamic> toJson() {
    return {
      'count': count,
    };
  }

  static CallsPerDayReport? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallsPerDayReport(
        count: mapValueOfType<int>(json, r'count')!,
      );
    }
    return null;
  }

  static List<CallsPerDayReport> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallsPerDayReport>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallsPerDayReport.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallsPerDayReport('
        'count: $count, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallsPerDayReport && other.count == count;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      count,
    ]);
  }
}
