// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_stats_participant.g.dart';
part 'call_stats_participant.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallStatsParticipant with _$CallStatsParticipant {
  const CallStatsParticipant({
    this.latestActivityAt,
    this.name,
    this.roles,
    this.sessions = const [],
    required this.userId,
  });

  @override
  @EpochDateTimeConverter()
  final DateTime? latestActivityAt;

  @override
  final String? name;

  @override
  final List<String>? roles;

  @override
  @JsonKey(defaultValue: [])
  final List<CallStatsParticipantSession> sessions;

  @override
  final String userId;

  Map<String, dynamic> toJson() => _$CallStatsParticipantToJson(this);

  static CallStatsParticipant fromJson(Map<String, dynamic> json) =>
      _$CallStatsParticipantFromJson(json);
}
