// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_participant_count_report.g.dart';
part 'call_participant_count_report.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallParticipantCountReport with _$CallParticipantCountReport {
  const CallParticipantCountReport({
    required this.histogram,
  });

  @override
  final List<ReportByHistogramBucket> histogram;

  Map<String, dynamic> toJson() => _$CallParticipantCountReportToJson(this);

  static CallParticipantCountReport fromJson(Map<String, dynamic> json) =>
      _$CallParticipantCountReportFromJson(json);
}
