// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_ended_event.g.dart';
part 'call_ended_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallEndedEvent extends core.WsEvent with _$CallEndedEvent {
  const CallEndedEvent({
    required this.call,
    required this.callCid,
    required this.createdAt,
    this.members,
    this.reason,
    required this.type,
    this.user,
  });

  @override
  @JsonKey(name: 'call')
  final CallResponse call;

  @override
  @JsonKey(name: 'call_cid')
  final String callCid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'members')
  final List<MemberResponse>? members;

  @override
  @JsonKey(name: 'reason')
  final String? reason;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @JsonKey(name: 'user')
  final UserResponse? user;

  Map<String, dynamic> toJson() => _$CallEndedEventToJson(this);

  static CallEndedEvent fromJson(Map<String, dynamic> json) =>
      _$CallEndedEventFromJson(json);
}
