// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_settings_request.g.dart';
part 'call_settings_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallSettingsRequest with _$CallSettingsRequest {
  const CallSettingsRequest({
    this.audio,
    this.backstage,
    this.broadcasting,
    this.encryption,
    this.frameRecording,
    this.geofencing,
    this.individualRecording,
    this.ingress,
    this.limits,
    this.rawRecording,
    this.recording,
    this.ring,
    this.screensharing,
    this.session,
    this.thumbnails,
    this.transcription,
    this.video,
  });

  @override
  @JsonKey(name: 'audio')
  final AudioSettingsRequest? audio;

  @override
  @JsonKey(name: 'backstage')
  final BackstageSettingsRequest? backstage;

  @override
  @JsonKey(name: 'broadcasting')
  final BroadcastSettingsRequest? broadcasting;

  @override
  @JsonKey(name: 'encryption')
  final EncryptionSettingsRequest? encryption;

  @override
  @JsonKey(name: 'frame_recording')
  final FrameRecordingSettingsRequest? frameRecording;

  @override
  @JsonKey(name: 'geofencing')
  final GeofenceSettingsRequest? geofencing;

  @override
  @JsonKey(name: 'individual_recording')
  final IndividualRecordingSettingsRequest? individualRecording;

  @override
  @JsonKey(name: 'ingress')
  final IngressSettingsRequest? ingress;

  @override
  @JsonKey(name: 'limits')
  final LimitsSettingsRequest? limits;

  @override
  @JsonKey(name: 'raw_recording')
  final RawRecordingSettingsRequest? rawRecording;

  @override
  @JsonKey(name: 'recording')
  final RecordSettingsRequest? recording;

  @override
  @JsonKey(name: 'ring')
  final RingSettingsRequest? ring;

  @override
  @JsonKey(name: 'screensharing')
  final ScreensharingSettingsRequest? screensharing;

  @override
  @JsonKey(name: 'session')
  final SessionSettingsRequest? session;

  @override
  @JsonKey(name: 'thumbnails')
  final ThumbnailsSettingsRequest? thumbnails;

  @override
  @JsonKey(name: 'transcription')
  final TranscriptionSettingsRequest? transcription;

  @override
  @JsonKey(name: 'video')
  final VideoSettingsRequest? video;

  Map<String, dynamic> toJson() => _$CallSettingsRequestToJson(this);

  static CallSettingsRequest fromJson(Map<String, dynamic> json) =>
      _$CallSettingsRequestFromJson(json);
}
