// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_settings_request.g.dart';
part 'call_settings_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallSettingsRequest with _$CallSettingsRequest {
  const CallSettingsRequest({
    this.audio,
    this.backstage,
    this.broadcasting,
    this.frameRecording,
    this.geofencing,
    this.individualRecording,
    this.ingress,
    this.limits,
    this.rawRecording,
    this.recording,
    this.ring,
    this.screensharing,
    this.session,
    this.thumbnails,
    this.transcription,
    this.video,
  });

  @override
  final AudioSettingsRequest? audio;

  @override
  final BackstageSettingsRequest? backstage;

  @override
  final BroadcastSettingsRequest? broadcasting;

  @override
  final FrameRecordingSettingsRequest? frameRecording;

  @override
  final GeofenceSettingsRequest? geofencing;

  @override
  final IndividualRecordingSettingsRequest? individualRecording;

  @override
  final IngressSettingsRequest? ingress;

  @override
  final LimitsSettingsRequest? limits;

  @override
  final RawRecordingSettingsRequest? rawRecording;

  @override
  final RecordSettingsRequest? recording;

  @override
  final RingSettingsRequest? ring;

  @override
  final ScreensharingSettingsRequest? screensharing;

  @override
  final SessionSettingsRequest? session;

  @override
  final ThumbnailsSettingsRequest? thumbnails;

  @override
  final TranscriptionSettingsRequest? transcription;

  @override
  final VideoSettingsRequest? video;

  Map<String, dynamic> toJson() => _$CallSettingsRequestToJson(this);

  static CallSettingsRequest fromJson(Map<String, dynamic> json) =>
      _$CallSettingsRequestFromJson(json);
}
