// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_stats_map_subscribers.g.dart';
part 'call_stats_map_subscribers.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallStatsMapSubscribers with _$CallStatsMapSubscribers {
  const CallStatsMapSubscribers({
    required this.locations,
    this.participants,
  });

  @override
  @JsonKey(defaultValue: [])
  final List<CallStatsMapLocation> locations;

  @override
  final List<CallStatsMapSubscriber>? participants;

  Map<String, dynamic> toJson() => _$CallStatsMapSubscribersToJson(this);

  static CallStatsMapSubscribers fromJson(Map<String, dynamic> json) =>
      _$CallStatsMapSubscribersFromJson(json);
}
