// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CallUserMutedEvent {
  const CallUserMutedEvent({
    required this.callCid,
    required this.createdAt,
    required this.fromUserId,
    required this.mutedUserIds,
    required this.type,
  });

  final String callCid;

  final DateTime createdAt;

  final String fromUserId;

  final List<String> mutedUserIds;

  final String type;

  Map<String, dynamic> toJson() {
    return {
      'call_cid': callCid,
      'created_at': createdAt,
      'from_user_id': fromUserId,
      'muted_user_ids': mutedUserIds,
      'type': type,
    };
  }

  static CallUserMutedEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CallUserMutedEvent(
        callCid: mapValueOfType<String>(json, r'call_cid')!,
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        fromUserId: mapValueOfType<String>(json, r'from_user_id')!,
        mutedUserIds: json[r'muted_user_ids'] is Iterable
            ? (json[r'muted_user_ids'] as Iterable)
                .cast<String>()
                .toList(growable: false)
            : const []!,
        type: mapValueOfType<String>(json, r'type', "call.user_muted")!,
      );
    }
    return null;
  }

  static List<CallUserMutedEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CallUserMutedEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CallUserMutedEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CallUserMutedEvent('
        'callCid: $callCid, '
        'createdAt: $createdAt, '
        'fromUserId: $fromUserId, '
        'mutedUserIds: $mutedUserIds, '
        'type: $type, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CallUserMutedEvent &&
        other.callCid == callCid &&
        other.createdAt == createdAt &&
        other.fromUserId == fromUserId &&
        other.mutedUserIds == mutedUserIds &&
        other.type == type;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      callCid,
      createdAt,
      fromUserId,
      mutedUserIds,
      type,
    ]);
  }
}
