// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_reaction_event.g.dart';
part 'call_reaction_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallReactionEvent extends core.WsEvent with _$CallReactionEvent {
  const CallReactionEvent({
    required this.callCid,
    required this.createdAt,
    required this.reaction,
    required this.type,
  });

  @override
  @JsonKey(name: 'call_cid')
  final String callCid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'reaction')
  final VideoReactionResponse reaction;

  @override
  @JsonKey(name: 'type')
  final String type;

  Map<String, dynamic> toJson() => _$CallReactionEventToJson(this);

  static CallReactionEvent fromJson(Map<String, dynamic> json) =>
      _$CallReactionEventFromJson(json);
}
