// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_session_participant_left_event.g.dart';
part 'call_session_participant_left_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallSessionParticipantLeftEvent extends core.WsEvent
    with _$CallSessionParticipantLeftEvent {
  const CallSessionParticipantLeftEvent({
    required this.callCid,
    required this.createdAt,
    required this.durationSeconds,
    required this.participant,
    this.reason,
    required this.sessionId,
    required this.type,
  });

  @override
  @JsonKey(name: 'call_cid')
  final String callCid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'duration_seconds')
  final int durationSeconds;

  @override
  @JsonKey(name: 'participant')
  final CallParticipantResponse participant;

  @override
  @JsonKey(name: 'reason')
  final String? reason;

  @override
  @JsonKey(name: 'session_id')
  final String sessionId;

  @override
  @JsonKey(name: 'type')
  final String type;

  Map<String, dynamic> toJson() =>
      _$CallSessionParticipantLeftEventToJson(this);

  static CallSessionParticipantLeftEvent fromJson(Map<String, dynamic> json) =>
      _$CallSessionParticipantLeftEventFromJson(json);
}
