// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_dtmf_event.g.dart';
part 'call_dtmf_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallDTMFEvent extends core.WsEvent with _$CallDTMFEvent {
  const CallDTMFEvent({
    required this.callCid,
    required this.createdAt,
    required this.digit,
    required this.durationMs,
    required this.seqNumber,
    required this.timestamp,
    required this.type,
    required this.user,
  });

  @override
  @JsonKey(name: 'call_cid')
  final String callCid;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'digit')
  final String digit;

  @override
  @JsonKey(name: 'duration_ms')
  final int durationMs;

  @override
  @JsonKey(name: 'seq_number')
  final int seqNumber;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'timestamp')
  final DateTime timestamp;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @JsonKey(name: 'user')
  final UserResponse user;

  Map<String, dynamic> toJson() => _$CallDTMFEventToJson(this);

  static CallDTMFEvent fromJson(Map<String, dynamic> json) =>
      _$CallDTMFEventFromJson(json);
}
