// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_settings_response.g.dart';
part 'call_settings_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallSettingsResponse with _$CallSettingsResponse {
  const CallSettingsResponse({
    required this.audio,
    required this.backstage,
    required this.broadcasting,
    required this.encryption,
    required this.frameRecording,
    required this.geofencing,
    required this.individualRecording,
    this.ingress,
    required this.limits,
    required this.rawRecording,
    required this.recording,
    required this.ring,
    required this.screensharing,
    required this.session,
    required this.thumbnails,
    required this.transcription,
    required this.video,
  });

  @override
  @JsonKey(name: 'audio')
  final AudioSettingsResponse audio;

  @override
  @JsonKey(name: 'backstage')
  final BackstageSettingsResponse backstage;

  @override
  @JsonKey(name: 'broadcasting')
  final BroadcastSettingsResponse broadcasting;

  @override
  @JsonKey(name: 'encryption')
  final EncryptionSettingsResponse encryption;

  @override
  @JsonKey(name: 'frame_recording')
  final FrameRecordingSettingsResponse frameRecording;

  @override
  @JsonKey(name: 'geofencing')
  final GeofenceSettingsResponse geofencing;

  @override
  @JsonKey(name: 'individual_recording')
  final IndividualRecordingSettingsResponse individualRecording;

  @override
  @JsonKey(name: 'ingress')
  final IngressSettingsResponse? ingress;

  @override
  @JsonKey(name: 'limits')
  final LimitsSettingsResponse limits;

  @override
  @JsonKey(name: 'raw_recording')
  final RawRecordingSettingsResponse rawRecording;

  @override
  @JsonKey(name: 'recording')
  final RecordSettingsResponse recording;

  @override
  @JsonKey(name: 'ring')
  final RingSettingsResponse ring;

  @override
  @JsonKey(name: 'screensharing')
  final ScreensharingSettingsResponse screensharing;

  @override
  @JsonKey(name: 'session')
  final SessionSettingsResponse session;

  @override
  @JsonKey(name: 'thumbnails')
  final ThumbnailsSettingsResponse thumbnails;

  @override
  @JsonKey(name: 'transcription')
  final TranscriptionSettingsResponse transcription;

  @override
  @JsonKey(name: 'video')
  final VideoSettingsResponse video;

  Map<String, dynamic> toJson() => _$CallSettingsResponseToJson(this);

  static CallSettingsResponse fromJson(Map<String, dynamic> json) =>
      _$CallSettingsResponseFromJson(json);
}
