// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'call_moderation_blur_event.g.dart';
part 'call_moderation_blur_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class CallModerationBlurEvent extends core.WsEvent
    with _$CallModerationBlurEvent {
  const CallModerationBlurEvent({
    required this.callCid,
    required this.createdAt,
    required this.custom,
    required this.type,
    required this.userId,
  });

  @override
  final String callCid;

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  final Map<String, Object?> custom;

  @override
  final String type;

  @override
  final String userId;

  Map<String, dynamic> toJson() => _$CallModerationBlurEventToJson(this);

  static CallModerationBlurEvent fromJson(Map<String, dynamic> json) =>
      _$CallModerationBlurEventFromJson(json);
}
