// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'connection_error_event.g.dart';
part 'connection_error_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ConnectionErrorEvent extends core.WsEvent with _$ConnectionErrorEvent {
  const ConnectionErrorEvent({
    required this.connectionId,
    required this.createdAt,
    required this.type,
  });

  @override
  final String connectionId;

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  final String type;

  Map<String, dynamic> toJson() => _$ConnectionErrorEventToJson(this);

  static ConnectionErrorEvent fromJson(Map<String, dynamic> json) =>
      _$ConnectionErrorEventFromJson(json);
}
