// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class ConnectionErrorEvent {
  const ConnectionErrorEvent({
    required this.connectionId,
    required this.createdAt,
    required this.error,
    required this.type,
  });

  final String connectionId;

  final DateTime createdAt;

  final APIError error;

  final String type;

  Map<String, dynamic> toJson() {
    return {
      'connection_id': connectionId,
      'created_at': createdAt,
      'error': error,
      'type': type,
    };
  }

  static ConnectionErrorEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return ConnectionErrorEvent(
        connectionId: mapValueOfType<String>(json, r'connection_id')!,
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        error: APIError.fromJson(json[r'error'])!,
        type: mapValueOfType<String>(json, r'type', "connection.error")!,
      );
    }
    return null;
  }

  static List<ConnectionErrorEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <ConnectionErrorEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = ConnectionErrorEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'ConnectionErrorEvent('
        'connectionId: $connectionId, '
        'createdAt: $createdAt, '
        'error: $error, '
        'type: $type, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ConnectionErrorEvent &&
        other.connectionId == connectionId &&
        other.createdAt == createdAt &&
        other.error == error &&
        other.type == type;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      connectionId,
      createdAt,
      error,
      type,
    ]);
  }
}
