// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class CreateGuestResponse {
  const CreateGuestResponse({
    required this.accessToken,
    required this.duration,
    required this.user,
  });

  final String accessToken;

  final String duration;

  final UserResponse user;

  Map<String, dynamic> toJson() {
    return {
      'access_token': accessToken,
      'duration': duration,
      'user': user,
    };
  }

  static CreateGuestResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return CreateGuestResponse(
        accessToken: mapValueOfType<String>(json, r'access_token')!,
        duration: mapValueOfType<String>(json, r'duration')!,
        user: UserResponse.fromJson(json[r'user'])!,
      );
    }
    return null;
  }

  static List<CreateGuestResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <CreateGuestResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = CreateGuestResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'CreateGuestResponse('
        'accessToken: $accessToken, '
        'duration: $duration, '
        'user: $user, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is CreateGuestResponse &&
        other.accessToken == accessToken &&
        other.duration == duration &&
        other.user == user;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      accessToken,
      duration,
      user,
    ]);
  }
}
