// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class DailyAggregateSDKUsageReportResponse {
  const DailyAggregateSDKUsageReportResponse({
    required this.date,
    required this.report,
  });

  final String date;

  final SDKUsageReport report;

  Map<String, dynamic> toJson() {
    return {
      'date': date,
      'report': report,
    };
  }

  static DailyAggregateSDKUsageReportResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return DailyAggregateSDKUsageReportResponse(
        date: mapValueOfType<String>(json, r'date')!,
        report: SDKUsageReport.fromJson(json[r'report'])!,
      );
    }
    return null;
  }

  static List<DailyAggregateSDKUsageReportResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <DailyAggregateSDKUsageReportResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = DailyAggregateSDKUsageReportResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'DailyAggregateSDKUsageReportResponse('
        'date: $date, '
        'report: $report, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is DailyAggregateSDKUsageReportResponse &&
        other.date == date &&
        other.report == report;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      date,
      report,
    ]);
  }
}
