// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'delete_reaction_request_payload.g.dart';
part 'delete_reaction_request_payload.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class DeleteReactionRequestPayload with _$DeleteReactionRequestPayload {
  const DeleteReactionRequestPayload({
    this.entityId,
    this.entityType,
    this.hardDelete,
    this.reason,
  });

  @override
  final String? entityId;

  @override
  final String? entityType;

  @override
  final bool? hardDelete;

  @override
  final String? reason;

  Map<String, dynamic> toJson() => _$DeleteReactionRequestPayloadToJson(this);

  static DeleteReactionRequestPayload fromJson(Map<String, dynamic> json) =>
      _$DeleteReactionRequestPayloadFromJson(json);
}
