// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'delivery_zone_segment.g.dart';
part 'delivery_zone_segment.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class DeliveryZoneSegment with _$DeliveryZoneSegment {
  const DeliveryZoneSegment({
    this.avgQualityScore,
    required this.key,
    required this.outlier,
    this.p5QualityScore,
    this.poorPct,
    required this.sessions,
    this.sharePct,
    this.watchSharePct,
  });

  @override
  @JsonKey(name: 'avg_quality_score')
  final double? avgQualityScore;

  @override
  @JsonKey(name: 'key')
  final String key;

  @override
  @JsonKey(name: 'outlier')
  final bool outlier;

  @override
  @JsonKey(name: 'p5_quality_score')
  final double? p5QualityScore;

  @override
  @JsonKey(name: 'poor_pct')
  final double? poorPct;

  @override
  @JsonKey(name: 'sessions')
  final int sessions;

  @override
  @JsonKey(name: 'share_pct')
  final double? sharePct;

  @override
  @JsonKey(name: 'watch_share_pct')
  final double? watchSharePct;

  Map<String, dynamic> toJson() => _$DeliveryZoneSegmentToJson(this);

  static DeliveryZoneSegment fromJson(Map<String, dynamic> json) =>
      _$DeliveryZoneSegmentFromJson(json);
}
