// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'draft_response.g.dart';
part 'draft_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class DraftResponse with _$DraftResponse {
  const DraftResponse({
    this.channel,
    required this.channelCid,
    required this.createdAt,
    required this.message,
    this.parentId,
    this.parentMessage,
    this.quotedMessage,
  });

  @override
  final ChannelResponse? channel;

  @override
  final String channelCid;

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  final DraftPayloadResponse message;

  @override
  final String? parentId;

  @override
  final MessageResponse? parentMessage;

  @override
  final MessageResponse? quotedMessage;

  Map<String, dynamic> toJson() => _$DraftResponseToJson(this);

  static DraftResponse fromJson(Map<String, dynamic> json) =>
      _$DraftResponseFromJson(json);
}
