// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'egress_response.g.dart';
part 'egress_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class EgressResponse with _$EgressResponse {
  const EgressResponse({
    required this.broadcasting,
    this.compositeRecording,
    this.frameRecording,
    this.hls,
    this.individualRecording,
    this.rawRecording,
    required this.rtmps,
  });

  @override
  @JsonKey(name: 'broadcasting')
  final bool broadcasting;

  @override
  @JsonKey(name: 'composite_recording')
  final CompositeRecordingResponse? compositeRecording;

  @override
  @JsonKey(name: 'frame_recording')
  final FrameRecordingResponse? frameRecording;

  @override
  @JsonKey(name: 'hls')
  final EgressHLSResponse? hls;

  @override
  @JsonKey(name: 'individual_recording')
  final IndividualRecordingResponse? individualRecording;

  @override
  @JsonKey(name: 'raw_recording')
  final RawRecordingResponse? rawRecording;

  @override
  @JsonKey(name: 'rtmps')
  final List<EgressRTMPResponse> rtmps;

  Map<String, dynamic> toJson() => _$EgressResponseToJson(this);

  static EgressResponse fromJson(Map<String, dynamic> json) =>
      _$EgressResponseFromJson(json);
}
