// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'feeds_v3_comment_response.g.dart';
part 'feeds_v3_comment_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FeedsV3CommentResponse with _$FeedsV3CommentResponse {
  const FeedsV3CommentResponse({
    this.attachments,
    required this.bookmarkCount,
    required this.confidenceScore,
    this.controversyScore,
    required this.createdAt,
    this.custom,
    this.deletedAt,
    required this.downvoteCount,
    this.editedAt,
    required this.id,
    this.latestReactions,
    this.mentionedUsers = const [],
    this.moderation,
    required this.objectId,
    required this.objectType,
    this.ownReactions = const [],
    this.parentId,
    required this.reactionCount,
    this.reactionGroups,
    required this.replyCount,
    required this.score,
    required this.status,
    this.text,
    required this.updatedAt,
    required this.upvoteCount,
    required this.user,
  });

  @override
  final List<Attachment>? attachments;

  @override
  final int bookmarkCount;

  @override
  final double confidenceScore;

  @override
  final double? controversyScore;

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  final Map<String, Object?>? custom;

  @override
  @EpochDateTimeConverter()
  final DateTime? deletedAt;

  @override
  final int downvoteCount;

  @override
  @EpochDateTimeConverter()
  final DateTime? editedAt;

  @override
  final String id;

  @override
  final List<FeedsReactionResponse>? latestReactions;

  @override
  @JsonKey(defaultValue: [])
  final List<UserResponse> mentionedUsers;

  @override
  final ModerationV2Response? moderation;

  @override
  final String objectId;

  @override
  final String objectType;

  @override
  @JsonKey(defaultValue: [])
  final List<FeedsReactionResponse> ownReactions;

  @override
  final String? parentId;

  @override
  final int reactionCount;

  @override
  final Map<String, FeedsReactionGroupResponse>? reactionGroups;

  @override
  final int replyCount;

  @override
  final int score;

  @override
  final String status;

  @override
  final String? text;

  @override
  @EpochDateTimeConverter()
  final DateTime updatedAt;

  @override
  final int upvoteCount;

  @override
  final UserResponse user;

  Map<String, dynamic> toJson() => _$FeedsV3CommentResponseToJson(this);

  static FeedsV3CommentResponse fromJson(Map<String, dynamic> json) =>
      _$FeedsV3CommentResponseFromJson(json);
}
