// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'feeds_v3_activity_response.g.dart';
part 'feeds_v3_activity_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FeedsV3ActivityResponse with _$FeedsV3ActivityResponse {
  const FeedsV3ActivityResponse({
    required this.attachments,
    required this.bookmarkCount,
    required this.collections,
    required this.commentCount,
    required this.comments,
    required this.createdAt,
    this.currentFeed,
    required this.custom,
    this.deletedAt,
    this.editedAt,
    this.expiresAt,
    required this.feeds,
    required this.filterTags,
    this.friendReactionCount,
    this.friendReactions,
    required this.hidden,
    required this.id,
    required this.interestTags,
    this.isRead,
    this.isSeen,
    this.isWatched,
    required this.latestReactions,
    this.location,
    required this.mentionedUsers,
    this.metrics,
    this.moderation,
    this.moderationAction,
    this.notificationContext,
    required this.ownBookmarks,
    required this.ownReactions,
    this.parent,
    this.poll,
    required this.popularity,
    required this.preview,
    required this.reactionCount,
    required this.reactionGroups,
    required this.restrictReplies,
    required this.score,
    this.scoreVars,
    required this.searchData,
    this.selectorSource,
    required this.shareCount,
    this.text,
    required this.type,
    required this.updatedAt,
    required this.user,
    required this.visibility,
    this.visibilityTag,
  });

  @override
  @JsonKey(defaultValue: [])
  final List<Attachment> attachments;

  @override
  final int bookmarkCount;

  @override
  @JsonKey(defaultValue: {})
  final Map<String, FeedsEnrichedCollectionResponse> collections;

  @override
  final int commentCount;

  @override
  @JsonKey(defaultValue: [])
  final List<FeedsV3CommentResponse> comments;

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  final FeedsFeedResponse? currentFeed;

  @override
  @JsonKey(defaultValue: {})
  final Map<String, Object?> custom;

  @override
  @EpochDateTimeConverter()
  final DateTime? deletedAt;

  @override
  @EpochDateTimeConverter()
  final DateTime? editedAt;

  @override
  @EpochDateTimeConverter()
  final DateTime? expiresAt;

  @override
  @JsonKey(defaultValue: [])
  final List<String> feeds;

  @override
  @JsonKey(defaultValue: [])
  final List<String> filterTags;

  @override
  final int? friendReactionCount;

  @override
  final List<FeedsReactionResponse>? friendReactions;

  @override
  final bool hidden;

  @override
  final String id;

  @override
  @JsonKey(defaultValue: [])
  final List<String> interestTags;

  @override
  final bool? isRead;

  @override
  final bool? isSeen;

  @override
  final bool? isWatched;

  @override
  @JsonKey(defaultValue: [])
  final List<FeedsReactionResponse> latestReactions;

  @override
  final FeedsActivityLocation? location;

  @override
  @JsonKey(defaultValue: [])
  final List<UserResponse> mentionedUsers;

  @override
  final Map<String, int>? metrics;

  @override
  final ModerationV2Response? moderation;

  @override
  final String? moderationAction;

  @override
  final FeedsNotificationContext? notificationContext;

  @override
  @JsonKey(defaultValue: [])
  final List<FeedsBookmarkResponse> ownBookmarks;

  @override
  @JsonKey(defaultValue: [])
  final List<FeedsReactionResponse> ownReactions;

  @override
  final FeedsV3ActivityResponse? parent;

  @override
  final PollResponseData? poll;

  @override
  final int popularity;

  @override
  final bool preview;

  @override
  final int reactionCount;

  @override
  @JsonKey(defaultValue: {})
  final Map<String, FeedsReactionGroupResponse> reactionGroups;

  @override
  final String restrictReplies;

  @override
  final double score;

  @override
  final Map<String, Object?>? scoreVars;

  @override
  @JsonKey(defaultValue: {})
  final Map<String, Object?> searchData;

  @override
  final String? selectorSource;

  @override
  final int shareCount;

  @override
  final String? text;

  @override
  final String type;

  @override
  @EpochDateTimeConverter()
  final DateTime updatedAt;

  @override
  final UserResponse user;

  @override
  final String visibility;

  @override
  final String? visibilityTag;

  Map<String, dynamic> toJson() => _$FeedsV3ActivityResponseToJson(this);

  static FeedsV3ActivityResponse fromJson(Map<String, dynamic> json) =>
      _$FeedsV3ActivityResponseFromJson(json);
}
