// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'feeds_preferences_response.g.dart';
part 'feeds_preferences_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FeedsPreferencesResponse with _$FeedsPreferencesResponse {
  const FeedsPreferencesResponse({
    this.comment,
    this.commentMention,
    this.commentReaction,
    this.commentReply,
    this.customActivityTypes,
    this.follow,
    this.mention,
    this.reaction,
  });

  @override
  final String? comment;

  @override
  final String? commentMention;

  @override
  final String? commentReaction;

  @override
  final String? commentReply;

  @override
  final Map<String, String>? customActivityTypes;

  @override
  final String? follow;

  @override
  final String? mention;

  @override
  final String? reaction;

  Map<String, dynamic> toJson() => _$FeedsPreferencesResponseToJson(this);

  static FeedsPreferencesResponse fromJson(Map<String, dynamic> json) =>
      _$FeedsPreferencesResponseFromJson(json);
}
