// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'frame_recording_settings_request.g.dart';
part 'frame_recording_settings_request.freezed.dart';

@JsonEnum(alwaysCreate: true)
enum FrameRecordingSettingsRequestMode {
  @JsonValue('auto-on')
  autoOn,
  @JsonValue('available')
  available,
  @JsonValue('disabled')
  disabled,
  @JsonValue('_unknown')
  unknown,
}

@JsonEnum(alwaysCreate: true)
enum FrameRecordingSettingsRequestQuality {
  @JsonValue('1080p')
  n1080p,
  @JsonValue('1440p')
  n1440p,
  @JsonValue('360p')
  n360p,
  @JsonValue('480p')
  n480p,
  @JsonValue('720p')
  n720p,
  @JsonValue('_unknown')
  unknown,
}

@freezed
@immutable
@JsonSerializable()
class FrameRecordingSettingsRequest with _$FrameRecordingSettingsRequest {
  const FrameRecordingSettingsRequest({
    required this.captureIntervalInSeconds,
    required this.mode,
    this.quality,
  });

  @override
  final int captureIntervalInSeconds;

  @override
  @JsonKey(unknownEnumValue: FrameRecordingSettingsRequestMode.unknown)
  final FrameRecordingSettingsRequestMode mode;

  @override
  @JsonKey(unknownEnumValue: FrameRecordingSettingsRequestQuality.unknown)
  final FrameRecordingSettingsRequestQuality? quality;

  Map<String, dynamic> toJson() => _$FrameRecordingSettingsRequestToJson(this);

  static FrameRecordingSettingsRequest fromJson(Map<String, dynamic> json) =>
      _$FrameRecordingSettingsRequestFromJson(json);
}
