// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'frame_recording_response.g.dart';
part 'frame_recording_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class FrameRecordingResponse with _$FrameRecordingResponse {
  const FrameRecordingResponse({
    required this.status,
  });

  @override
  final String status;

  Map<String, dynamic> toJson() => _$FrameRecordingResponseToJson(this);

  static FrameRecordingResponse fromJson(Map<String, dynamic> json) =>
      _$FrameRecordingResponseFromJson(json);
}
