// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'frame_recording_settings_response.g.dart';
part 'frame_recording_settings_response.freezed.dart';

extension type const FrameRecordingSettingsResponseMode._(String _)
    implements String {
  static const autoOn = FrameRecordingSettingsResponseMode._('auto-on');
  static const available = FrameRecordingSettingsResponseMode._('available');
  static const disabled = FrameRecordingSettingsResponseMode._('disabled');

  factory FrameRecordingSettingsResponseMode.fromJson(String json) =>
      FrameRecordingSettingsResponseMode._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class FrameRecordingSettingsResponse with _$FrameRecordingSettingsResponse {
  const FrameRecordingSettingsResponse({
    required this.captureIntervalInSeconds,
    required this.mode,
    this.quality,
  });

  @override
  @JsonKey(name: 'capture_interval_in_seconds')
  final int captureIntervalInSeconds;

  @override
  @JsonKey(name: 'mode')
  final FrameRecordingSettingsResponseMode mode;

  @override
  @JsonKey(name: 'quality')
  final String? quality;

  Map<String, dynamic> toJson() => _$FrameRecordingSettingsResponseToJson(this);

  static FrameRecordingSettingsResponse fromJson(Map<String, dynamic> json) =>
      _$FrameRecordingSettingsResponseFromJson(json);
}
