// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class FrameRecordingResponse {
  const FrameRecordingResponse({
    required this.status,
  });

  final String status;

  Map<String, dynamic> toJson() {
    return {
      'status': status,
    };
  }

  static FrameRecordingResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return FrameRecordingResponse(
        status: mapValueOfType<String>(json, r'status')!,
      );
    }
    return null;
  }

  static List<FrameRecordingResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <FrameRecordingResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = FrameRecordingResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'FrameRecordingResponse('
        'status: $status, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is FrameRecordingResponse && other.status == status;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      status,
    ]);
  }
}
