// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class GeofenceSettingsResponse {
  const GeofenceSettingsResponse({
    required this.names,
  });

  final List<String> names;

  Map<String, dynamic> toJson() {
    return {
      'names': names,
    };
  }

  static GeofenceSettingsResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return GeofenceSettingsResponse(
        names: json[r'names'] is Iterable
            ? (json[r'names'] as Iterable)
                .cast<String>()
                .toList(growable: false)
            : const []!,
      );
    }
    return null;
  }

  static List<GeofenceSettingsResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <GeofenceSettingsResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = GeofenceSettingsResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'GeofenceSettingsResponse('
        'names: $names, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is GeofenceSettingsResponse && other.names == names;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      names,
    ]);
  }
}
