// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'get_call_session_participant_stats_details_response.g.dart';
part 'get_call_session_participant_stats_details_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class GetCallSessionParticipantStatsDetailsResponse
    with _$GetCallSessionParticipantStatsDetailsResponse {
  const GetCallSessionParticipantStatsDetailsResponse({
    required this.callId,
    required this.callSessionId,
    required this.callType,
    required this.duration,
    this.publisher,
    this.subscriber,
    this.timeframe,
    this.user,
    required this.userId,
    required this.userSessionId,
  });

  @override
  final String callId;

  @override
  final String callSessionId;

  @override
  final String callType;

  @override
  final String duration;

  @override
  final ParticipantSeriesPublisherStats? publisher;

  @override
  final ParticipantSeriesSubscriberStats? subscriber;

  @override
  final ParticipantSeriesTimeframe? timeframe;

  @override
  final ParticipantSeriesUserStats? user;

  @override
  final String userId;

  @override
  final String userSessionId;

  Map<String, dynamic> toJson() =>
      _$GetCallSessionParticipantStatsDetailsResponseToJson(this);

  static GetCallSessionParticipantStatsDetailsResponse fromJson(
    Map<String, dynamic> json,
  ) => _$GetCallSessionParticipantStatsDetailsResponseFromJson(json);
}
