// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'get_call_participant_session_metrics_response.g.dart';
part 'get_call_participant_session_metrics_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class GetCallParticipantSessionMetricsResponse
    with _$GetCallParticipantSessionMetricsResponse {
  const GetCallParticipantSessionMetricsResponse({
    this.client,
    required this.duration,
    this.isPublisher,
    this.isSubscriber,
    this.joinedAt,
    this.publishedTracks,
    this.publisherType,
    this.userId,
    this.userSessionId,
  });

  @override
  @JsonKey(name: 'client')
  final SessionClient? client;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'is_publisher')
  final bool? isPublisher;

  @override
  @JsonKey(name: 'is_subscriber')
  final bool? isSubscriber;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'joined_at')
  final DateTime? joinedAt;

  @override
  @JsonKey(name: 'published_tracks')
  final List<PublishedTrackMetrics>? publishedTracks;

  @override
  @JsonKey(name: 'publisher_type')
  final String? publisherType;

  @override
  @JsonKey(name: 'user_id')
  final String? userId;

  @override
  @JsonKey(name: 'user_session_id')
  final String? userSessionId;

  Map<String, dynamic> toJson() =>
      _$GetCallParticipantSessionMetricsResponseToJson(this);

  static GetCallParticipantSessionMetricsResponse fromJson(
    Map<String, dynamic> json,
  ) => _$GetCallParticipantSessionMetricsResponseFromJson(json);
}
