// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'go_live_request.g.dart';
part 'go_live_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class GoLiveRequest with _$GoLiveRequest {
  const GoLiveRequest({
    this.recordingStorageName,
    this.startClosedCaption,
    this.startCompositeRecording,
    this.startHls,
    this.startIndividualRecording,
    this.startRawRecording,
    this.startRecording,
    this.startTranscription,
    this.transcriptionStorageName,
  });

  @override
  @JsonKey(name: 'recording_storage_name')
  final String? recordingStorageName;

  @override
  @JsonKey(name: 'start_closed_caption')
  final bool? startClosedCaption;

  @override
  @JsonKey(name: 'start_composite_recording')
  final bool? startCompositeRecording;

  @override
  @JsonKey(name: 'start_hls')
  final bool? startHls;

  @override
  @JsonKey(name: 'start_individual_recording')
  final bool? startIndividualRecording;

  @override
  @JsonKey(name: 'start_raw_recording')
  final bool? startRawRecording;

  @override
  @JsonKey(name: 'start_recording')
  final bool? startRecording;

  @override
  @JsonKey(name: 'start_transcription')
  final bool? startTranscription;

  @override
  @JsonKey(name: 'transcription_storage_name')
  final String? transcriptionStorageName;

  Map<String, dynamic> toJson() => _$GoLiveRequestToJson(this);

  static GoLiveRequest fromJson(Map<String, dynamic> json) =>
      _$GoLiveRequestFromJson(json);
}
