// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class GoLiveResponse {
  const GoLiveResponse({
    required this.call,
    required this.duration,
  });

  final CallResponse call;

  final String duration;

  Map<String, dynamic> toJson() {
    return {
      'call': call,
      'duration': duration,
    };
  }

  static GoLiveResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return GoLiveResponse(
        call: CallResponse.fromJson(json[r'call'])!,
        duration: mapValueOfType<String>(json, r'duration')!,
      );
    }
    return null;
  }

  static List<GoLiveResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <GoLiveResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = GoLiveResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'GoLiveResponse('
        'call: $call, '
        'duration: $duration, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is GoLiveResponse &&
        other.call == call &&
        other.duration == duration;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      call,
      duration,
    ]);
  }
}
