// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class HLSSettingsResponse {
  const HLSSettingsResponse({
    required this.autoOn,
    required this.enabled,
    required this.qualityTracks,
  });

  final bool autoOn;

  final bool enabled;

  final List<String> qualityTracks;

  Map<String, dynamic> toJson() {
    return {
      'auto_on': autoOn,
      'enabled': enabled,
      'quality_tracks': qualityTracks,
    };
  }

  static HLSSettingsResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return HLSSettingsResponse(
        autoOn: mapValueOfType<bool>(json, r'auto_on')!,
        enabled: mapValueOfType<bool>(json, r'enabled')!,
        qualityTracks: json[r'quality_tracks'] is Iterable
            ? (json[r'quality_tracks'] as Iterable)
                .cast<String>()
                .toList(growable: false)
            : const []!,
      );
    }
    return null;
  }

  static List<HLSSettingsResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <HLSSettingsResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = HLSSettingsResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'HLSSettingsResponse('
        'autoOn: $autoOn, '
        'enabled: $enabled, '
        'qualityTracks: $qualityTracks, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is HLSSettingsResponse &&
        other.autoOn == autoOn &&
        other.enabled == enabled &&
        other.qualityTracks == qualityTracks;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      autoOn,
      enabled,
      qualityTracks,
    ]);
  }
}
