// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'hls_settings_response.g.dart';
part 'hls_settings_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class HLSSettingsResponse with _$HLSSettingsResponse {
  const HLSSettingsResponse({
    required this.autoOn,
    required this.enabled,
    required this.qualityTracks,
  });

  @override
  final bool autoOn;

  @override
  final bool enabled;

  @override
  final List<String> qualityTracks;

  Map<String, dynamic> toJson() => _$HLSSettingsResponseToJson(this);

  static HLSSettingsResponse fromJson(Map<String, dynamic> json) =>
      _$HLSSettingsResponseFromJson(json);
}
