// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ingress_audio_encoding_options_request.g.dart';
part 'ingress_audio_encoding_options_request.freezed.dart';

extension type const IngressAudioEncodingOptionsRequestChannels._(String _)
    implements String {
  static const n1 = IngressAudioEncodingOptionsRequestChannels._('1');
  static const n2 = IngressAudioEncodingOptionsRequestChannels._('2');

  factory IngressAudioEncodingOptionsRequestChannels.fromJson(String json) =>
      IngressAudioEncodingOptionsRequestChannels._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class IngressAudioEncodingOptionsRequest
    with _$IngressAudioEncodingOptionsRequest {
  const IngressAudioEncodingOptionsRequest({
    required this.bitrate,
    required this.channels,
    this.enableDtx,
  });

  @override
  @JsonKey(name: 'bitrate')
  final int bitrate;

  @override
  @JsonKey(name: 'channels')
  final IngressAudioEncodingOptionsRequestChannels channels;

  @override
  @JsonKey(name: 'enable_dtx')
  final bool? enableDtx;

  Map<String, dynamic> toJson() =>
      _$IngressAudioEncodingOptionsRequestToJson(this);

  static IngressAudioEncodingOptionsRequest fromJson(
    Map<String, dynamic> json,
  ) => _$IngressAudioEncodingOptionsRequestFromJson(json);
}
