// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ingress_settings_response.g.dart';
part 'ingress_settings_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class IngressSettingsResponse with _$IngressSettingsResponse {
  const IngressSettingsResponse({
    this.audioEncodingOptions,
    required this.enabled,
    this.videoEncodingOptions,
  });

  @override
  final IngressAudioEncodingResponse? audioEncodingOptions;

  @override
  final bool enabled;

  @override
  final Map<String, IngressVideoEncodingResponse>? videoEncodingOptions;

  Map<String, dynamic> toJson() => _$IngressSettingsResponseToJson(this);

  static IngressSettingsResponse fromJson(Map<String, dynamic> json) =>
      _$IngressSettingsResponseFromJson(json);
}
