// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ingress_source_request.g.dart';
part 'ingress_source_request.freezed.dart';

extension type const IngressSourceRequestFps._(String _) implements String {
  static const n30 = IngressSourceRequestFps._('30');
  static const n60 = IngressSourceRequestFps._('60');

  factory IngressSourceRequestFps.fromJson(String json) =>
      IngressSourceRequestFps._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class IngressSourceRequest with _$IngressSourceRequest {
  const IngressSourceRequest({
    required this.fps,
    required this.height,
    required this.width,
  });

  @override
  @JsonKey(name: 'fps')
  final IngressSourceRequestFps fps;

  @override
  @JsonKey(name: 'height')
  final int height;

  @override
  @JsonKey(name: 'width')
  final int width;

  Map<String, dynamic> toJson() => _$IngressSourceRequestToJson(this);

  static IngressSourceRequest fromJson(Map<String, dynamic> json) =>
      _$IngressSourceRequestFromJson(json);
}
