// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ingress_error_event.g.dart';
part 'ingress_error_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class IngressErrorEvent extends core.WsEvent with _$IngressErrorEvent {
  const IngressErrorEvent({
    required this.callCid,
    this.code,
    required this.createdAt,
    required this.error,
    required this.ingressStreamId,
    required this.type,
    required this.userId,
  });

  @override
  @JsonKey(name: 'call_cid')
  final String callCid;

  @override
  @JsonKey(name: 'code')
  final String? code;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'error')
  final String error;

  @override
  @JsonKey(name: 'ingress_stream_id')
  final String ingressStreamId;

  @override
  @JsonKey(name: 'type')
  final String type;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  Map<String, dynamic> toJson() => _$IngressErrorEventToJson(this);

  static IngressErrorEvent fromJson(Map<String, dynamic> json) =>
      _$IngressErrorEventFromJson(json);
}
