// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ingress_video_encoding_response.g.dart';
part 'ingress_video_encoding_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class IngressVideoEncodingResponse with _$IngressVideoEncodingResponse {
  const IngressVideoEncodingResponse({
    required this.layers,
    required this.source,
  });

  @override
  final List<IngressVideoLayerResponse> layers;

  @override
  final IngressSourceResponse source;

  Map<String, dynamic> toJson() => _$IngressVideoEncodingResponseToJson(this);

  static IngressVideoEncodingResponse fromJson(Map<String, dynamic> json) =>
      _$IngressVideoEncodingResponseFromJson(json);
}
