// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ingress_video_layer_response.g.dart';
part 'ingress_video_layer_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class IngressVideoLayerResponse with _$IngressVideoLayerResponse {
  const IngressVideoLayerResponse({
    required this.bitrate,
    required this.codec,
    required this.frameRateLimit,
    required this.maxDimension,
    required this.minDimension,
  });

  @override
  final int bitrate;

  @override
  final String codec;

  @override
  final int frameRateLimit;

  @override
  final int maxDimension;

  @override
  final int minDimension;

  Map<String, dynamic> toJson() => _$IngressVideoLayerResponseToJson(this);

  static IngressVideoLayerResponse fromJson(Map<String, dynamic> json) =>
      _$IngressVideoLayerResponseFromJson(json);
}
