// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'ingress_source_request.g.dart';
part 'ingress_source_request.freezed.dart';

@JsonEnum(alwaysCreate: true)
enum IngressSourceRequestFps {
  @JsonValue('30')
  n30,
  @JsonValue('60')
  n60,
  @JsonValue('_unknown')
  unknown,
}

@freezed
@immutable
@JsonSerializable()
class IngressSourceRequest with _$IngressSourceRequest {
  const IngressSourceRequest({
    required this.fps,
    required this.height,
    required this.width,
  });

  @override
  @JsonKey(unknownEnumValue: IngressSourceRequestFps.unknown)
  final IngressSourceRequestFps fps;

  @override
  final int height;

  @override
  final int width;

  Map<String, dynamic> toJson() => _$IngressSourceRequestToJson(this);

  static IngressSourceRequest fromJson(Map<String, dynamic> json) =>
      _$IngressSourceRequestFromJson(json);
}
