// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'join_call_request.g.dart';
part 'join_call_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class JoinCallRequest with _$JoinCallRequest {
  const JoinCallRequest({
    this.create,
    this.data,
    this.e2ee,
    this.hintHighScaleLivestreamPublisher,
    required this.location,
    this.membersLimit,
    this.migratingFrom,
    this.migratingFromList,
    this.notify,
    this.ring,
    this.video,
  });

  @override
  @JsonKey(name: 'create')
  final bool? create;

  @override
  @JsonKey(name: 'data')
  final CallRequest? data;

  @override
  @JsonKey(name: 'e2ee')
  final bool? e2ee;

  @override
  @JsonKey(name: 'hint_high_scale_livestream_publisher')
  final bool? hintHighScaleLivestreamPublisher;

  @override
  @JsonKey(name: 'location')
  final String location;

  @override
  @JsonKey(name: 'members_limit')
  final int? membersLimit;

  @override
  @JsonKey(name: 'migrating_from')
  final String? migratingFrom;

  @override
  @JsonKey(name: 'migrating_from_list')
  final List<String>? migratingFromList;

  @override
  @JsonKey(name: 'notify')
  final bool? notify;

  @override
  @JsonKey(name: 'ring')
  final bool? ring;

  @override
  @JsonKey(name: 'video')
  final bool? video;

  Map<String, dynamic> toJson() => _$JoinCallRequestToJson(this);

  static JoinCallRequest fromJson(Map<String, dynamic> json) =>
      _$JoinCallRequestFromJson(json);
}
