// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'joins.g.dart';
part 'joins.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class Joins with _$Joins {
  const Joins({
    required this.disconnectReasons,
    required this.failureStages,
    this.joinAttempts,
    this.joinSuccessRate,
    required this.reason,
  });

  @override
  @JsonKey(name: 'disconnect_reasons')
  final Map<String, int> disconnectReasons;

  @override
  @JsonKey(name: 'failure_stages')
  final Map<String, int> failureStages;

  @override
  @JsonKey(name: 'join_attempts')
  final int? joinAttempts;

  @override
  @JsonKey(name: 'join_success_rate')
  final double? joinSuccessRate;

  @override
  @JsonKey(name: 'reason')
  final String reason;

  Map<String, dynamic> toJson() => _$JoinsToJson(this);

  static Joins fromJson(Map<String, dynamic> json) => _$JoinsFromJson(json);
}
