// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'keyframe_rule_parameters.g.dart';
part 'keyframe_rule_parameters.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class KeyframeRuleParameters with _$KeyframeRuleParameters {
  const KeyframeRuleParameters({
    this.harmLabels,
    this.minConfidence,
    this.threshold,
    this.timeWindow,
  });

  @override
  final List<String>? harmLabels;

  @override
  final double? minConfidence;

  @override
  final int? threshold;

  @override
  final String? timeWindow;

  Map<String, dynamic> toJson() => _$KeyframeRuleParametersToJson(this);

  static KeyframeRuleParameters fromJson(Map<String, dynamic> json) =>
      _$KeyframeRuleParametersFromJson(json);
}
