// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'layout_settings_request.g.dart';
part 'layout_settings_request.freezed.dart';

extension type const LayoutSettingsRequestName._(String _) implements String {
  static const custom = LayoutSettingsRequestName._('custom');
  static const grid = LayoutSettingsRequestName._('grid');
  static const mobile = LayoutSettingsRequestName._('mobile');
  static const singleParticipant = LayoutSettingsRequestName._(
    'single-participant',
  );
  static const spotlight = LayoutSettingsRequestName._('spotlight');

  factory LayoutSettingsRequestName.fromJson(String json) =>
      LayoutSettingsRequestName._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class LayoutSettingsRequest with _$LayoutSettingsRequest {
  const LayoutSettingsRequest({
    this.detectOrientation,
    this.externalAppUrl,
    this.externalCssUrl,
    required this.name,
    this.options,
  });

  @override
  @JsonKey(name: 'detect_orientation')
  final bool? detectOrientation;

  @override
  @JsonKey(name: 'external_app_url')
  final String? externalAppUrl;

  @override
  @JsonKey(name: 'external_css_url')
  final String? externalCssUrl;

  @override
  @JsonKey(name: 'name')
  final LayoutSettingsRequestName name;

  @override
  @JsonKey(name: 'options')
  final Map<String, Object?>? options;

  Map<String, dynamic> toJson() => _$LayoutSettingsRequestToJson(this);

  static LayoutSettingsRequest fromJson(Map<String, dynamic> json) =>
      _$LayoutSettingsRequestFromJson(json);
}
