// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'limits_settings_response.g.dart';
part 'limits_settings_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class LimitsSettingsResponse with _$LimitsSettingsResponse {
  const LimitsSettingsResponse({
    this.maxDurationSeconds,
    this.maxParticipants,
    this.maxParticipantsExcludeOwner,
    required this.maxParticipantsExcludeRoles,
  });

  @override
  final int? maxDurationSeconds;

  @override
  final int? maxParticipants;

  @override
  final bool? maxParticipantsExcludeOwner;

  @override
  final List<String> maxParticipantsExcludeRoles;

  Map<String, dynamic> toJson() => _$LimitsSettingsResponseToJson(this);

  static LimitsSettingsResponse fromJson(Map<String, dynamic> json) =>
      _$LimitsSettingsResponseFromJson(json);
}
