// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class LimitsSettingsResponse {
  const LimitsSettingsResponse({
    this.maxDurationSeconds,
    this.maxParticipants,
    this.maxParticipantsExcludeOwner,
    required this.maxParticipantsExcludeRoles,
  });

  final int? maxDurationSeconds;

  final int? maxParticipants;

  final bool? maxParticipantsExcludeOwner;

  final List<String> maxParticipantsExcludeRoles;

  Map<String, dynamic> toJson() {
    return {
      'max_duration_seconds': maxDurationSeconds,
      'max_participants': maxParticipants,
      'max_participants_exclude_owner': maxParticipantsExcludeOwner,
      'max_participants_exclude_roles': maxParticipantsExcludeRoles,
    };
  }

  static LimitsSettingsResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return LimitsSettingsResponse(
        maxDurationSeconds:
            mapValueOfType<int>(json, r'max_duration_seconds', null),
        maxParticipants: mapValueOfType<int>(json, r'max_participants', null),
        maxParticipantsExcludeOwner:
            mapValueOfType<bool>(json, r'max_participants_exclude_owner', null),
        maxParticipantsExcludeRoles:
            json[r'max_participants_exclude_roles'] is Iterable
                ? (json[r'max_participants_exclude_roles'] as Iterable)
                    .cast<String>()
                    .toList(growable: false)
                : const []!,
      );
    }
    return null;
  }

  static List<LimitsSettingsResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <LimitsSettingsResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = LimitsSettingsResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'LimitsSettingsResponse('
        'maxDurationSeconds: $maxDurationSeconds, '
        'maxParticipants: $maxParticipants, '
        'maxParticipantsExcludeOwner: $maxParticipantsExcludeOwner, '
        'maxParticipantsExcludeRoles: $maxParticipantsExcludeRoles, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is LimitsSettingsResponse &&
        other.maxDurationSeconds == maxDurationSeconds &&
        other.maxParticipants == maxParticipants &&
        other.maxParticipantsExcludeOwner == maxParticipantsExcludeOwner &&
        other.maxParticipantsExcludeRoles == maxParticipantsExcludeRoles;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      maxDurationSeconds,
      maxParticipants,
      maxParticipantsExcludeOwner,
      maxParticipantsExcludeRoles,
    ]);
  }
}
