// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'location_response.g.dart';
part 'location_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class LocationResponse with _$LocationResponse {
  const LocationResponse({
    required this.continentCode,
    required this.countryIsoCode,
    required this.subdivisionIsoCode,
  });

  @override
  @JsonKey(name: 'continent_code')
  final String continentCode;

  @override
  @JsonKey(name: 'country_iso_code')
  final String countryIsoCode;

  @override
  @JsonKey(name: 'subdivision_iso_code')
  final String subdivisionIsoCode;

  Map<String, dynamic> toJson() => _$LocationResponseToJson(this);

  static LocationResponse fromJson(Map<String, dynamic> json) =>
      _$LocationResponseFromJson(json);
}
