// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'member_response.g.dart';
part 'member_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MemberResponse with _$MemberResponse {
  const MemberResponse({
    required this.createdAt,
    required this.custom,
    this.deletedAt,
    this.role,
    required this.updatedAt,
    required this.user,
    required this.userId,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'created_at')
  final DateTime createdAt;

  @override
  @JsonKey(name: 'custom')
  final Map<String, Object?> custom;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'deleted_at')
  final DateTime? deletedAt;

  @override
  @JsonKey(name: 'role')
  final String? role;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'updated_at')
  final DateTime updatedAt;

  @override
  @JsonKey(name: 'user')
  final UserResponse user;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  Map<String, dynamic> toJson() => _$MemberResponseToJson(this);

  static MemberResponse fromJson(Map<String, dynamic> json) =>
      _$MemberResponseFromJson(json);
}
