// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class MemberResponse {
  const MemberResponse({
    required this.createdAt,
    required this.custom,
    this.deletedAt,
    this.role,
    required this.updatedAt,
    required this.user,
    required this.userId,
  });

  final DateTime createdAt;

  final Map<String, Object> custom;

  final DateTime? deletedAt;

  final String? role;

  final DateTime updatedAt;

  final UserResponse user;

  final String userId;

  Map<String, dynamic> toJson() {
    return {
      'created_at': createdAt,
      'custom': custom,
      'deleted_at': deletedAt,
      'role': role,
      'updated_at': updatedAt,
      'user': user,
      'user_id': userId,
    };
  }

  static MemberResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return MemberResponse(
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        custom: mapCastOfType<String, Object>(json, r'custom')!,
        deletedAt: mapValueOfType<DateTime>(json, r'deleted_at', null),
        role: mapValueOfType<String>(json, r'role', null),
        updatedAt: mapValueOfType<DateTime>(json, r'updated_at')!,
        user: UserResponse.fromJson(json[r'user'])!,
        userId: mapValueOfType<String>(json, r'user_id')!,
      );
    }
    return null;
  }

  static List<MemberResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <MemberResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = MemberResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'MemberResponse('
        'createdAt: $createdAt, '
        'custom: $custom, '
        'deletedAt: $deletedAt, '
        'role: $role, '
        'updatedAt: $updatedAt, '
        'user: $user, '
        'userId: $userId, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is MemberResponse &&
        other.createdAt == createdAt &&
        other.custom == custom &&
        other.deletedAt == deletedAt &&
        other.role == role &&
        other.updatedAt == updatedAt &&
        other.user == user &&
        other.userId == userId;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      createdAt,
      custom,
      deletedAt,
      role,
      updatedAt,
      user,
      userId,
    ]);
  }
}
