// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'metric_descriptor.g.dart';
part 'metric_descriptor.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class MetricDescriptor with _$MetricDescriptor {
  const MetricDescriptor({
    this.description,
    required this.label,
    this.unit,
  });

  @override
  final String? description;

  @override
  final String label;

  @override
  final String? unit;

  Map<String, dynamic> toJson() => _$MetricDescriptorToJson(this);

  static MetricDescriptor fromJson(Map<String, dynamic> json) =>
      _$MetricDescriptorFromJson(json);
}
