// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'moderation_payload_response.g.dart';
part 'moderation_payload_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ModerationPayloadResponse with _$ModerationPayloadResponse {
  const ModerationPayloadResponse({
    this.custom,
    this.images,
    this.texts,
    this.videos,
  });

  @override
  final Map<String, Object?>? custom;

  @override
  final List<String>? images;

  @override
  final List<String>? texts;

  @override
  final List<String>? videos;

  Map<String, dynamic> toJson() => _$ModerationPayloadResponseToJson(this);

  static ModerationPayloadResponse fromJson(Map<String, dynamic> json) =>
      _$ModerationPayloadResponseFromJson(json);
}
