// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'participant_series_timeframe.g.dart';
part 'participant_series_timeframe.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ParticipantSeriesTimeframe with _$ParticipantSeriesTimeframe {
  const ParticipantSeriesTimeframe({
    required this.maxPoints,
    required this.since,
    required this.stepSeconds,
    required this.until,
  });

  @override
  @JsonKey(name: 'max_points')
  final int maxPoints;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'since')
  final DateTime since;

  @override
  @JsonKey(name: 'step_seconds')
  final int stepSeconds;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'until')
  final DateTime until;

  Map<String, dynamic> toJson() => _$ParticipantSeriesTimeframeToJson(this);

  static ParticipantSeriesTimeframe fromJson(Map<String, dynamic> json) =>
      _$ParticipantSeriesTimeframeFromJson(json);
}
