// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'participant_series_subscriber_stats.g.dart';
part 'participant_series_subscriber_stats.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ParticipantSeriesSubscriberStats with _$ParticipantSeriesSubscriberStats {
  const ParticipantSeriesSubscriberStats({
    this.global,
    this.globalMeta,
    this.globalMetricsOrder,
    this.globalThresholds,
    this.subscriptions,
  });

  @override
  final Map<String, List<List<double>>>? global;

  @override
  final Map<String, MetricDescriptor>? globalMeta;

  @override
  final List<String>? globalMetricsOrder;

  @override
  final Map<String, List<MetricThreshold>>? globalThresholds;

  @override
  final List<ParticipantSeriesSubscriptionTrackMetrics>? subscriptions;

  Map<String, dynamic> toJson() =>
      _$ParticipantSeriesSubscriberStatsToJson(this);

  static ParticipantSeriesSubscriberStats fromJson(Map<String, dynamic> json) =>
      _$ParticipantSeriesSubscriberStatsFromJson(json);
}
