// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'participant_session_details.g.dart';
part 'participant_session_details.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ParticipantSessionDetails with _$ParticipantSessionDetails {
  const ParticipantSessionDetails({
    this.durationInSeconds,
    this.joinedAt,
    this.leftAt,
    required this.publisherType,
    required this.roles,
    required this.userId,
    required this.userSessionId,
  });

  @override
  @JsonKey(name: 'duration_in_seconds')
  final int? durationInSeconds;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'joined_at')
  final DateTime? joinedAt;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'left_at')
  final DateTime? leftAt;

  @override
  @JsonKey(name: 'publisher_type')
  final String publisherType;

  @override
  @JsonKey(name: 'roles')
  final List<String> roles;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  @override
  @JsonKey(name: 'user_session_id')
  final String userSessionId;

  Map<String, dynamic> toJson() => _$ParticipantSessionDetailsToJson(this);

  static ParticipantSessionDetails fromJson(Map<String, dynamic> json) =>
      _$ParticipantSessionDetailsFromJson(json);
}
