// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'per_sdk_usage_report.g.dart';
part 'per_sdk_usage_report.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class PerSDKUsageReport with _$PerSDKUsageReport {
  const PerSDKUsageReport({
    this.byVersion = const {},
    required this.total,
  });

  @override
  @JsonKey(defaultValue: {})
  final Map<String, int> byVersion;

  @override
  final int total;

  Map<String, dynamic> toJson() => _$PerSDKUsageReportToJson(this);

  static PerSDKUsageReport fromJson(Map<String, dynamic> json) =>
      _$PerSDKUsageReportFromJson(json);
}
