// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class PinResponse {
  const PinResponse({
    required this.duration,
  });

  final String duration;

  Map<String, dynamic> toJson() {
    return {
      'duration': duration,
    };
  }

  static PinResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return PinResponse(
        duration: mapValueOfType<String>(json, r'duration')!,
      );
    }
    return null;
  }

  static List<PinResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <PinResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = PinResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'PinResponse('
        'duration: $duration, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is PinResponse && other.duration == duration;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      duration,
    ]);
  }
}
