// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'poll_votes_response.g.dart';
part 'poll_votes_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class PollVotesResponse with _$PollVotesResponse {
  const PollVotesResponse({
    required this.duration,
    this.next,
    this.prev,
    required this.votes,
  });

  @override
  final String duration;

  @override
  final String? next;

  @override
  final String? prev;

  @override
  final List<PollVoteResponseData> votes;

  Map<String, dynamic> toJson() => _$PollVotesResponseToJson(this);

  static PollVotesResponse fromJson(Map<String, dynamic> json) =>
      _$PollVotesResponseFromJson(json);
}
