// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'poll_vote_response_data.g.dart';
part 'poll_vote_response_data.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class PollVoteResponseData with _$PollVoteResponseData {
  const PollVoteResponseData({
    this.answerText,
    required this.createdAt,
    required this.id,
    this.isAnswer,
    required this.optionId,
    required this.pollId,
    required this.updatedAt,
    this.user,
    this.userId,
  });

  @override
  final String? answerText;

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  final String id;

  @override
  final bool? isAnswer;

  @override
  final String optionId;

  @override
  final String pollId;

  @override
  @EpochDateTimeConverter()
  final DateTime updatedAt;

  @override
  final UserResponse? user;

  @override
  final String? userId;

  Map<String, dynamic> toJson() => _$PollVoteResponseDataToJson(this);

  static PollVoteResponseData fromJson(Map<String, dynamic> json) =>
      _$PollVoteResponseDataFromJson(json);
}
