// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'poor_by_cause.g.dart';
part 'poor_by_cause.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class PoorByCause with _$PoorByCause {
  const PoorByCause({
    required this.delivery,
    required this.edge,
    required this.isolatedLocal,
    required this.source,
    required this.unattributed,
  });

  @override
  @JsonKey(name: 'delivery')
  final int delivery;

  @override
  @JsonKey(name: 'edge')
  final int edge;

  @override
  @JsonKey(name: 'isolated_local')
  final int isolatedLocal;

  @override
  @JsonKey(name: 'source')
  final int source;

  @override
  @JsonKey(name: 'unattributed')
  final int unattributed;

  Map<String, dynamic> toJson() => _$PoorByCauseToJson(this);

  static PoorByCause fromJson(Map<String, dynamic> json) =>
      _$PoorByCauseFromJson(json);
}
