// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'poor_tail.g.dart';
part 'poor_tail.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class PoorTail with _$PoorTail {
  const PoorTail({
    this.healthyPct,
    required this.healthyViewers,
    required this.note,
    required this.poorByCause,
    required this.poorTotal,
    required this.supporting,
  });

  @override
  @JsonKey(name: 'healthy_pct')
  final double? healthyPct;

  @override
  @JsonKey(name: 'healthy_viewers')
  final int healthyViewers;

  @override
  @JsonKey(name: 'note')
  final String note;

  @override
  @JsonKey(name: 'poor_by_cause')
  final PoorByCause poorByCause;

  @override
  @JsonKey(name: 'poor_total')
  final int poorTotal;

  @override
  @JsonKey(name: 'supporting')
  final Supporting supporting;

  Map<String, dynamic> toJson() => _$PoorTailToJson(this);

  static PoorTail fromJson(Map<String, dynamic> json) =>
      _$PoorTailFromJson(json);
}
