// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'published_track_metrics.g.dart';
part 'published_track_metrics.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class PublishedTrackMetrics with _$PublishedTrackMetrics {
  const PublishedTrackMetrics({
    this.bitrate,
    this.codec,
    this.framerate,
    this.resolution,
    this.trackId,
    this.trackType,
    this.warnings,
  });

  @override
  @JsonKey(name: 'bitrate')
  final MetricTimeSeries? bitrate;

  @override
  @JsonKey(name: 'codec')
  final String? codec;

  @override
  @JsonKey(name: 'framerate')
  final MetricTimeSeries? framerate;

  @override
  @JsonKey(name: 'resolution')
  final ResolutionMetricsTimeSeries? resolution;

  @override
  @JsonKey(name: 'track_id')
  final String? trackId;

  @override
  @JsonKey(name: 'track_type')
  final String? trackType;

  @override
  @JsonKey(name: 'warnings')
  final List<SessionWarningResponse>? warnings;

  Map<String, dynamic> toJson() => _$PublishedTrackMetricsToJson(this);

  static PublishedTrackMetrics fromJson(Map<String, dynamic> json) =>
      _$PublishedTrackMetricsFromJson(json);
}
