// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'publisher_stats_response.g.dart';
part 'publisher_stats_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class PublisherStatsResponse with _$PublisherStatsResponse {
  const PublisherStatsResponse({
    this.byTrack,
    required this.total,
    required this.unique,
  });

  @override
  final List<TrackStatsResponse>? byTrack;

  @override
  final int total;

  @override
  final int unique;

  Map<String, dynamic> toJson() => _$PublisherStatsResponseToJson(this);

  static PublisherStatsResponse fromJson(Map<String, dynamic> json) =>
      _$PublisherStatsResponseFromJson(json);
}
