// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'quality.g.dart';
part 'quality.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class Quality with _$Quality {
  const Quality({
    required this.connectionAvgJitterMs,
    required this.connectionAvgLatencyMs,
    required this.interruptionIncidents,
    this.p50QualityScore,
    this.p5QualityScore,
    required this.scoreBandsByConnectionPct,
    required this.scoreBandsByWatchTimePct,
    required this.viewerInterruptionNote,
    this.viewerInterruptionRatePct,
  });

  @override
  @JsonKey(name: 'connection_avg_jitter_ms')
  final Percentiles connectionAvgJitterMs;

  @override
  @JsonKey(name: 'connection_avg_latency_ms')
  final Percentiles connectionAvgLatencyMs;

  @override
  @JsonKey(name: 'interruption_incidents')
  final List<Incident> interruptionIncidents;

  @override
  @JsonKey(name: 'p50_quality_score')
  final double? p50QualityScore;

  @override
  @JsonKey(name: 'p5_quality_score')
  final double? p5QualityScore;

  @override
  @JsonKey(name: 'score_bands_by_connection_pct')
  final ScoreBands scoreBandsByConnectionPct;

  @override
  @JsonKey(name: 'score_bands_by_watch_time_pct')
  final ScoreBands scoreBandsByWatchTimePct;

  @override
  @JsonKey(name: 'viewer_interruption_note')
  final String viewerInterruptionNote;

  @override
  @JsonKey(name: 'viewer_interruption_rate_pct')
  final double? viewerInterruptionRatePct;

  Map<String, dynamic> toJson() => _$QualityToJson(this);

  static Quality fromJson(Map<String, dynamic> json) => _$QualityFromJson(json);
}
