// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_aggregate_call_stats_response.g.dart';
part 'query_aggregate_call_stats_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryAggregateCallStatsResponse with _$QueryAggregateCallStatsResponse {
  const QueryAggregateCallStatsResponse({
    this.callDurationReport,
    this.callParticipantCountReport,
    this.callsPerDayReport,
    required this.duration,
    this.networkMetricsReport,
    this.qualityScoreReport,
    this.sdkUsageReport,
    this.userFeedbackReport,
  });

  @override
  @JsonKey(name: 'call_duration_report')
  final CallDurationReportResponse? callDurationReport;

  @override
  @JsonKey(name: 'call_participant_count_report')
  final CallParticipantCountReportResponse? callParticipantCountReport;

  @override
  @JsonKey(name: 'calls_per_day_report')
  final CallsPerDayReportResponse? callsPerDayReport;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'network_metrics_report')
  final NetworkMetricsReportResponse? networkMetricsReport;

  @override
  @JsonKey(name: 'quality_score_report')
  final QualityScoreReportResponse? qualityScoreReport;

  @override
  @JsonKey(name: 'sdk_usage_report')
  final SDKUsageReportResponse? sdkUsageReport;

  @override
  @JsonKey(name: 'user_feedback_report')
  final UserFeedbackReportResponse? userFeedbackReport;

  Map<String, dynamic> toJson() =>
      _$QueryAggregateCallStatsResponseToJson(this);

  static QueryAggregateCallStatsResponse fromJson(Map<String, dynamic> json) =>
      _$QueryAggregateCallStatsResponseFromJson(json);
}
