// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class QueryCallParticipantsResponse {
  const QueryCallParticipantsResponse({
    required this.call,
    required this.duration,
    required this.members,
    this.membership,
    required this.ownCapabilities,
    required this.participants,
    required this.totalParticipants,
  });

  final CallResponse call;

  final String duration;

  final List<MemberResponse> members;

  final MemberResponse? membership;

  final List<OwnCapability> ownCapabilities;

  final List<CallParticipantResponse> participants;

  final int totalParticipants;

  Map<String, dynamic> toJson() {
    return {
      'call': call,
      'duration': duration,
      'members': members,
      'membership': membership,
      'own_capabilities': ownCapabilities,
      'participants': participants,
      'total_participants': totalParticipants,
    };
  }

  static QueryCallParticipantsResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return QueryCallParticipantsResponse(
        call: CallResponse.fromJson(json[r'call'])!,
        duration: mapValueOfType<String>(json, r'duration')!,
        members: MemberResponse.listFromJson(json[r'members'])!,
        membership: MemberResponse.fromJson(json[r'membership'] ?? null),
        ownCapabilities: OwnCapability.listFromJson(json[r'own_capabilities'])!,
        participants:
            CallParticipantResponse.listFromJson(json[r'participants'])!,
        totalParticipants: mapValueOfType<int>(json, r'total_participants')!,
      );
    }
    return null;
  }

  static List<QueryCallParticipantsResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <QueryCallParticipantsResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = QueryCallParticipantsResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'QueryCallParticipantsResponse('
        'call: $call, '
        'duration: $duration, '
        'members: $members, '
        'membership: $membership, '
        'ownCapabilities: $ownCapabilities, '
        'participants: $participants, '
        'totalParticipants: $totalParticipants, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is QueryCallParticipantsResponse &&
        other.call == call &&
        other.duration == duration &&
        other.members == members &&
        other.membership == membership &&
        other.ownCapabilities == ownCapabilities &&
        other.participants == participants &&
        other.totalParticipants == totalParticipants;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      call,
      duration,
      members,
      membership,
      ownCapabilities,
      participants,
      totalParticipants,
    ]);
  }
}
