// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_call_session_participant_stats_response.g.dart';
part 'query_call_session_participant_stats_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryCallSessionParticipantStatsResponse
    with _$QueryCallSessionParticipantStatsResponse {
  const QueryCallSessionParticipantStatsResponse({
    this.callEndedAt,
    this.callEvents,
    required this.callId,
    required this.callSessionId,
    this.callStartedAt,
    required this.callType,
    required this.counts,
    required this.duration,
    this.next,
    required this.participants,
    this.prev,
    this.tmpDataSource,
  });

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'call_ended_at')
  final DateTime? callEndedAt;

  @override
  @JsonKey(name: 'call_events')
  final List<CallLevelEventPayload>? callEvents;

  @override
  @JsonKey(name: 'call_id')
  final String callId;

  @override
  @JsonKey(name: 'call_session_id')
  final String callSessionId;

  @override
  @StreamDateTimeConverter()
  @JsonKey(name: 'call_started_at')
  final DateTime? callStartedAt;

  @override
  @JsonKey(name: 'call_type')
  final String callType;

  @override
  @JsonKey(name: 'counts')
  final CallStatsParticipantCounts counts;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'next')
  final String? next;

  @override
  @JsonKey(name: 'participants')
  final List<CallStatsParticipant> participants;

  @override
  @JsonKey(name: 'prev')
  final String? prev;

  @override
  @JsonKey(name: 'tmp_data_source')
  final String? tmpDataSource;

  Map<String, dynamic> toJson() =>
      _$QueryCallSessionParticipantStatsResponseToJson(this);

  static QueryCallSessionParticipantStatsResponse fromJson(
    Map<String, dynamic> json,
  ) => _$QueryCallSessionParticipantStatsResponseFromJson(json);
}
