// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class QueryCallParticipantsRequest {
  const QueryCallParticipantsRequest({
    this.filterConditions,
  });

  final Map<String, Object>? filterConditions;

  Map<String, dynamic> toJson() {
    return {
      'filter_conditions': filterConditions,
    };
  }

  static QueryCallParticipantsRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return QueryCallParticipantsRequest(
        filterConditions:
            mapCastOfType<String, Object>(json, r'filter_conditions'),
      );
    }
    return null;
  }

  static List<QueryCallParticipantsRequest> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <QueryCallParticipantsRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = QueryCallParticipantsRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'QueryCallParticipantsRequest('
        'filterConditions: $filterConditions, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is QueryCallParticipantsRequest &&
        other.filterConditions == filterConditions;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      filterConditions,
    ]);
  }
}
