// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_call_members_response.g.dart';
part 'query_call_members_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryCallMembersResponse with _$QueryCallMembersResponse {
  const QueryCallMembersResponse({
    required this.duration,
    required this.members,
    this.next,
    this.prev,
  });

  @override
  final String duration;

  @override
  final List<MemberResponse> members;

  @override
  final String? next;

  @override
  final String? prev;

  Map<String, dynamic> toJson() => _$QueryCallMembersResponseToJson(this);

  static QueryCallMembersResponse fromJson(Map<String, dynamic> json) =>
      _$QueryCallMembersResponseFromJson(json);
}
