// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_call_stats_request.g.dart';
part 'query_call_stats_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryCallStatsRequest with _$QueryCallStatsRequest {
  const QueryCallStatsRequest({
    this.filterConditions,
    this.limit,
    this.next,
    this.prev,
    this.sort,
  });

  @override
  final Map<String, Object?>? filterConditions;

  @override
  final int? limit;

  @override
  final String? next;

  @override
  final String? prev;

  @override
  final List<SortParamRequest>? sort;

  Map<String, dynamic> toJson() => _$QueryCallStatsRequestToJson(this);

  static QueryCallStatsRequest fromJson(Map<String, dynamic> json) =>
      _$QueryCallStatsRequestFromJson(json);
}
