// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class QueryCallMembersResponse {
  const QueryCallMembersResponse({
    required this.duration,
    required this.members,
    this.next,
    this.prev,
  });

  final String duration;

  final List<MemberResponse> members;

  final String? next;

  final String? prev;

  Map<String, dynamic> toJson() {
    return {
      'duration': duration,
      'members': members,
      'next': next,
      'prev': prev,
    };
  }

  static QueryCallMembersResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return QueryCallMembersResponse(
        duration: mapValueOfType<String>(json, r'duration')!,
        members: MemberResponse.listFromJson(json[r'members'])!,
        next: mapValueOfType<String?>(json, r'next', null),
        prev: mapValueOfType<String?>(json, r'prev', null),
      );
    }
    return null;
  }

  static List<QueryCallMembersResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <QueryCallMembersResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = QueryCallMembersResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'QueryCallMembersResponse('
        'duration: $duration, '
        'members: $members, '
        'next: $next, '
        'prev: $prev, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is QueryCallMembersResponse &&
        other.duration == duration &&
        other.members == members &&
        other.next == next &&
        other.prev == prev;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      duration,
      members,
      next,
      prev,
    ]);
  }
}
