// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'query_review_queue_response.g.dart';
part 'query_review_queue_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class QueryReviewQueueResponse with _$QueryReviewQueueResponse {
  const QueryReviewQueueResponse({
    this.actionConfig = const {},
    this.defaultActionConfig,
    required this.duration,
    this.filterConfig,
    this.items = const [],
    this.next,
    this.prev,
    this.stats = const {},
  });

  @override
  @JsonKey(defaultValue: {})
  final Map<String, List<ModerationActionConfigResponse>> actionConfig;

  @override
  final Map<String, List<ModerationActionConfigResponse>>? defaultActionConfig;

  @override
  final String duration;

  @override
  final FilterConfigResponse? filterConfig;

  @override
  @JsonKey(defaultValue: [])
  final List<ReviewQueueItemResponse> items;

  @override
  final String? next;

  @override
  final String? prev;

  @override
  @JsonKey(defaultValue: {})
  final Map<String, Object?> stats;

  Map<String, dynamic> toJson() => _$QueryReviewQueueResponseToJson(this);

  static QueryReviewQueueResponse fromJson(Map<String, dynamic> json) =>
      _$QueryReviewQueueResponseFromJson(json);
}
