// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'raw_recording_settings_response.g.dart';
part 'raw_recording_settings_response.freezed.dart';

extension type const RawRecordingSettingsResponseMode._(String _)
    implements String {
  static const autoOn = RawRecordingSettingsResponseMode._('auto-on');
  static const available = RawRecordingSettingsResponseMode._('available');
  static const disabled = RawRecordingSettingsResponseMode._('disabled');

  factory RawRecordingSettingsResponseMode.fromJson(String json) =>
      RawRecordingSettingsResponseMode._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class RawRecordingSettingsResponse with _$RawRecordingSettingsResponse {
  const RawRecordingSettingsResponse({
    this.audioOnly,
    required this.mode,
  });

  @override
  @JsonKey(name: 'audio_only')
  final bool? audioOnly;

  @override
  @JsonKey(name: 'mode')
  final RawRecordingSettingsResponseMode mode;

  Map<String, dynamic> toJson() => _$RawRecordingSettingsResponseToJson(this);

  static RawRecordingSettingsResponse fromJson(Map<String, dynamic> json) =>
      _$RawRecordingSettingsResponseFromJson(json);
}
