// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class ReactionResponse {
  const ReactionResponse({
    this.custom,
    this.emojiCode,
    required this.type,
    required this.user,
  });

  final Map<String, Object>? custom;

  final String? emojiCode;

  final String type;

  final UserResponse user;

  Map<String, dynamic> toJson() {
    return {
      'custom': custom,
      'emoji_code': emojiCode,
      'type': type,
      'user': user,
    };
  }

  static ReactionResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return ReactionResponse(
        custom: mapCastOfType<String, Object>(json, r'custom'),
        emojiCode: mapValueOfType<String?>(json, r'emoji_code', null),
        type: mapValueOfType<String>(json, r'type')!,
        user: UserResponse.fromJson(json[r'user'])!,
      );
    }
    return null;
  }

  static List<ReactionResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <ReactionResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = ReactionResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'ReactionResponse('
        'custom: $custom, '
        'emojiCode: $emojiCode, '
        'type: $type, '
        'user: $user, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ReactionResponse &&
        other.custom == custom &&
        other.emojiCode == emojiCode &&
        other.type == type &&
        other.user == user;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      custom,
      emojiCode,
      type,
      user,
    ]);
  }
}
