// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class RecordSettingsResponse {
  const RecordSettingsResponse({
    required this.audioOnly,
    required this.mode,
    required this.quality,
  });

  final bool audioOnly;

  final String mode;

  final String quality;

  Map<String, dynamic> toJson() {
    return {
      'audio_only': audioOnly,
      'mode': mode,
      'quality': quality,
    };
  }

  static RecordSettingsResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return RecordSettingsResponse(
        audioOnly: mapValueOfType<bool>(json, r'audio_only')!,
        mode: mapValueOfType<String>(json, r'mode')!,
        quality: mapValueOfType<String>(json, r'quality')!,
      );
    }
    return null;
  }

  static List<RecordSettingsResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <RecordSettingsResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = RecordSettingsResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'RecordSettingsResponse('
        'audioOnly: $audioOnly, '
        'mode: $mode, '
        'quality: $quality, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is RecordSettingsResponse &&
        other.audioOnly == audioOnly &&
        other.mode == mode &&
        other.quality == quality;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      audioOnly,
      mode,
      quality,
    ]);
  }
}
