// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class RejectCallRequest {
  const RejectCallRequest({
    this.reason,
  });

  final String? reason;

  Map<String, dynamic> toJson() {
    return {
      'reason': reason,
    };
  }

  static RejectCallRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return RejectCallRequest(
        reason: mapValueOfType<String?>(json, r'reason', null),
      );
    }
    return null;
  }

  static List<RejectCallRequest> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <RejectCallRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = RejectCallRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'RejectCallRequest('
        'reason: $reason, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is RejectCallRequest && other.reason == reason;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      reason,
    ]);
  }
}
