// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'reject_call_request.g.dart';
part 'reject_call_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class RejectCallRequest with _$RejectCallRequest {
  const RejectCallRequest({
    this.reason,
  });

  @override
  final String? reason;

  Map<String, dynamic> toJson() => _$RejectCallRequestToJson(this);

  static RejectCallRequest fromJson(Map<String, dynamic> json) =>
      _$RejectCallRequestFromJson(json);
}
