// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'report_by_histogram_bucket.g.dart';
part 'report_by_histogram_bucket.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ReportByHistogramBucket with _$ReportByHistogramBucket {
  const ReportByHistogramBucket({
    required this.category,
    required this.count,
    this.lowerBound,
    required this.sum,
    this.upperBound,
  });

  @override
  final String category;

  @override
  final int count;

  @override
  final Bound? lowerBound;

  @override
  final double sum;

  @override
  final Bound? upperBound;

  Map<String, dynamic> toJson() => _$ReportByHistogramBucketToJson(this);

  static ReportByHistogramBucket fromJson(Map<String, dynamic> json) =>
      _$ReportByHistogramBucketFromJson(json);
}
