// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'request_permission_request.g.dart';
part 'request_permission_request.freezed.dart';

@JsonEnum(alwaysCreate: true)
enum RequestPermissionRequestPermissions {
  @JsonValue('screenshare')
  screenshare,
  @JsonValue('send-audio')
  sendAudio,
  @JsonValue('send-video')
  sendVideo,
  @JsonValue('_unknown')
  unknown,
}

@freezed
@immutable
@JsonSerializable()
class RequestPermissionRequest with _$RequestPermissionRequest {
  const RequestPermissionRequest({
    required this.permissions,
  });

  @override
  @JsonKey(
    unknownEnumValue: RequestPermissionRequestPermissions.unknown,
    defaultValue: [],
  )
  final List<RequestPermissionRequestPermissions> permissions;

  Map<String, dynamic> toJson() => _$RequestPermissionRequestToJson(this);

  static RequestPermissionRequest fromJson(Map<String, dynamic> json) =>
      _$RequestPermissionRequestFromJson(json);
}
