// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'resolve_sip_inbound_response.g.dart';
part 'resolve_sip_inbound_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class ResolveSipInboundResponse with _$ResolveSipInboundResponse {
  const ResolveSipInboundResponse({
    required this.credentials,
    required this.duration,
    this.sipRoutingRule,
    this.sipTrunk,
  });

  @override
  @JsonKey(name: 'credentials')
  final SipInboundCredentials credentials;

  @override
  @JsonKey(name: 'duration')
  final String duration;

  @override
  @JsonKey(name: 'sip_routing_rule')
  final SIPInboundRoutingRuleResponse? sipRoutingRule;

  @override
  @JsonKey(name: 'sip_trunk')
  final SIPTrunkResponse? sipTrunk;

  Map<String, dynamic> toJson() => _$ResolveSipInboundResponseToJson(this);

  static ResolveSipInboundResponse fromJson(Map<String, dynamic> json) =>
      _$ResolveSipInboundResponseFromJson(json);
}
