// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class RTMPSettingsResponse {
  const RTMPSettingsResponse({
    required this.enabled,
    required this.quality,
  });

  final bool enabled;

  final String quality;

  Map<String, dynamic> toJson() {
    return {
      'enabled': enabled,
      'quality': quality,
    };
  }

  static RTMPSettingsResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return RTMPSettingsResponse(
        enabled: mapValueOfType<bool>(json, r'enabled')!,
        quality: mapValueOfType<String>(json, r'quality')!,
      );
    }
    return null;
  }

  static List<RTMPSettingsResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <RTMPSettingsResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = RTMPSettingsResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'RTMPSettingsResponse('
        'enabled: $enabled, '
        'quality: $quality, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is RTMPSettingsResponse &&
        other.enabled == enabled &&
        other.quality == quality;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      enabled,
      quality,
    ]);
  }
}
