// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'rtmp_broadcast_request.g.dart';
part 'rtmp_broadcast_request.freezed.dart';

extension type const RTMPBroadcastRequestQuality._(String _) implements String {
  static const n1080p = RTMPBroadcastRequestQuality._('1080p');
  static const n1440p = RTMPBroadcastRequestQuality._('1440p');
  static const n360p = RTMPBroadcastRequestQuality._('360p');
  static const n480p = RTMPBroadcastRequestQuality._('480p');
  static const n720p = RTMPBroadcastRequestQuality._('720p');
  static const portrait1080x1920 = RTMPBroadcastRequestQuality._(
    'portrait-1080x1920',
  );
  static const portrait1440x2560 = RTMPBroadcastRequestQuality._(
    'portrait-1440x2560',
  );
  static const portrait360x640 = RTMPBroadcastRequestQuality._(
    'portrait-360x640',
  );
  static const portrait480x854 = RTMPBroadcastRequestQuality._(
    'portrait-480x854',
  );
  static const portrait720x1280 = RTMPBroadcastRequestQuality._(
    'portrait-720x1280',
  );

  factory RTMPBroadcastRequestQuality.fromJson(String json) =>
      RTMPBroadcastRequestQuality._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class RTMPBroadcastRequest with _$RTMPBroadcastRequest {
  const RTMPBroadcastRequest({
    this.layout,
    required this.name,
    this.quality,
    this.streamKey,
    required this.streamUrl,
  });

  @override
  @JsonKey(name: 'layout')
  final LayoutSettingsRequest? layout;

  @override
  @JsonKey(name: 'name')
  final String name;

  @override
  @JsonKey(name: 'quality')
  final RTMPBroadcastRequestQuality? quality;

  @override
  @JsonKey(name: 'stream_key')
  final String? streamKey;

  @override
  @JsonKey(name: 'stream_url')
  final String streamUrl;

  Map<String, dynamic> toJson() => _$RTMPBroadcastRequestToJson(this);

  static RTMPBroadcastRequest fromJson(Map<String, dynamic> json) =>
      _$RTMPBroadcastRequestFromJson(json);
}
