// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'send_video_reaction_request.g.dart';
part 'send_video_reaction_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SendVideoReactionRequest with _$SendVideoReactionRequest {
  const SendVideoReactionRequest({
    this.custom,
    this.emojiCode,
    required this.type,
  });

  @override
  final Map<String, Object?>? custom;

  @override
  final String? emojiCode;

  @override
  final String type;

  Map<String, dynamic> toJson() => _$SendVideoReactionRequestToJson(this);

  static SendVideoReactionRequest fromJson(Map<String, dynamic> json) =>
      _$SendVideoReactionRequestFromJson(json);
}
