// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class SendReactionResponse {
  const SendReactionResponse({
    required this.duration,
    required this.reaction,
  });

  final String duration;

  final ReactionResponse reaction;

  Map<String, dynamic> toJson() {
    return {
      'duration': duration,
      'reaction': reaction,
    };
  }

  static SendReactionResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return SendReactionResponse(
        duration: mapValueOfType<String>(json, r'duration')!,
        reaction: ReactionResponse.fromJson(json[r'reaction'])!,
      );
    }
    return null;
  }

  static List<SendReactionResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <SendReactionResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = SendReactionResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'SendReactionResponse('
        'duration: $duration, '
        'reaction: $reaction, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is SendReactionResponse &&
        other.duration == duration &&
        other.reaction == reaction;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      duration,
      reaction,
    ]);
  }
}
