// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class SessionSettingsRequest {
  const SessionSettingsRequest({
    required this.inactivityTimeoutSeconds,
  });

  final int inactivityTimeoutSeconds;

  Map<String, dynamic> toJson() {
    return {
      'inactivity_timeout_seconds': inactivityTimeoutSeconds,
    };
  }

  static SessionSettingsRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return SessionSettingsRequest(
        inactivityTimeoutSeconds:
            mapValueOfType<int>(json, r'inactivity_timeout_seconds')!,
      );
    }
    return null;
  }

  static List<SessionSettingsRequest> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <SessionSettingsRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = SessionSettingsRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'SessionSettingsRequest('
        'inactivityTimeoutSeconds: $inactivityTimeoutSeconds, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is SessionSettingsRequest &&
        other.inactivityTimeoutSeconds == inactivityTimeoutSeconds;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      inactivityTimeoutSeconds,
    ]);
  }
}
