// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'sfu_response.g.dart';
part 'sfu_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SFUResponse with _$SFUResponse {
  const SFUResponse({
    required this.edgeName,
    required this.url,
    required this.wsEndpoint,
  });

  @override
  @JsonKey(name: 'edge_name')
  final String edgeName;

  @override
  @JsonKey(name: 'url')
  final String url;

  @override
  @JsonKey(name: 'ws_endpoint')
  final String wsEndpoint;

  Map<String, dynamic> toJson() => _$SFUResponseToJson(this);

  static SFUResponse fromJson(Map<String, dynamic> json) =>
      _$SFUResponseFromJson(json);
}
