// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'shared_location_response.g.dart';
part 'shared_location_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SharedLocationResponse with _$SharedLocationResponse {
  const SharedLocationResponse({
    this.channel,
    required this.channelCid,
    required this.createdAt,
    required this.createdByDeviceId,
    required this.duration,
    this.endAt,
    required this.latitude,
    required this.longitude,
    this.message,
    required this.messageId,
    required this.updatedAt,
    required this.userId,
  });

  @override
  final ChannelResponse? channel;

  @override
  final String channelCid;

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  final String createdByDeviceId;

  @override
  final String duration;

  @override
  @EpochDateTimeConverter()
  final DateTime? endAt;

  @override
  final double latitude;

  @override
  final double longitude;

  @override
  final MessageResponse? message;

  @override
  final String messageId;

  @override
  @EpochDateTimeConverter()
  final DateTime updatedAt;

  @override
  final String userId;

  Map<String, dynamic> toJson() => _$SharedLocationResponseToJson(this);

  static SharedLocationResponse fromJson(Map<String, dynamic> json) =>
      _$SharedLocationResponseFromJson(json);
}
