// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'sip_inbound_routing_rule_pin_configs_response.g.dart';
part 'sip_inbound_routing_rule_pin_configs_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SIPInboundRoutingRulePinConfigsResponse
    with _$SIPInboundRoutingRulePinConfigsResponse {
  const SIPInboundRoutingRulePinConfigsResponse({
    this.customWebhookUrl,
    this.pinFailedAttemptPrompt,
    this.pinHangupPrompt,
    this.pinPrompt,
    this.pinSuccessPrompt,
  });

  @override
  final String? customWebhookUrl;

  @override
  final String? pinFailedAttemptPrompt;

  @override
  final String? pinHangupPrompt;

  @override
  final String? pinPrompt;

  @override
  final String? pinSuccessPrompt;

  Map<String, dynamic> toJson() =>
      _$SIPInboundRoutingRulePinConfigsResponseToJson(this);

  static SIPInboundRoutingRulePinConfigsResponse fromJson(
    Map<String, dynamic> json,
  ) => _$SIPInboundRoutingRulePinConfigsResponseFromJson(json);
}
