// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'sip_challenge_request.g.dart';
part 'sip_challenge_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SIPChallengeRequest with _$SIPChallengeRequest {
  const SIPChallengeRequest({
    this.a1,
    this.algorithm,
    this.charset,
    this.cnonce,
    this.domain,
    this.method,
    this.nc,
    this.nonce,
    this.opaque,
    this.qop,
    this.realm,
    this.response,
    this.stale,
    this.uri,
    this.userhash,
    this.username,
  });

  @override
  final String? a1;

  @override
  final String? algorithm;

  @override
  final String? charset;

  @override
  final String? cnonce;

  @override
  final List<String>? domain;

  @override
  final String? method;

  @override
  final String? nc;

  @override
  final String? nonce;

  @override
  final String? opaque;

  @override
  final List<String>? qop;

  @override
  final String? realm;

  @override
  final String? response;

  @override
  final bool? stale;

  @override
  final String? uri;

  @override
  final bool? userhash;

  @override
  final String? username;

  Map<String, dynamic> toJson() => _$SIPChallengeRequestToJson(this);

  static SIPChallengeRequest fromJson(Map<String, dynamic> json) =>
      _$SIPChallengeRequestFromJson(json);
}
