// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'speech_segment_config.g.dart';
part 'speech_segment_config.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SpeechSegmentConfig with _$SpeechSegmentConfig {
  const SpeechSegmentConfig({
    this.maxSpeechCaptionMs,
    this.silenceDurationMs,
  });

  @override
  final int? maxSpeechCaptionMs;

  @override
  final int? silenceDurationMs;

  Map<String, dynamic> toJson() => _$SpeechSegmentConfigToJson(this);

  static SpeechSegmentConfig fromJson(Map<String, dynamic> json) =>
      _$SpeechSegmentConfigFromJson(json);
}
