// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'start_rtmp_broadcasts_request.g.dart';
part 'start_rtmp_broadcasts_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class StartRTMPBroadcastsRequest with _$StartRTMPBroadcastsRequest {
  const StartRTMPBroadcastsRequest({
    this.broadcasts = const [],
  });

  @override
  @JsonKey(defaultValue: [])
  final List<RTMPBroadcastRequest> broadcasts;

  Map<String, dynamic> toJson() => _$StartRTMPBroadcastsRequestToJson(this);

  static StartRTMPBroadcastsRequest fromJson(Map<String, dynamic> json) =>
      _$StartRTMPBroadcastsRequestFromJson(json);
}
