// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'start_closed_captions_request.g.dart';
part 'start_closed_captions_request.freezed.dart';

@JsonEnum(alwaysCreate: true)
enum StartClosedCaptionsRequestLanguage {
  @JsonValue('ar')
  ar,
  @JsonValue('auto')
  auto,
  @JsonValue('bg')
  bg,
  @JsonValue('ca')
  ca,
  @JsonValue('cs')
  cs,
  @JsonValue('da')
  da,
  @JsonValue('de')
  de,
  @JsonValue('el')
  el,
  @JsonValue('en')
  en,
  @JsonValue('es')
  es,
  @JsonValue('et')
  et,
  @JsonValue('fi')
  fi,
  @JsonValue('fr')
  fr,
  @JsonValue('he')
  he,
  @JsonValue('hi')
  hi,
  @JsonValue('hr')
  hr,
  @JsonValue('hu')
  hu,
  @JsonValue('id')
  id,
  @JsonValue('it')
  it,
  @JsonValue('ja')
  ja,
  @JsonValue('ko')
  ko,
  @JsonValue('ms')
  ms,
  @JsonValue('nl')
  nl,
  @JsonValue('no')
  no,
  @JsonValue('pl')
  pl,
  @JsonValue('pt')
  pt,
  @JsonValue('ro')
  ro,
  @JsonValue('ru')
  ru,
  @JsonValue('sk')
  sk,
  @JsonValue('sl')
  sl,
  @JsonValue('sv')
  sv,
  @JsonValue('ta')
  ta,
  @JsonValue('th')
  th,
  @JsonValue('tl')
  tl,
  @JsonValue('tr')
  tr,
  @JsonValue('uk')
  uk,
  @JsonValue('zh')
  zh,
  @JsonValue('_unknown')
  unknown,
}

@freezed
@immutable
@JsonSerializable()
class StartClosedCaptionsRequest with _$StartClosedCaptionsRequest {
  const StartClosedCaptionsRequest({
    this.enableTranscription,
    this.externalStorage,
    this.language,
    this.speechSegmentConfig,
  });

  @override
  final bool? enableTranscription;

  @override
  final String? externalStorage;

  @override
  @JsonKey(unknownEnumValue: StartClosedCaptionsRequestLanguage.unknown)
  final StartClosedCaptionsRequestLanguage? language;

  @override
  final SpeechSegmentConfig? speechSegmentConfig;

  Map<String, dynamic> toJson() => _$StartClosedCaptionsRequestToJson(this);

  static StartClosedCaptionsRequest fromJson(Map<String, dynamic> json) =>
      _$StartClosedCaptionsRequestFromJson(json);
}
