// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'start_hls_broadcasting_response.g.dart';
part 'start_hls_broadcasting_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class StartHLSBroadcastingResponse with _$StartHLSBroadcastingResponse {
  const StartHLSBroadcastingResponse({
    required this.duration,
    required this.playlistUrl,
  });

  @override
  final String duration;

  @override
  final String playlistUrl;

  Map<String, dynamic> toJson() => _$StartHLSBroadcastingResponseToJson(this);

  static StartHLSBroadcastingResponse fromJson(Map<String, dynamic> json) =>
      _$StartHLSBroadcastingResponseFromJson(json);
}
