// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'start_transcription_request.g.dart';
part 'start_transcription_request.freezed.dart';

extension type const StartTranscriptionRequestLanguage._(String _)
    implements String {
  static const ar = StartTranscriptionRequestLanguage._('ar');
  static const auto = StartTranscriptionRequestLanguage._('auto');
  static const bg = StartTranscriptionRequestLanguage._('bg');
  static const ca = StartTranscriptionRequestLanguage._('ca');
  static const cs = StartTranscriptionRequestLanguage._('cs');
  static const da = StartTranscriptionRequestLanguage._('da');
  static const de = StartTranscriptionRequestLanguage._('de');
  static const el = StartTranscriptionRequestLanguage._('el');
  static const en = StartTranscriptionRequestLanguage._('en');
  static const es = StartTranscriptionRequestLanguage._('es');
  static const et = StartTranscriptionRequestLanguage._('et');
  static const fi = StartTranscriptionRequestLanguage._('fi');
  static const fr = StartTranscriptionRequestLanguage._('fr');
  static const he = StartTranscriptionRequestLanguage._('he');
  static const hi = StartTranscriptionRequestLanguage._('hi');
  static const hr = StartTranscriptionRequestLanguage._('hr');
  static const hu = StartTranscriptionRequestLanguage._('hu');
  static const id = StartTranscriptionRequestLanguage._('id');
  static const it = StartTranscriptionRequestLanguage._('it');
  static const ja = StartTranscriptionRequestLanguage._('ja');
  static const ko = StartTranscriptionRequestLanguage._('ko');
  static const ms = StartTranscriptionRequestLanguage._('ms');
  static const nl = StartTranscriptionRequestLanguage._('nl');
  static const no = StartTranscriptionRequestLanguage._('no');
  static const pl = StartTranscriptionRequestLanguage._('pl');
  static const pt = StartTranscriptionRequestLanguage._('pt');
  static const ro = StartTranscriptionRequestLanguage._('ro');
  static const ru = StartTranscriptionRequestLanguage._('ru');
  static const sk = StartTranscriptionRequestLanguage._('sk');
  static const sl = StartTranscriptionRequestLanguage._('sl');
  static const sv = StartTranscriptionRequestLanguage._('sv');
  static const ta = StartTranscriptionRequestLanguage._('ta');
  static const th = StartTranscriptionRequestLanguage._('th');
  static const tl = StartTranscriptionRequestLanguage._('tl');
  static const tr = StartTranscriptionRequestLanguage._('tr');
  static const uk = StartTranscriptionRequestLanguage._('uk');
  static const zh = StartTranscriptionRequestLanguage._('zh');

  factory StartTranscriptionRequestLanguage.fromJson(String json) =>
      StartTranscriptionRequestLanguage._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class StartTranscriptionRequest with _$StartTranscriptionRequest {
  const StartTranscriptionRequest({
    this.enableClosedCaptions,
    this.language,
    this.transcriptionExternalStorage,
  });

  @override
  @JsonKey(name: 'enable_closed_captions')
  final bool? enableClosedCaptions;

  @override
  @JsonKey(name: 'language')
  final StartTranscriptionRequestLanguage? language;

  @override
  @JsonKey(name: 'transcription_external_storage')
  final String? transcriptionExternalStorage;

  Map<String, dynamic> toJson() => _$StartTranscriptionRequestToJson(this);

  static StartTranscriptionRequest fromJson(Map<String, dynamic> json) =>
      _$StartTranscriptionRequestFromJson(json);
}
