// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

enum StartTranscriptionRequestLanguageEnum {
  ar('ar'),
  auto('auto'),
  bg('bg'),
  ca('ca'),
  cs('cs'),
  da('da'),
  de('de'),
  el('el'),
  en('en'),
  es('es'),
  et('et'),
  fi('fi'),
  fr('fr'),
  he('he'),
  hi('hi'),
  hr('hr'),
  hu('hu'),
  id('id'),
  it('it'),
  ja('ja'),
  ko('ko'),
  ms('ms'),
  nl('nl'),
  no('no'),
  pl('pl'),
  pt('pt'),
  ro('ro'),
  ru('ru'),
  sk('sk'),
  sl('sl'),
  sv('sv'),
  ta('ta'),
  th('th'),
  tl('tl'),
  tr('tr'),
  uk('uk'),
  zh('zh'),
  unknown('_unknown');

  const StartTranscriptionRequestLanguageEnum(this.value);
  final String value;

  static StartTranscriptionRequestLanguageEnum? fromValue(String? json) {
    switch (json) {
      case null:
        return null;
      case 'ar':
        return StartTranscriptionRequestLanguageEnum.ar;
      case 'auto':
        return StartTranscriptionRequestLanguageEnum.auto;
      case 'bg':
        return StartTranscriptionRequestLanguageEnum.bg;
      case 'ca':
        return StartTranscriptionRequestLanguageEnum.ca;
      case 'cs':
        return StartTranscriptionRequestLanguageEnum.cs;
      case 'da':
        return StartTranscriptionRequestLanguageEnum.da;
      case 'de':
        return StartTranscriptionRequestLanguageEnum.de;
      case 'el':
        return StartTranscriptionRequestLanguageEnum.el;
      case 'en':
        return StartTranscriptionRequestLanguageEnum.en;
      case 'es':
        return StartTranscriptionRequestLanguageEnum.es;
      case 'et':
        return StartTranscriptionRequestLanguageEnum.et;
      case 'fi':
        return StartTranscriptionRequestLanguageEnum.fi;
      case 'fr':
        return StartTranscriptionRequestLanguageEnum.fr;
      case 'he':
        return StartTranscriptionRequestLanguageEnum.he;
      case 'hi':
        return StartTranscriptionRequestLanguageEnum.hi;
      case 'hr':
        return StartTranscriptionRequestLanguageEnum.hr;
      case 'hu':
        return StartTranscriptionRequestLanguageEnum.hu;
      case 'id':
        return StartTranscriptionRequestLanguageEnum.id;
      case 'it':
        return StartTranscriptionRequestLanguageEnum.it;
      case 'ja':
        return StartTranscriptionRequestLanguageEnum.ja;
      case 'ko':
        return StartTranscriptionRequestLanguageEnum.ko;
      case 'ms':
        return StartTranscriptionRequestLanguageEnum.ms;
      case 'nl':
        return StartTranscriptionRequestLanguageEnum.nl;
      case 'no':
        return StartTranscriptionRequestLanguageEnum.no;
      case 'pl':
        return StartTranscriptionRequestLanguageEnum.pl;
      case 'pt':
        return StartTranscriptionRequestLanguageEnum.pt;
      case 'ro':
        return StartTranscriptionRequestLanguageEnum.ro;
      case 'ru':
        return StartTranscriptionRequestLanguageEnum.ru;
      case 'sk':
        return StartTranscriptionRequestLanguageEnum.sk;
      case 'sl':
        return StartTranscriptionRequestLanguageEnum.sl;
      case 'sv':
        return StartTranscriptionRequestLanguageEnum.sv;
      case 'ta':
        return StartTranscriptionRequestLanguageEnum.ta;
      case 'th':
        return StartTranscriptionRequestLanguageEnum.th;
      case 'tl':
        return StartTranscriptionRequestLanguageEnum.tl;
      case 'tr':
        return StartTranscriptionRequestLanguageEnum.tr;
      case 'uk':
        return StartTranscriptionRequestLanguageEnum.uk;
      case 'zh':
        return StartTranscriptionRequestLanguageEnum.zh;
      default:
        return StartTranscriptionRequestLanguageEnum.unknown;
    }
  }
}

@immutable
class StartTranscriptionRequest {
  const StartTranscriptionRequest({
    this.enableClosedCaptions,
    this.language,
    this.transcriptionExternalStorage,
  });

  final bool? enableClosedCaptions;

  final StartTranscriptionRequestLanguageEnum? language;

  final String? transcriptionExternalStorage;

  Map<String, dynamic> toJson() {
    return {
      'enable_closed_captions': enableClosedCaptions,
      'language': language,
      'transcription_external_storage': transcriptionExternalStorage,
    };
  }

  static StartTranscriptionRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return StartTranscriptionRequest(
        enableClosedCaptions:
            mapValueOfType<bool>(json, r'enable_closed_captions', null),
        language:
            StartTranscriptionRequestLanguageEnum.fromValue(json['language']),
        transcriptionExternalStorage: mapValueOfType<String>(
            json, r'transcription_external_storage', null),
      );
    }
    return null;
  }

  static List<StartTranscriptionRequest> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <StartTranscriptionRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = StartTranscriptionRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'StartTranscriptionRequest('
        'enableClosedCaptions: $enableClosedCaptions, '
        'language: $language, '
        'transcriptionExternalStorage: $transcriptionExternalStorage, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is StartTranscriptionRequest &&
        other.enableClosedCaptions == enableClosedCaptions &&
        other.language == language &&
        other.transcriptionExternalStorage == transcriptionExternalStorage;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      enableClosedCaptions,
      language,
      transcriptionExternalStorage,
    ]);
  }
}
