// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class StartRTMPBroadcastsRequest {
  const StartRTMPBroadcastsRequest({
    required this.broadcasts,
  });

  final List<RTMPBroadcastRequest> broadcasts;

  Map<String, dynamic> toJson() {
    return {
      'broadcasts': broadcasts,
    };
  }

  static StartRTMPBroadcastsRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return StartRTMPBroadcastsRequest(
        broadcasts: RTMPBroadcastRequest.listFromJson(json[r'broadcasts'])!,
      );
    }
    return null;
  }

  static List<StartRTMPBroadcastsRequest> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <StartRTMPBroadcastsRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = StartRTMPBroadcastsRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'StartRTMPBroadcastsRequest('
        'broadcasts: $broadcasts, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is StartRTMPBroadcastsRequest &&
        other.broadcasts == broadcasts;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      broadcasts,
    ]);
  }
}
