// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class StopClosedCaptionsRequest {
  const StopClosedCaptionsRequest({
    this.stopTranscription,
  });

  final bool? stopTranscription;

  Map<String, dynamic> toJson() {
    return {
      'stop_transcription': stopTranscription,
    };
  }

  static StopClosedCaptionsRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return StopClosedCaptionsRequest(
        stopTranscription:
            mapValueOfType<bool?>(json, r'stop_transcription', null),
      );
    }
    return null;
  }

  static List<StopClosedCaptionsRequest> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <StopClosedCaptionsRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = StopClosedCaptionsRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'StopClosedCaptionsRequest('
        'stopTranscription: $stopTranscription, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is StopClosedCaptionsRequest &&
        other.stopTranscription == stopTranscription;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      stopTranscription,
    ]);
  }
}
