// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'stop_live_request.g.dart';
part 'stop_live_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class StopLiveRequest with _$StopLiveRequest {
  const StopLiveRequest({
    this.continueClosedCaption,
    this.continueCompositeRecording,
    this.continueHls,
    this.continueIndividualRecording,
    this.continueRawRecording,
    this.continueRecording,
    this.continueRtmpBroadcasts,
    this.continueTranscription,
  });

  @override
  final bool? continueClosedCaption;

  @override
  final bool? continueCompositeRecording;

  @override
  final bool? continueHls;

  @override
  final bool? continueIndividualRecording;

  @override
  final bool? continueRawRecording;

  @override
  final bool? continueRecording;

  @override
  final bool? continueRtmpBroadcasts;

  @override
  final bool? continueTranscription;

  Map<String, dynamic> toJson() => _$StopLiveRequestToJson(this);

  static StopLiveRequest fromJson(Map<String, dynamic> json) =>
      _$StopLiveRequestFromJson(json);
}
