// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class StopTranscriptionRequest {
  const StopTranscriptionRequest({
    this.stopClosedCaptions,
  });

  final bool? stopClosedCaptions;

  Map<String, dynamic> toJson() {
    return {
      'stop_closed_captions': stopClosedCaptions,
    };
  }

  static StopTranscriptionRequest? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return StopTranscriptionRequest(
        stopClosedCaptions:
            mapValueOfType<bool?>(json, r'stop_closed_captions', null),
      );
    }
    return null;
  }

  static List<StopTranscriptionRequest> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <StopTranscriptionRequest>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = StopTranscriptionRequest.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'StopTranscriptionRequest('
        'stopClosedCaptions: $stopClosedCaptions, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is StopTranscriptionRequest &&
        other.stopClosedCaptions == stopClosedCaptions;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      stopClosedCaptions,
    ]);
  }
}
