// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'submit_action_request.g.dart';
part 'submit_action_request.freezed.dart';

@JsonEnum(alwaysCreate: true)
enum SubmitActionRequestActionType {
  @JsonValue('ban')
  ban,
  @JsonValue('block')
  block,
  @JsonValue('bypass')
  bypass,
  @JsonValue('custom')
  custom,
  @JsonValue('de_escalate')
  deEscalate,
  @JsonValue('delete_activity')
  deleteActivity,
  @JsonValue('delete_comment')
  deleteComment,
  @JsonValue('delete_message')
  deleteMessage,
  @JsonValue('delete_reaction')
  deleteReaction,
  @JsonValue('delete_user')
  deleteUser,
  @JsonValue('end_call')
  endCall,
  @JsonValue('escalate')
  escalate,
  @JsonValue('flag')
  flag,
  @JsonValue('kick_user')
  kickUser,
  @JsonValue('mark_reviewed')
  markReviewed,
  @JsonValue('reject_appeal')
  rejectAppeal,
  @JsonValue('restore')
  restore,
  @JsonValue('shadow_block')
  shadowBlock,
  @JsonValue('unban')
  unban,
  @JsonValue('unblock')
  unblock,
  @JsonValue('unmask')
  unmask,
  @JsonValue('_unknown')
  unknown,
}

@freezed
@immutable
@JsonSerializable()
class SubmitActionRequest with _$SubmitActionRequest {
  const SubmitActionRequest({
    required this.actionType,
    this.appealId,
    this.ban,
    this.block,
    this.bypass,
    this.custom,
    this.deleteActivity,
    this.deleteComment,
    this.deleteMessage,
    this.deleteReaction,
    this.deleteUser,
    this.escalate,
    this.flag,
    this.itemId,
    this.markReviewed,
    this.rejectAppeal,
    this.restore,
    this.shadowBlock,
    this.unban,
    this.unblock,
  });

  @override
  @JsonKey(unknownEnumValue: SubmitActionRequestActionType.unknown)
  final SubmitActionRequestActionType actionType;

  @override
  final String? appealId;

  @override
  final BanActionRequestPayload? ban;

  @override
  final BlockActionRequestPayload? block;

  @override
  final BypassActionRequest? bypass;

  @override
  final CustomActionRequestPayload? custom;

  @override
  final DeleteActivityRequestPayload? deleteActivity;

  @override
  final DeleteCommentRequestPayload? deleteComment;

  @override
  final DeleteMessageRequestPayload? deleteMessage;

  @override
  final DeleteReactionRequestPayload? deleteReaction;

  @override
  final DeleteUserRequestPayload? deleteUser;

  @override
  final EscalatePayload? escalate;

  @override
  final FlagRequest? flag;

  @override
  final String? itemId;

  @override
  final MarkReviewedRequestPayload? markReviewed;

  @override
  final RejectAppealRequestPayload? rejectAppeal;

  @override
  final RestoreActionRequestPayload? restore;

  @override
  final ShadowBlockActionRequestPayload? shadowBlock;

  @override
  final UnbanActionRequestPayload? unban;

  @override
  final UnblockActionRequestPayload? unblock;

  Map<String, dynamic> toJson() => _$SubmitActionRequestToJson(this);

  static SubmitActionRequest fromJson(Map<String, dynamic> json) =>
      _$SubmitActionRequestFromJson(json);
}
