// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'subscriber_stats_response.g.dart';
part 'subscriber_stats_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class SubscriberStatsResponse with _$SubscriberStatsResponse {
  const SubscriberStatsResponse({
    required this.total,
    required this.totalSubscribedDurationSeconds,
    required this.unique,
  });

  @override
  final int total;

  @override
  final int totalSubscribedDurationSeconds;

  @override
  final int unique;

  Map<String, dynamic> toJson() => _$SubscriberStatsResponseToJson(this);

  static SubscriberStatsResponse fromJson(Map<String, dynamic> json) =>
      _$SubscriberStatsResponseFromJson(json);
}
