// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'text_rule_parameters.g.dart';
part 'text_rule_parameters.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class TextRuleParameters with _$TextRuleParameters {
  const TextRuleParameters({
    this.blocklistMatch,
    this.containsUrl,
    this.harmLabels,
    this.llmHarmLabels,
    this.semanticFilterMinThreshold,
    this.semanticFilterNames,
    this.severity,
    this.threshold,
    this.timeWindow,
  });

  @override
  final List<String>? blocklistMatch;

  @override
  final bool? containsUrl;

  @override
  final List<String>? harmLabels;

  @override
  final Map<String, String>? llmHarmLabels;

  @override
  final double? semanticFilterMinThreshold;

  @override
  final List<String>? semanticFilterNames;

  @override
  final String? severity;

  @override
  final int? threshold;

  @override
  final String? timeWindow;

  Map<String, dynamic> toJson() => _$TextRuleParametersToJson(this);

  static TextRuleParameters fromJson(Map<String, dynamic> json) =>
      _$TextRuleParametersFromJson(json);
}
