// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'track_stats_response.g.dart';
part 'track_stats_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class TrackStatsResponse with _$TrackStatsResponse {
  const TrackStatsResponse({
    required this.durationSeconds,
    required this.trackType,
  });

  @override
  final int durationSeconds;

  @override
  final String trackType;

  Map<String, dynamic> toJson() => _$TrackStatsResponseToJson(this);

  static TrackStatsResponse fromJson(Map<String, dynamic> json) =>
      _$TrackStatsResponseFromJson(json);
}
