// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'translation_settings.g.dart';
part 'translation_settings.freezed.dart';

extension type const TranslationSettingsLanguages._(String _)
    implements String {
  static const ar = TranslationSettingsLanguages._('ar');
  static const ca = TranslationSettingsLanguages._('ca');
  static const cs = TranslationSettingsLanguages._('cs');
  static const da = TranslationSettingsLanguages._('da');
  static const de = TranslationSettingsLanguages._('de');
  static const el = TranslationSettingsLanguages._('el');
  static const en = TranslationSettingsLanguages._('en');
  static const es = TranslationSettingsLanguages._('es');
  static const fi = TranslationSettingsLanguages._('fi');
  static const fr = TranslationSettingsLanguages._('fr');
  static const he = TranslationSettingsLanguages._('he');
  static const hi = TranslationSettingsLanguages._('hi');
  static const hr = TranslationSettingsLanguages._('hr');
  static const hu = TranslationSettingsLanguages._('hu');
  static const id = TranslationSettingsLanguages._('id');
  static const it = TranslationSettingsLanguages._('it');
  static const ja = TranslationSettingsLanguages._('ja');
  static const ko = TranslationSettingsLanguages._('ko');
  static const ms = TranslationSettingsLanguages._('ms');
  static const nl = TranslationSettingsLanguages._('nl');
  static const no = TranslationSettingsLanguages._('no');
  static const pl = TranslationSettingsLanguages._('pl');
  static const pt = TranslationSettingsLanguages._('pt');
  static const ro = TranslationSettingsLanguages._('ro');
  static const ru = TranslationSettingsLanguages._('ru');
  static const sv = TranslationSettingsLanguages._('sv');
  static const ta = TranslationSettingsLanguages._('ta');
  static const th = TranslationSettingsLanguages._('th');
  static const tl = TranslationSettingsLanguages._('tl');
  static const tr = TranslationSettingsLanguages._('tr');
  static const uk = TranslationSettingsLanguages._('uk');
  static const zh = TranslationSettingsLanguages._('zh');

  factory TranslationSettingsLanguages.fromJson(String json) =>
      TranslationSettingsLanguages._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class TranslationSettings with _$TranslationSettings {
  const TranslationSettings({
    this.enabled,
    this.languages,
  });

  @override
  @JsonKey(name: 'enabled')
  final bool? enabled;

  @override
  @JsonKey(name: 'languages')
  final List<TranslationSettingsLanguages>? languages;

  Map<String, dynamic> toJson() => _$TranslationSettingsToJson(this);

  static TranslationSettings fromJson(Map<String, dynamic> json) =>
      _$TranslationSettingsFromJson(json);
}
