// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'transcription_settings_response.g.dart';
part 'transcription_settings_response.freezed.dart';

extension type const TranscriptionSettingsResponseClosedCaptionMode._(String _)
    implements String {
  static const autoOn = TranscriptionSettingsResponseClosedCaptionMode._(
    'auto-on',
  );
  static const available = TranscriptionSettingsResponseClosedCaptionMode._(
    'available',
  );
  static const disabled = TranscriptionSettingsResponseClosedCaptionMode._(
    'disabled',
  );

  factory TranscriptionSettingsResponseClosedCaptionMode.fromJson(
    String json,
  ) => TranscriptionSettingsResponseClosedCaptionMode._(json);

  String toJson() => this;
}

extension type const TranscriptionSettingsResponseLanguage._(String _)
    implements String {
  static const ar = TranscriptionSettingsResponseLanguage._('ar');
  static const auto = TranscriptionSettingsResponseLanguage._('auto');
  static const bg = TranscriptionSettingsResponseLanguage._('bg');
  static const ca = TranscriptionSettingsResponseLanguage._('ca');
  static const cs = TranscriptionSettingsResponseLanguage._('cs');
  static const da = TranscriptionSettingsResponseLanguage._('da');
  static const de = TranscriptionSettingsResponseLanguage._('de');
  static const el = TranscriptionSettingsResponseLanguage._('el');
  static const en = TranscriptionSettingsResponseLanguage._('en');
  static const es = TranscriptionSettingsResponseLanguage._('es');
  static const et = TranscriptionSettingsResponseLanguage._('et');
  static const fi = TranscriptionSettingsResponseLanguage._('fi');
  static const fr = TranscriptionSettingsResponseLanguage._('fr');
  static const he = TranscriptionSettingsResponseLanguage._('he');
  static const hi = TranscriptionSettingsResponseLanguage._('hi');
  static const hr = TranscriptionSettingsResponseLanguage._('hr');
  static const hu = TranscriptionSettingsResponseLanguage._('hu');
  static const id = TranscriptionSettingsResponseLanguage._('id');
  static const it = TranscriptionSettingsResponseLanguage._('it');
  static const ja = TranscriptionSettingsResponseLanguage._('ja');
  static const ko = TranscriptionSettingsResponseLanguage._('ko');
  static const ms = TranscriptionSettingsResponseLanguage._('ms');
  static const nl = TranscriptionSettingsResponseLanguage._('nl');
  static const no = TranscriptionSettingsResponseLanguage._('no');
  static const pl = TranscriptionSettingsResponseLanguage._('pl');
  static const pt = TranscriptionSettingsResponseLanguage._('pt');
  static const ro = TranscriptionSettingsResponseLanguage._('ro');
  static const ru = TranscriptionSettingsResponseLanguage._('ru');
  static const sk = TranscriptionSettingsResponseLanguage._('sk');
  static const sl = TranscriptionSettingsResponseLanguage._('sl');
  static const sv = TranscriptionSettingsResponseLanguage._('sv');
  static const ta = TranscriptionSettingsResponseLanguage._('ta');
  static const th = TranscriptionSettingsResponseLanguage._('th');
  static const tl = TranscriptionSettingsResponseLanguage._('tl');
  static const tr = TranscriptionSettingsResponseLanguage._('tr');
  static const uk = TranscriptionSettingsResponseLanguage._('uk');
  static const zh = TranscriptionSettingsResponseLanguage._('zh');

  factory TranscriptionSettingsResponseLanguage.fromJson(String json) =>
      TranscriptionSettingsResponseLanguage._(json);

  String toJson() => this;
}

extension type const TranscriptionSettingsResponseMode._(String _)
    implements String {
  static const autoOn = TranscriptionSettingsResponseMode._('auto-on');
  static const available = TranscriptionSettingsResponseMode._('available');
  static const disabled = TranscriptionSettingsResponseMode._('disabled');

  factory TranscriptionSettingsResponseMode.fromJson(String json) =>
      TranscriptionSettingsResponseMode._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class TranscriptionSettingsResponse with _$TranscriptionSettingsResponse {
  const TranscriptionSettingsResponse({
    required this.closedCaptionMode,
    required this.language,
    required this.mode,
    this.speechSegmentConfig,
    this.translation,
  });

  @override
  @JsonKey(name: 'closed_caption_mode')
  final TranscriptionSettingsResponseClosedCaptionMode closedCaptionMode;

  @override
  @JsonKey(name: 'language')
  final TranscriptionSettingsResponseLanguage language;

  @override
  @JsonKey(name: 'mode')
  final TranscriptionSettingsResponseMode mode;

  @override
  @JsonKey(name: 'speech_segment_config')
  final SpeechSegmentConfig? speechSegmentConfig;

  @override
  @JsonKey(name: 'translation')
  final TranslationSettings? translation;

  Map<String, dynamic> toJson() => _$TranscriptionSettingsResponseToJson(this);

  static TranscriptionSettingsResponse fromJson(Map<String, dynamic> json) =>
      _$TranscriptionSettingsResponseFromJson(json);
}
