// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class UnblockedUserEvent {
  const UnblockedUserEvent({
    required this.callCid,
    required this.createdAt,
    required this.type,
    required this.user,
  });

  final String callCid;

  final DateTime createdAt;

  final String type;

  final UserResponse user;

  Map<String, dynamic> toJson() {
    return {
      'call_cid': callCid,
      'created_at': createdAt,
      'type': type,
      'user': user,
    };
  }

  static UnblockedUserEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return UnblockedUserEvent(
        callCid: mapValueOfType<String>(json, r'call_cid')!,
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        type: mapValueOfType<String>(json, r'type', "call.unblocked_user")!,
        user: UserResponse.fromJson(json[r'user'])!,
      );
    }
    return null;
  }

  static List<UnblockedUserEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <UnblockedUserEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = UnblockedUserEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'UnblockedUserEvent('
        'callCid: $callCid, '
        'createdAt: $createdAt, '
        'type: $type, '
        'user: $user, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is UnblockedUserEvent &&
        other.callCid == callCid &&
        other.createdAt == createdAt &&
        other.type == type &&
        other.user == user;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      callCid,
      createdAt,
      type,
      user,
    ]);
  }
}
