// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'update_call_response.g.dart';
part 'update_call_response.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UpdateCallResponse with _$UpdateCallResponse {
  const UpdateCallResponse({
    required this.call,
    required this.duration,
    this.members = const [],
    this.membership,
    this.ownCapabilities = const [],
  });

  @override
  final CallResponse call;

  @override
  final String duration;

  @override
  @JsonKey(defaultValue: [])
  final List<MemberResponse> members;

  @override
  final MemberResponse? membership;

  @override
  @JsonKey(unknownEnumValue: OwnCapability.unknown, defaultValue: [])
  final List<OwnCapability> ownCapabilities;

  Map<String, dynamic> toJson() => _$UpdateCallResponseToJson(this);

  static UpdateCallResponse fromJson(Map<String, dynamic> json) =>
      _$UpdateCallResponseFromJson(json);
}
