// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'update_user_permissions_request.g.dart';
part 'update_user_permissions_request.freezed.dart';

@JsonEnum(alwaysCreate: true)
enum UpdateUserPermissionsRequestGrantPermissions {
  @JsonValue('screenshare')
  screenshare,
  @JsonValue('send-audio')
  sendAudio,
  @JsonValue('send-video')
  sendVideo,
  @JsonValue('_unknown')
  unknown,
}

@JsonEnum(alwaysCreate: true)
enum UpdateUserPermissionsRequestRevokePermissions {
  @JsonValue('screenshare')
  screenshare,
  @JsonValue('send-audio')
  sendAudio,
  @JsonValue('send-video')
  sendVideo,
  @JsonValue('_unknown')
  unknown,
}

@freezed
@immutable
@JsonSerializable()
class UpdateUserPermissionsRequest with _$UpdateUserPermissionsRequest {
  const UpdateUserPermissionsRequest({
    this.grantPermissions,
    this.revokePermissions,
    required this.userId,
  });

  @override
  @JsonKey(
    unknownEnumValue: UpdateUserPermissionsRequestGrantPermissions.unknown,
  )
  final List<UpdateUserPermissionsRequestGrantPermissions>? grantPermissions;

  @override
  @JsonKey(
    unknownEnumValue: UpdateUserPermissionsRequestRevokePermissions.unknown,
  )
  final List<UpdateUserPermissionsRequestRevokePermissions>? revokePermissions;

  @override
  final String userId;

  Map<String, dynamic> toJson() => _$UpdateUserPermissionsRequestToJson(this);

  static UpdateUserPermissionsRequest fromJson(Map<String, dynamic> json) =>
      _$UpdateUserPermissionsRequestFromJson(json);
}
