// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs, sort_constructors_first

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'update_user_permissions_request.g.dart';
part 'update_user_permissions_request.freezed.dart';

extension type const UpdateUserPermissionsRequestGrantPermissions._(String _)
    implements String {
  static const screenshare = UpdateUserPermissionsRequestGrantPermissions._(
    'screenshare',
  );
  static const sendAudio = UpdateUserPermissionsRequestGrantPermissions._(
    'send-audio',
  );
  static const sendVideo = UpdateUserPermissionsRequestGrantPermissions._(
    'send-video',
  );

  factory UpdateUserPermissionsRequestGrantPermissions.fromJson(String json) =>
      UpdateUserPermissionsRequestGrantPermissions._(json);

  String toJson() => this;
}

extension type const UpdateUserPermissionsRequestRevokePermissions._(String _)
    implements String {
  static const screenshare = UpdateUserPermissionsRequestRevokePermissions._(
    'screenshare',
  );
  static const sendAudio = UpdateUserPermissionsRequestRevokePermissions._(
    'send-audio',
  );
  static const sendVideo = UpdateUserPermissionsRequestRevokePermissions._(
    'send-video',
  );

  factory UpdateUserPermissionsRequestRevokePermissions.fromJson(String json) =>
      UpdateUserPermissionsRequestRevokePermissions._(json);

  String toJson() => this;
}

@freezed
@immutable
@JsonSerializable()
class UpdateUserPermissionsRequest with _$UpdateUserPermissionsRequest {
  const UpdateUserPermissionsRequest({
    this.grantPermissions,
    this.revokePermissions,
    required this.userId,
  });

  @override
  @JsonKey(name: 'grant_permissions')
  final List<UpdateUserPermissionsRequestGrantPermissions>? grantPermissions;

  @override
  @JsonKey(name: 'revoke_permissions')
  final List<UpdateUserPermissionsRequestRevokePermissions>? revokePermissions;

  @override
  @JsonKey(name: 'user_id')
  final String userId;

  Map<String, dynamic> toJson() => _$UpdateUserPermissionsRequestToJson(this);

  static UpdateUserPermissionsRequest fromJson(Map<String, dynamic> json) =>
      _$UpdateUserPermissionsRequestFromJson(json);
}
