// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'update_block_list_request.g.dart';
part 'update_block_list_request.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UpdateBlockListRequest with _$UpdateBlockListRequest {
  const UpdateBlockListRequest({
    this.isLeetCheckEnabled,
    this.isPluralCheckEnabled,
    this.team,
    this.words,
  });

  @override
  final bool? isLeetCheckEnabled;

  @override
  final bool? isPluralCheckEnabled;

  @override
  final String? team;

  @override
  final List<String>? words;

  Map<String, dynamic> toJson() => _$UpdateBlockListRequestToJson(this);

  static UpdateBlockListRequest fromJson(Map<String, dynamic> json) =>
      _$UpdateBlockListRequestFromJson(json);
}
