// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'updated_call_permissions_event.g.dart';
part 'updated_call_permissions_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UpdatedCallPermissionsEvent extends core.WsEvent
    with _$UpdatedCallPermissionsEvent {
  const UpdatedCallPermissionsEvent({
    required this.callCid,
    required this.createdAt,
    required this.ownCapabilities,
    required this.type,
    required this.user,
  });

  @override
  final String callCid;

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  @JsonKey(unknownEnumValue: OwnCapability.unknown, defaultValue: [])
  final List<OwnCapability> ownCapabilities;

  @override
  final String type;

  @override
  final UserResponse user;

  Map<String, dynamic> toJson() => _$UpdatedCallPermissionsEventToJson(this);

  static UpdatedCallPermissionsEvent fromJson(Map<String, dynamic> json) =>
      _$UpdatedCallPermissionsEventFromJson(json);
}
