// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class UserFeedbackReport {
  const UserFeedbackReport({
    required this.countByRating,
    required this.unreportedCount,
  });

  final Map<String, int> countByRating;

  final int unreportedCount;

  Map<String, dynamic> toJson() {
    return {
      'count_by_rating': countByRating,
      'unreported_count': unreportedCount,
    };
  }

  static UserFeedbackReport? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return UserFeedbackReport(
        countByRating: mapCastOfType<String, int>(json, r'count_by_rating')!,
        unreportedCount: mapValueOfType<int>(json, r'unreported_count')!,
      );
    }
    return null;
  }

  static List<UserFeedbackReport> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <UserFeedbackReport>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = UserFeedbackReport.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'UserFeedbackReport('
        'countByRating: $countByRating, '
        'unreportedCount: $unreportedCount, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is UserFeedbackReport &&
        other.countByRating == countByRating &&
        other.unreportedCount == unreportedCount;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      countByRating,
      unreportedCount,
    ]);
  }
}
