// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class UserReactivatedEvent {
  const UserReactivatedEvent({
    required this.createdAt,
    required this.type,
    this.user,
  });

  final DateTime createdAt;

  final String type;

  final User? user;

  Map<String, dynamic> toJson() {
    return {
      'created_at': createdAt,
      'type': type,
      'user': user,
    };
  }

  static UserReactivatedEvent? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return UserReactivatedEvent(
        createdAt: mapValueOfType<DateTime>(json, r'created_at')!,
        type: mapValueOfType<String>(json, r'type', "user.reactivated")!,
        user: User?.fromJson(json[r'user'] ?? null),
      );
    }
    return null;
  }

  static List<UserReactivatedEvent> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <UserReactivatedEvent>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = UserReactivatedEvent.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'UserReactivatedEvent('
        'createdAt: $createdAt, '
        'type: $type, '
        'user: $user, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is UserReactivatedEvent &&
        other.createdAt == createdAt &&
        other.type == type &&
        other.user == user;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      createdAt,
      type,
      user,
    ]);
  }
}
