// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'user_updated_event.g.dart';
part 'user_updated_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UserUpdatedEvent extends core.WsEvent with _$UserUpdatedEvent {
  const UserUpdatedEvent({
    required this.createdAt,
    required this.custom,
    this.receivedAt,
    required this.type,
    required this.user,
  });

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  final Map<String, Object?> custom;

  @override
  @EpochDateTimeConverter()
  final DateTime? receivedAt;

  @override
  final String type;

  @override
  final UserResponsePrivacyFields user;

  Map<String, dynamic> toJson() => _$UserUpdatedEventToJson(this);

  static UserUpdatedEvent fromJson(Map<String, dynamic> json) =>
      _$UserUpdatedEventFromJson(json);
}
