// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'user_banned_event.g.dart';
part 'user_banned_event.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class UserBannedEvent extends core.WsEvent with _$UserBannedEvent {
  const UserBannedEvent({
    this.channelCustom,
    this.channelId,
    this.channelMemberCount,
    this.channelMessageCount,
    this.channelType,
    this.cid,
    required this.createdAt,
    this.createdBy,
    required this.custom,
    this.expiration,
    this.reason,
    this.receivedAt,
    this.reviewQueueItemId,
    this.shadow,
    this.team,
    this.totalBans,
    required this.type,
    required this.user,
  });

  @override
  final Map<String, Object?>? channelCustom;

  @override
  final String? channelId;

  @override
  final int? channelMemberCount;

  @override
  final int? channelMessageCount;

  @override
  final String? channelType;

  @override
  final String? cid;

  @override
  @EpochDateTimeConverter()
  final DateTime createdAt;

  @override
  final UserResponseCommonFields? createdBy;

  @override
  final Map<String, Object?> custom;

  @override
  @EpochDateTimeConverter()
  final DateTime? expiration;

  @override
  final String? reason;

  @override
  @EpochDateTimeConverter()
  final DateTime? receivedAt;

  @override
  final String? reviewQueueItemId;

  @override
  final bool? shadow;

  @override
  final String? team;

  @override
  final int? totalBans;

  @override
  final String type;

  @override
  final UserResponseCommonFields user;

  Map<String, dynamic> toJson() => _$UserBannedEventToJson(this);

  static UserBannedEvent fromJson(Map<String, dynamic> json) =>
      _$UserBannedEventFromJson(json);
}
