// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'velocity_filter_config.g.dart';
part 'velocity_filter_config.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class VelocityFilterConfig with _$VelocityFilterConfig {
  const VelocityFilterConfig({
    required this.advancedFilters,
    this.async,
    required this.cascadingActions,
    required this.cidsPerUser,
    required this.enabled,
    required this.firstMessageOnly,
    required this.rules,
  });

  @override
  final bool advancedFilters;

  @override
  final bool? async;

  @override
  final bool cascadingActions;

  @override
  final int cidsPerUser;

  @override
  final bool enabled;

  @override
  final bool firstMessageOnly;

  @override
  final List<VelocityFilterConfigRule> rules;

  Map<String, dynamic> toJson() => _$VelocityFilterConfigToJson(this);

  static VelocityFilterConfig fromJson(Map<String, dynamic> json) =>
      _$VelocityFilterConfigFromJson(json);
}
