// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'velocity_filter_config_rule.g.dart';
part 'velocity_filter_config_rule.freezed.dart';

@JsonEnum(alwaysCreate: true)
enum VelocityFilterConfigRuleAction {
  @JsonValue('ban')
  ban,
  @JsonValue('flag')
  flag,
  @JsonValue('remove')
  remove,
  @JsonValue('shadow')
  shadow,
  @JsonValue('_unknown')
  unknown,
}

@JsonEnum(alwaysCreate: true)
enum VelocityFilterConfigRuleCascadingAction {
  @JsonValue('ban')
  ban,
  @JsonValue('flag')
  flag,
  @JsonValue('remove')
  remove,
  @JsonValue('shadow')
  shadow,
  @JsonValue('_unknown')
  unknown,
}

@freezed
@immutable
@JsonSerializable()
class VelocityFilterConfigRule with _$VelocityFilterConfigRule {
  const VelocityFilterConfigRule({
    required this.action,
    required this.banDuration,
    required this.cascadingAction,
    required this.cascadingThreshold,
    required this.checkMessageContext,
    required this.fastSpamThreshold,
    required this.fastSpamTtl,
    required this.ipBan,
    required this.probationPeriod,
    required this.shadowBan,
    this.slowSpamBanDuration,
    required this.slowSpamThreshold,
    required this.slowSpamTtl,
    required this.urlOnly,
  });

  @override
  @JsonKey(unknownEnumValue: VelocityFilterConfigRuleAction.unknown)
  final VelocityFilterConfigRuleAction action;

  @override
  final int banDuration;

  @override
  @JsonKey(unknownEnumValue: VelocityFilterConfigRuleCascadingAction.unknown)
  final VelocityFilterConfigRuleCascadingAction cascadingAction;

  @override
  final int cascadingThreshold;

  @override
  final bool checkMessageContext;

  @override
  final int fastSpamThreshold;

  @override
  final int fastSpamTtl;

  @override
  final bool ipBan;

  @override
  final int probationPeriod;

  @override
  final bool shadowBan;

  @override
  final int? slowSpamBanDuration;

  @override
  final int slowSpamThreshold;

  @override
  final int slowSpamTtl;

  @override
  final bool urlOnly;

  Map<String, dynamic> toJson() => _$VelocityFilterConfigRuleToJson(this);

  static VelocityFilterConfigRule fromJson(Map<String, dynamic> json) =>
      _$VelocityFilterConfigRuleFromJson(json);
}
