// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// ignore_for_file: use_string_in_part_of_directives
// ignore_for_file: unnecessary_raw_strings

part of openapi.api;

@immutable
class VideoReactionOverTimeResponse {
  const VideoReactionOverTimeResponse({
    this.byMinute,
  });

  final List<CountByMinuteResponse>? byMinute;

  Map<String, dynamic> toJson() {
    return {
      'by_minute': byMinute,
    };
  }

  static VideoReactionOverTimeResponse? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      return VideoReactionOverTimeResponse(
        byMinute: CountByMinuteResponse.listFromJson(json[r'by_minute']),
      );
    }
    return null;
  }

  static List<VideoReactionOverTimeResponse> listFromJson(
    dynamic json, {
    bool growable = false,
  }) {
    final result = <VideoReactionOverTimeResponse>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = VideoReactionOverTimeResponse.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  @override
  String toString() {
    return 'VideoReactionOverTimeResponse('
        'byMinute: $byMinute, '
        ')';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is VideoReactionOverTimeResponse && other.byMinute == byMinute;
  }

  @override
  int get hashCode {
    return Object.hashAll([
      byMinute,
    ]);
  }
}
