// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:meta/meta.dart';
import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

part 'whip_ingress.g.dart';
part 'whip_ingress.freezed.dart';

@freezed
@immutable
@JsonSerializable()
class WHIPIngress with _$WHIPIngress {
  const WHIPIngress({
    required this.address,
  });

  @override
  final String address;

  Map<String, dynamic> toJson() => _$WHIPIngressToJson(this);

  static WHIPIngress fromJson(Map<String, dynamic> json) =>
      _$WHIPIngressFromJson(json);
}
