// Code generated by GetStream internal OpenAPI code generator. DO NOT EDIT.

// coverage:ignore-file
// ignore_for_file: unused_import, unnecessary_import, prefer_single_quotes, require_trailing_commas, unnecessary_raw_strings, public_member_api_docs

import 'package:stream_core/stream_core.dart' as core;

import '../models.dart';

abstract class WSClientEvent<T extends core.WsEvent> {
  const WSClientEvent(this.wrapped);

  final T wrapped;
  String get type;

  static WSClientEvent fromJson(Map<String, dynamic> json) {
    final eventType = json['type'];

    if (eventType == null || eventType is! String) {
      throw ArgumentError('Invalid or missing "type" field in JSON: $json');
    }

    return switch (eventType) {
      "app.updated" => _AppUpdatedEvent(AppUpdatedEvent.fromJson(json)),
      "moderation.custom_action" => _ModerationCustomActionEvent(
        ModerationCustomActionEvent.fromJson(json),
      ),
      "moderation.flagged" => _ModerationFlaggedEvent(
        ModerationFlaggedEvent.fromJson(json),
      ),
      "moderation.mark_reviewed" => _ModerationMarkReviewedEvent(
        ModerationMarkReviewedEvent.fromJson(json),
      ),
      "user.banned" => _UserBannedEvent(UserBannedEvent.fromJson(json)),
      "user.deactivated" => _UserDeactivatedEvent(
        UserDeactivatedEvent.fromJson(json),
      ),
      "user.deleted" => _UserDeletedEvent(UserDeletedEvent.fromJson(json)),
      "user.presence.changed" => _UserPresenceChangedEvent(
        UserPresenceChangedEvent.fromJson(json),
      ),
      "user.reactivated" => _UserReactivatedEvent(
        UserReactivatedEvent.fromJson(json),
      ),
      "user.unbanned" => _UserUnbannedEvent(UserUnbannedEvent.fromJson(json)),
      "user.updated" => _UserUpdatedEvent(UserUpdatedEvent.fromJson(json)),
      _ => _UnknownWSClientEvent(UnknownWSClientEvent(eventType, json)),
    };
  }
}

class _AppUpdatedEvent extends WSClientEvent<AppUpdatedEvent> {
  const _AppUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ModerationCustomActionEvent
    extends WSClientEvent<ModerationCustomActionEvent> {
  const _ModerationCustomActionEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ModerationFlaggedEvent extends WSClientEvent<ModerationFlaggedEvent> {
  const _ModerationFlaggedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _ModerationMarkReviewedEvent
    extends WSClientEvent<ModerationMarkReviewedEvent> {
  const _ModerationMarkReviewedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserBannedEvent extends WSClientEvent<UserBannedEvent> {
  const _UserBannedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserDeactivatedEvent extends WSClientEvent<UserDeactivatedEvent> {
  const _UserDeactivatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserDeletedEvent extends WSClientEvent<UserDeletedEvent> {
  const _UserDeletedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserPresenceChangedEvent
    extends WSClientEvent<UserPresenceChangedEvent> {
  const _UserPresenceChangedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserReactivatedEvent extends WSClientEvent<UserReactivatedEvent> {
  const _UserReactivatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserUnbannedEvent extends WSClientEvent<UserUnbannedEvent> {
  const _UserUnbannedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UserUpdatedEvent extends WSClientEvent<UserUpdatedEvent> {
  const _UserUpdatedEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class _UnknownWSClientEvent extends WSClientEvent<UnknownWSClientEvent> {
  const _UnknownWSClientEvent(super.wrapped);

  @override
  String get type => wrapped.type;
}

class UnknownWSClientEvent extends core.WsEvent {
  const UnknownWSClientEvent(this.type, this.rawJson);

  final String type;
  final Map<String, Object?> rawJson;
}
