package io.getstream.video.flutter.stream_video_flutter.service.notification

import android.os.Parcel
import android.os.Parcelable
import androidx.core.os.ParcelCompat

// These payloads are handed to the foreground services as Intent extras, so they have to be
// Parcelable. The implementations below are written by hand rather than generated by
// kotlin-parcelize: that plugin is a Kotlin compiler plugin and it does not run under AGP's
// built-in Kotlin, which silently leaves @Parcelize classes without a writeToParcel.

data class NotificationPayload(
    val callCid: String = "",
    val options: NotificationOptions? = null,
) : Parcelable {

    override fun describeContents(): Int = 0

    override fun writeToParcel(dest: Parcel, flags: Int) {
        dest.writeString(callCid)
        dest.writeParcelable(options, flags)
    }

    companion object {
        private const val CALL_CID = "call_cid"
        private const val OPTIONS = "options"

        @JvmField
        val CREATOR: Parcelable.Creator<NotificationPayload> =
            object : Parcelable.Creator<NotificationPayload> {
                override fun createFromParcel(source: Parcel): NotificationPayload =
                    NotificationPayload(
                        callCid = source.readString().orEmpty(),
                        options = ParcelCompat.readParcelable(
                            source,
                            NotificationOptions::class.java.classLoader,
                            NotificationOptions::class.java,
                        ),
                    )

                override fun newArray(size: Int): Array<NotificationPayload?> =
                    arrayOfNulls(size)
            }

        fun fromJson(json: Any?): NotificationPayload {
            if (json is Map<*, *>) {
                return NotificationPayload(
                    callCid = (json[CALL_CID] as? String) ?: error("no call_cid found"),
                    options = NotificationOptions.fromJson(json[OPTIONS])
                )
            }
            error("json must be an instance of Map, but was: $json")
        }
    }
}

data class NotificationOptions(
    val content: NotificationContent? = null,
    val avatar: NotificationAvatar? = null,
    val useCustomLayout: Boolean = false,
) : Parcelable {

    override fun describeContents(): Int = 0

    override fun writeToParcel(dest: Parcel, flags: Int) {
        dest.writeParcelable(content, flags)
        dest.writeParcelable(avatar, flags)
        ParcelCompat.writeBoolean(dest, useCustomLayout)
    }

    companion object {
        private const val CONTENT = "content"
        private const val AVATAR = "avatar"
        private const val USE_CUSTOM_LAYOUT = "use_custom_layout"

        @JvmField
        val CREATOR: Parcelable.Creator<NotificationOptions> =
            object : Parcelable.Creator<NotificationOptions> {
                override fun createFromParcel(source: Parcel): NotificationOptions =
                    NotificationOptions(
                        content = ParcelCompat.readParcelable(
                            source,
                            NotificationContent::class.java.classLoader,
                            NotificationContent::class.java,
                        ),
                        avatar = ParcelCompat.readParcelable(
                            source,
                            NotificationAvatar::class.java.classLoader,
                            NotificationAvatar::class.java,
                        ),
                        useCustomLayout = ParcelCompat.readBoolean(source),
                    )

                override fun newArray(size: Int): Array<NotificationOptions?> =
                    arrayOfNulls(size)
            }

        fun fromJson(json: Any?): NotificationOptions? {
            if (json is Map<*, *>) {
                val content = NotificationContent.fromJson(json[CONTENT])
                val avatar = NotificationAvatar.fromJson(json[AVATAR])
                val rawUseCustomLayout = json[USE_CUSTOM_LAYOUT]
                if (rawUseCustomLayout is String) {
                    error("NotificationOptions.fromJson => use_custom_layout should be Boolean")
                }
                val useCustomLayout = (json[USE_CUSTOM_LAYOUT] as? Boolean) ?: false
                if (content != null || avatar != null) {
                    return NotificationOptions(
                        content = content,
                        avatar = avatar,
                        useCustomLayout = useCustomLayout,
                    )
                }
            }
            return null
        }
    }
}

data class NotificationContent(
    val title: String? = null,
    val text: String? = null,
) : Parcelable {

    override fun describeContents(): Int = 0

    override fun writeToParcel(dest: Parcel, flags: Int) {
        dest.writeString(title)
        dest.writeString(text)
    }

    companion object {
        private const val TITLE = "title"
        private const val TEXT = "text"

        @JvmField
        val CREATOR: Parcelable.Creator<NotificationContent> =
            object : Parcelable.Creator<NotificationContent> {
                override fun createFromParcel(source: Parcel): NotificationContent =
                    NotificationContent(
                        title = source.readString(),
                        text = source.readString(),
                    )

                override fun newArray(size: Int): Array<NotificationContent?> =
                    arrayOfNulls(size)
            }

        fun fromJson(json: Any?): NotificationContent? {
            if (json is Map<*, *>) {
                val title = json[TITLE] as? String
                val text = json[TEXT] as? String
                if (title != null || text != null) {
                    return NotificationContent(title = title, text = text)
                }
            }
            return null
        }
    }
}

data class NotificationAvatar(
    val url: String? = null,
    val httpHeaders: Map<String, String> = emptyMap(),
) : Parcelable {

    override fun describeContents(): Int = 0

    override fun writeToParcel(dest: Parcel, flags: Int) {
        dest.writeString(url)
        dest.writeInt(httpHeaders.size)
        httpHeaders.forEach { (key, value) ->
            dest.writeString(key)
            dest.writeString(value)
        }
    }

    companion object {
        const val URL = "url"
        const val HTTP_HEADERS = "http_headers"

        @JvmField
        val CREATOR: Parcelable.Creator<NotificationAvatar> =
            object : Parcelable.Creator<NotificationAvatar> {
                override fun createFromParcel(source: Parcel): NotificationAvatar {
                    val url = source.readString()
                    val size = source.readInt()
                    val httpHeaders = buildMap(size) {
                        repeat(size) {
                            val key = source.readString()
                            val value = source.readString()
                            if (key != null && value != null) put(key, value)
                        }
                    }
                    return NotificationAvatar(url = url, httpHeaders = httpHeaders)
                }

                override fun newArray(size: Int): Array<NotificationAvatar?> =
                    arrayOfNulls(size)
            }

        fun fromJson(json: Any?): NotificationAvatar? {
            if (json is Map<*, *>) {
                val url = json[URL] as? String
                val httpHeaders = json[HTTP_HEADERS] as? Map<String, String>
                if (url != null) {
                    return NotificationAvatar(
                        url = url,
                        httpHeaders = httpHeaders ?: emptyMap(),
                    )
                }
            }
            return null
        }
    }
}
