import 'dart:math';

/// Word pool for generated encryption passphrases.
///
/// Short, unambiguous, easy to read aloud over a call — the key gets shared
/// by voice or chat, so anything easily misheard costs a failed decrypt.
const _words = <String>[
  'amber',
  'anchor',
  'arctic',
  'autumn',
  'badger',
  'bamboo',
  'beacon',
  'birch',
  'bishop',
  'blossom',
  'boulder',
  'brave',
  'breeze',
  'bridge',
  'bronze',
  'canyon',
  'cedar',
  'chorus',
  'cinder',
  'clever',
  'clover',
  'cobalt',
  'comet',
  'copper',
  'coral',
  'cosmic',
  'crimson',
  'crystal',
  'dagger',
  'delta',
  'desert',
  'dolphin',
  'dragon',
  'dusk',
  'eagle',
  'ember',
  'falcon',
  'fern',
  'forest',
  'fossil',
  'garnet',
  'glacier',
  'granite',
  'harbor',
  'hazel',
  'heron',
  'indigo',
  'island',
  'ivory',
  'jasper',
  'jungle',
  'kestrel',
  'lagoon',
  'lantern',
  'lilac',
  'lunar',
  'maple',
  'marble',
  'meadow',
  'meteor',
  'mint',
  'noble',
  'nomad',
  'ocean',
  'onyx',
  'orbit',
  'otter',
  'panther',
  'pebble',
  'pepper',
  'pilot',
  'pine',
  'prairie',
  'quartz',
  'quiet',
  'raven',
  'ridge',
  'river',
  'rover',
  'saffron',
  'sage',
  'sapphire',
  'shadow',
  'silver',
  'solar',
  'spruce',
  'stellar',
  'summit',
  'sunset',
  'thunder',
  'tiger',
  'timber',
  'topaz',
  'tundra',
  'valley',
  'velvet',
  'violet',
  'walnut',
  'waitress',
  'willow',
  'winter',
  'zenith',
  'zephyr',
];

final _random = Random();

/// Builds a memorable passphrase of [count] distinct words joined by `-`,
/// e.g. `noun-rover-waitress`.
///
/// Seeds the E2EE shared key in the lobby. Readability is the point: the key
/// travels to other participants by voice or chat, and every platform derives
/// the same bytes from the same phrase.
///
/// This is a demo convenience, not a security control — three words from a
/// ~100-word pool is roughly 20 bits, fine for a test call among people who
/// trust each other and nowhere near enough for a real secret.
String getRandomWords([int count = 3]) {
  final pool = [..._words]..shuffle(_random);
  return pool.take(min(count, pool.length)).join('-');
}
