name: Check Docusaurus docs with vale linter

on: [pull_request]

jobs:
  vale:
    name: Vale doc linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          filter_mode: nofilter
          reporter: github-pr-check
          fail_on_error: true
          files: '["docusaurus", "README.md"]'
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
