name: Vale

on:
  pull_request:
    paths:
      - 'docusaurus/**'
      - '.github/workflows/vale-doc-lint.yml'

  workflow_dispatch:

jobs:
  vale:
    name: Check Docusaurus docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          filter_mode: nofilter
          reporter: github-pr-check
          fail_on_error: true
          files: '["docusaurus", "README.md"]'
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
